interface HelpTopic {
  readonly title: string;
  readonly entries: readonly string[];
}

export const HELP_TOPICS: readonly HelpTopic[] = [
  {
    title: 'MOVEMENT',
    entries: [
      'WASD or arrows: move in eight directions.',
      'On touch devices, drag the left thumb pad to move.',
      'Hold Shift while moving: sprint at 125% speed; spends Vigour.',
      '1-0: select a hotbar slot (0 is the tenth slot).',
      '- / + or the world mouse wheel: change world zoom.',
      'Shift - / +: change UI scale.',
    ],
  },
  {
    title: 'ACTIONS',
    entries: [
      'Left click another player or NPC to select it; click empty ground to clear it.',
      'E: use the closest available interaction (chest, NPC, horse, portal, or pickup).',
      'F: swing axes, swords, picks and hoes in the direction you face. Other items use their highlighted target.',
      'On touch devices, the E and F buttons perform these same actions.',
      'Q: drop the selected hotbar item.',
      'Select a damaged tool and press E while facing an anvil to repair it for 5 copper coins.',
      'Hold left mouse with a bow selected to draw; release to fire toward the pointer.',
      'Space: jump while mounted.',
    ],
  },
  {
    title: 'WINDOWS',
    entries: [
      'I: toggle inventory.',
      'C: toggle crafting.',
      'P: open the Character screen for appearance, equipment, vitals, attributes, and experience.',
      'K: open Skill Trees. Learned ranks persist, but their labelled effects are still previews for now.',
      'L: open the Quest Log. Select a quest to inspect objectives and rewards, track it, or drop it.',
      'O: open Expedition Rewards. Camp materials stay saved until collected. If your bags are full, make space and retry. Combat XP is awarded when the camp clears.',
      'Hold Tab: show online players.',
      'Enter or /: open chat or command input.',
      'The speech-bubble button collapses chat; it turns green for unread messages.',
      'Wheel up shows older framed content; drag its scrollbar to browse.',
      'Page Up / Down scroll by a page. Click a scrollbar for arrows and Home / End.',
      'N: toggle nameplates.',
      'Stone-tinted players with a pulsing lightning nameplate are offline and non-interactive.',
      'Z: hide or restore the complete interface.',
      'Esc: menu, back, or close.',
      'The menu includes a full-screen toggle on supported browsers.',
      'F3: player tile coordinates, network, and render metrics.',
      'G: collision and tool-range overlay.',
      'H: hide entity art for a terrain-only debug view.',
    ],
  },
  {
    title: 'CHAT AND COMMANDS',
    entries: [
      'Plain messages go to general chat.',
      '/say <message>: a wrapped bubble visible on screen nearby.',
      '/shout or /yell: a bubble with a finite long range and edge direction marker.',
      '/whisper, /tell, or /w <player> <message>: private chat.',
      '/reply or /r <message>: answer your latest incoming whisper.',
      '/baltop: show the top 10 player balances privately in your chat console.',
      'Tab completes predictions; Up and Down select them.',
      'Owners can use /tp <x> <y>, /tp <player|NPC>, or /tp <player> <player|NPC>. Coordinates are tiles.',
      'Owners can use /last to show recent login and logout times privately in their chat console.',
    ],
  },
  {
    title: 'DIALOGUE AND TRADE',
    entries: [
      'Press E near an NPC to talk. The NPC stops and faces the latest speaker while dialogue is open.',
      'Use 1-4 to choose a conversation response.',
      'In a shop, 1 selects Buy and 2 selects Sell; choose a row and adjust its quantity before confirming.',
      'On quantity +/- controls, Shift-click changes 10; Control-click jumps to minimum or maximum.',
      'Currency is stored as gold, silver, and bronze in your purse rather than inventory slots.',
      'Marlow buys useful carried goods and sells tools, supplies, and one homestead deed per farmer.',
    ],
  },
  {
    title: 'INVENTORY',
    entries: [
      'Click a stack to hold it, then click a valid slot to place or swap it.',
      'Right click a stack to take half; right click while holding to place one item.',
      'A held stack stays on the cursor after mouse release. Left-drag over slots splits it evenly; right-drag places one in each.',
      'Shift-click quick-moves a stack between available containers.',
      'Double-click collects matching items. Double Shift-click quick-moves every matching stack.',
      'Hover a slot and press 1-0 to swap it with that hotbar slot. Q drops one; Control-Q drops the whole stack.',
      'A backpack expands carried storage. Equipment, backpack, and hotbar slots enforce their item rules.',
      'Open chests and barrels with E. Their storage appears beside your inventory.',
    ],
  },
  {
    title: 'CRAFTING',
    entries: [
      'Press C to open the crafting grid and recipe book.',
      'Click a recipe to fill its ingredients from carried inventory when the grid is clear.',
      'Click the result to carry one craft on the cursor; Shift-click crafts repeatedly while ingredients and storage allow.',
      'Nearby workbenches unlock recipes for chests, barrels, fences, gates, signs, standing torches, and arrows.',
      'Basic recipes include planks, sticks, torches, campfires, workbenches, and Orchard Tea.',
      'Select a crafted placeable, aim at a clear highlighted tile, and press F to place it.',
    ],
  },
  {
    title: 'HOMESTEAD DEEDS',
    entries: [
      'Buy your one homestead deed from Marlow; deeds cannot be dropped or sold.',
      'On the overworld, select the deed, aim at a clear grass site, and press F.',
      'A white footprint is valid; a red footprint means terrain, an object, a player, or another homestead blocks the site.',
      'The deed is consumed only when the homestead is successfully established.',
      'Use the tent entrance to visit the homestead space and its southern gate to return to the overworld.',
      'Visitors share the same homestead space. The owner can open or close its farm gate with F.',
    ],
  },
  {
    title: 'SHARED WORLD',
    entries: [
      'Movement, items, NPCs, time, and weather are server authoritative.',
      'Online players share the same world clock, but only see entities and speech in their current space.',
      'Only the owner can change world time, weather, or wind direction.',
      'Wind direction AUTO chooses a shared compass direction automatically.',
      'Cloud shadows appear in daylight or with rain; directional wind sways trees and grass.',
      'Strong wind carries fading leaves from live tree canopies.',
      'Wildlife lives in habitat packs; distant packs sleep until a farmer approaches.',
      'Livestock and birds settle at night. Bees return to hives that slowly store honey.',
      'Nameplate visibility and zoom are local display settings.',
    ],
  },
  {
    title: 'HORSES',
    entries: [
      'Only one player can ride a horse at a time.',
      'Wild horses are nameless; Nados Mum remains the named island horse.',
      'Mounted movement is twice walking speed.',
      'Tools and item dropping are disabled while mounted.',
      'A jump crosses at most three freshwater or oasis-water tiles.',
      'Horses cannot jump cliffs, ridges, waterfalls, ocean, trees, or unsafe landings.',
      'Horses can travel between the overworld and a homestead exterior. Dismount before entering tents, interiors, caves, or underground spaces.',
    ],
  },
  {
    title: 'ITEMS AND TOOLS',
    entries: [
      'Swings hit all contacts in their arc and wear the tool for each contact. Hover over a tool for its details.',
      'Pickups and inventory moves succeed only when the server validates capacity.',
      'The axe harvests trees. Chopped trees regrow over one game day; rain helps a little.',
      'The pickaxe mines ore with a short, narrow swing. Left-click an exposed cellar wall to excavate it.',
      'Select the hoe and left-click grass up to 3 tiles away to till it. Right-click tilled soil to restore grass.',
      'Select the watering can and target tilled soil up to 3 tiles away to water it.',
      'Select the fishing rod and target a clear water tile up to 3 tiles away. Fish shadows mark productive pools.',
      'Chests and crafted placeables use the same tile target. A red frame means placement is blocked.',
      'Neighbouring soil automatically joins into rows, corners, edges, and filled plots.',
      'Rare ore veins are isolated points of interest with large reserves.',
      'Ore drops every third hit. Ordinary rocks break once and drop one stone.',
      'Successful tool uses consume Vigour and one durability; rejected actions and whiffs do not wear tools.',
      'A broken tool stays in its slot. Select it and press E while facing an anvil; 5 copper coins repair it fully.',
      'Durability bars are green, then gold, then red as the tool wears down.',
      'Craft Orchard Tea from an apple and pear; select it and press F to drink it.',
      'Equip a lantern or torch in the Off Hand slot, then press F to switch it. F also switches a nearby dropped light; E picks it up.',
      'Press E at a fence gate to open or close it.',
    ],
  },
  {
    title: 'HELP BOOK',
    entries: [
      'Pick a chapter tab along the top and a topic on the left page. Left / Right or Q / E turn to the previous or next topic; Up / Down move through the list.',
      'Escape or X returns to the menu.',
      'This book describes implemented controls and rules, not planned features.',
    ],
  },
] as const;

