import { uiLabGameOptions } from '../game-mock.js';
import type { UiLabSpecimen } from '../registry.js';
export const migrationSpecimens: readonly UiLabSpecimen[] = [
  {id:'migration-build-palette',title:'Homestead Build Palette',district:'migration',size:{width:640,height:640},closable:false,matrix:{mode:['stocked','poor','max','empty']},build(ui,props,mock){return ui.gameSurface(uiLabGameOptions('build-palette',props,mock));}},
  {id:'migration-delve-confirmation',title:'Start Delve',district:'migration',size:{width:760,height:470},closable:false,build(ui,props,mock){return ui.gameSurface(uiLabGameOptions('delve-confirmation',props,mock));}},
  {id:'migration-delve-rewards',title:'Delve Rewards',district:'migration',size:{width:1080,height:650},closable:false,matrix:{mode:['shop','boon','poor']},build(ui,props,mock){return ui.gameSurface(uiLabGameOptions('delve-rewards',props,mock));}},
  { id:'migration-statistics',title:'Lifetime Statistics',district:'migration',size:{width:920,height:640},closable:true,build(ui,props,mock){return ui.gameSurface(uiLabGameOptions('statistics',props,mock));} },
  { id: 'migration-gateway', title: 'Gateway / Account Entry', district: 'migration', size: { width: 620, height: 420 }, closable: false, matrix: { mode: ['signed-out', 'signed-in', 'local', 'busy', 'error', 'loading', 'connection-error'] },
    build(ui, props, mock) { return ui.gameSurface(uiLabGameOptions('gateway', props, mock)); },
  },
  { id: 'migration-character-name', title: 'Character Name Prompt', district: 'migration', size: { width: 760, height: 470 }, closable: false, matrix: { mode: ['editing', 'saving', 'taken'] },
    build(ui, props, mock) { return ui.gameSurface(uiLabGameOptions('character-name', props, mock)); },
  },
  { id: 'migration-update-ready', title: 'Update Ready', district: 'migration', size: { width: 560, height: 340 }, closable: false,
    build(ui, props, mock) { return ui.gameSurface(uiLabGameOptions('update-ready', props, mock)); },
  },
  { id: 'migration-zone-minimap', title: 'Zone, Time & Minimap', district: 'migration', size: { width: 540, height: 270 }, closable: false,
    build(ui, props, mock) { return ui.gameSurface(uiLabGameOptions('zone-minimap', props, mock)); },
  },
  { id: 'migration-hotbar-vitals', title: 'Hotbar & Player Vitals', district: 'migration', size: { width: 760, height: 380 }, closable: false,
    build(ui, props, mock) { return ui.gameSurface(uiLabGameOptions('hotbar-vitals', props, mock)); },
  },
  { id: 'migration-target-effects', title: 'Target & Status Effects', district: 'migration', size: { width: 520, height: 290 }, closable: false,
    build(ui, props, mock) { return ui.gameSurface(uiLabGameOptions('target-effects', props, mock)); },
  },
  { id: 'migration-chat', title: 'Chat', district: 'migration', size: { width: 660, height: 420 }, closable: false, matrix: { mode: ['expanded', 'collapsed', 'unread', 'commands'] },
    build(ui, props, mock) { return ui.gameSurface(uiLabGameOptions('chat', props, mock)); },
  },
  { id: 'migration-quest-tracker', title: 'Quest Tracker', district: 'migration', size: { width: 430, height: 300 }, closable: false,
    build(ui, props, mock) { return ui.gameSurface(uiLabGameOptions('quest-tracker', props, mock)); },
  },
  { id: 'migration-online-players', title: 'Online Players', district: 'migration', size: { width: 600, height: 500 }, closable: true,
    build(ui, props, mock) { return ui.gameSurface(uiLabGameOptions('online-players', props, mock)); },
  },
  { id: 'migration-feedback-overlays', title: 'Nameplates & Feedback', district: 'migration', size: { width: 800, height: 1120 }, closable: false,
    build(ui, props, mock) { return ui.gameSurface(uiLabGameOptions('feedback-overlays', props, mock)); },
  },
  { id: 'migration-touch-controls', title: 'Touch Actions', district: 'migration', size: { width: 760, height: 560 }, closable: false,
    build(ui, props, mock) { return ui.gameSurface(uiLabGameOptions('touch-controls', props, mock)); },
  },
  { id: 'migration-inventory', title: 'Inventory / Pack', district: 'migration', size: { width: 920, height: 430 }, closable: true,
    build(ui, props, mock) { return ui.gameSurface(uiLabGameOptions('inventory', props, mock)); },
  },
  { id: 'migration-crafting', title: 'Crafting & Recipes', district: 'migration', size: { width: 980, height: 450 }, closable: true,
    build(ui, props, mock) { return ui.gameSurface(uiLabGameOptions('crafting', props, mock)); },
  },
  { id: 'migration-chest', title: 'Chest Storage', district: 'migration', size: { width: 780, height: 420 }, closable: true,
    build(ui, props, mock) { return ui.gameSurface(uiLabGameOptions('chest', props, mock)); },
  },
  { id: 'migration-barrel', title: 'Barrel Storage', district: 'migration', size: { width: 500, height: 440 }, closable: true, matrix: { sealed: [false, true] },
    build(ui, props, mock) { return ui.gameSurface(uiLabGameOptions('barrel', props, mock)); },
  },
  { id: 'migration-furnace', title: 'Furnace', district: 'migration', size: { width: 900, height: 420 }, closable: true, matrix: { mode: ['idle', 'active'] },
    build(ui, props, mock) { return ui.gameSurface(uiLabGameOptions('furnace', props, mock)); },
  },
  { id: 'migration-cooking', title: 'Cooking Fire', district: 'migration', size: { width: 900, height: 420 }, closable: true, matrix: { mode: ['idle', 'active', 'unlit', 'batch'] },
    build(ui, props, mock) { return ui.gameSurface(uiLabGameOptions('cooking', props, mock)); },
  },
  { id: 'migration-press', title: 'Fruit Press', district: 'migration', size: { width: 900, height: 420 }, closable: true, matrix: { mode: ['idle', 'active'] },
    build(ui, props, mock) { return ui.gameSurface(uiLabGameOptions('press', props, mock)); },
  },
  { id: 'migration-fermentation', title: 'Fermentation Cask', district: 'migration', size: { width: 900, height: 420 }, closable: true, matrix: { mode: ['idle', 'active'] },
    build(ui, props, mock) { return ui.gameSurface(uiLabGameOptions('fermentation', props, mock)); },
  },
  { id: 'migration-character', title: 'Character', district: 'migration', size: { width: 980, height: 500 }, closable: true,
    build(ui, props, mock) { return ui.gameSurface(uiLabGameOptions('character', props, mock)); },
  },
  { id: 'migration-skills', title: 'Skill Tree', district: 'migration', size: { width: 980, height: 500 }, closable: true,
    build(ui, props, mock) { return ui.gameSurface(uiLabGameOptions('skills', props, mock)); },
  },
  { id: 'migration-quest-log', title: 'Quest Log', district: 'migration', size: { width: 800, height: 410 }, closable: true,
    build(ui, props, mock) { return ui.gameSurface(uiLabGameOptions('quest-log', props, mock)); },
  },
  { id: 'migration-help-book', title: 'Help Book', district: 'migration', size: { width: 840, height: 440 }, closable: true,
    build(ui, props, mock) { return ui.gameSurface(uiLabGameOptions('help-book', props, mock)); },
  },
  { id: 'migration-npc-dialogue', title: 'NPC Dialogue', district: 'migration', size: { width: 740, height: 330 }, closable: true,
    build(ui, props, mock) { return ui.gameSurface(uiLabGameOptions('npc-dialogue', props, mock)); },
  },
  { id: 'migration-merchant-shop', title: 'Merchant Shop', district: 'migration', size: { width: 900, height: 350 }, closable: true,
    build(ui, props, mock) { return ui.gameSurface(uiLabGameOptions('merchant-shop', props, mock)); },
  },
  { id: 'migration-player-trade', title: 'Player Trade', district: 'migration', size: { width: 840, height: 380 }, closable: true,
    build(ui, props, mock) { return ui.gameSurface(uiLabGameOptions('player-trade', props, mock)); },
  },
  { id: 'migration-game-menu', title: 'Game Menu', district: 'migration', size: { width: 520, height: 350 }, closable: true, matrix: { mode: ['regular', 'privileged', 'checking', 'updating', 'fullscreen-unavailable'] },
    build(ui, props, mock) { return ui.gameSurface(uiLabGameOptions('game-menu', props, mock)); },
  },
  { id: 'migration-settings', title: 'Settings', district: 'migration', size: { width: 900, height: 390 }, closable: true, matrix: { page: ['gameplay', 'controls', 'video', 'audio', 'interface', 'accessibility'] },
    build(ui, props, mock) { return ui.gameSurface(uiLabGameOptions('settings', props, mock)); },
  },
  { id: 'migration-developer', title: 'Developer Tools', district: 'migration', size: { width: 900, height: 410 }, closable: true, matrix: { page: ['world', 'player', 'quests', 'render'] },
    build(ui, props, mock) { return ui.gameSurface(uiLabGameOptions('developer', props, mock)); },
  },
];
