/* Generated by packages/tools/src/extract-cute-fantasy-npcs.ts. */
export type CuteFantasyActorKind = 'npc' | 'faction' | 'enemy' | 'effect';

export interface CuteFantasyActorCatalogEntry {
  readonly id: string;
  readonly label: string;
  readonly asset: string;
  readonly kind: CuteFantasyActorKind;
  readonly family: string;
  readonly size: readonly [number, number];
  readonly animations: readonly string[];
  readonly sourcePath: string;
  readonly companions: readonly string[];
}

export const CUTE_FANTASY_ACTOR_CATALOG = [
  {
    "id": "npc_cf_desert_person_01",
    "label": "Desert Person 1",
    "asset": "npc_cf_desert_person_01",
    "kind": "npc",
    "family": "Desert",
    "size": [
      32,
      32
    ],
    "animations": [
      "idle_down",
      "idle_right",
      "idle_up",
      "walk_down",
      "walk_right",
      "walk_up",
      "defeat",
      "hurt_down",
      "hurt_right",
      "hurt_up"
    ],
    "sourcePath": "references/Cute_Fantasy_Desert/NPC/Desert_Person_1.png",
    "companions": []
  },
  {
    "id": "npc_cf_desert_person_02",
    "label": "Desert Person 2",
    "asset": "npc_cf_desert_person_02",
    "kind": "npc",
    "family": "Desert",
    "size": [
      32,
      32
    ],
    "animations": [
      "idle_down",
      "idle_right",
      "idle_up",
      "walk_down",
      "walk_right",
      "walk_up",
      "defeat",
      "hurt_down",
      "hurt_right",
      "hurt_up"
    ],
    "sourcePath": "references/Cute_Fantasy_Desert/NPC/Desert_Person_2.png",
    "companions": []
  },
  {
    "id": "npc_cf_desert_person_03",
    "label": "Desert Person 3",
    "asset": "npc_cf_desert_person_03",
    "kind": "npc",
    "family": "Desert",
    "size": [
      32,
      32
    ],
    "animations": [
      "idle_down",
      "idle_right",
      "idle_up",
      "walk_down",
      "walk_right",
      "walk_up",
      "defeat",
      "hurt_down",
      "hurt_right",
      "hurt_up"
    ],
    "sourcePath": "references/Cute_Fantasy_Desert/NPC/Desert_Person_3.png",
    "companions": []
  },
  {
    "id": "npc_cf_desert_person_04",
    "label": "Desert Person 4",
    "asset": "npc_cf_desert_person_04",
    "kind": "npc",
    "family": "Desert",
    "size": [
      32,
      32
    ],
    "animations": [
      "idle_down",
      "idle_right",
      "idle_up",
      "walk_down",
      "walk_right",
      "walk_up",
      "defeat",
      "hurt_down",
      "hurt_right",
      "hurt_up"
    ],
    "sourcePath": "references/Cute_Fantasy_Desert/NPC/Desert_Person_4.png",
    "companions": []
  },
  {
    "id": "npc_cf_desert_trader_01",
    "label": "Desert Trader 1",
    "asset": "npc_cf_desert_trader_01",
    "kind": "npc",
    "family": "Desert",
    "size": [
      32,
      32
    ],
    "animations": [
      "idle"
    ],
    "sourcePath": "references/Cute_Fantasy_Desert/NPC/Traders/Desert_Trader_1.png",
    "companions": []
  },
  {
    "id": "npc_cf_desert_trader_02",
    "label": "Desert Trader 2",
    "asset": "npc_cf_desert_trader_02",
    "kind": "npc",
    "family": "Desert",
    "size": [
      32,
      32
    ],
    "animations": [
      "idle"
    ],
    "sourcePath": "references/Cute_Fantasy_Desert/NPC/Traders/Desert_Trader_2.png",
    "companions": []
  },
  {
    "id": "npc_cf_desert_trader_03",
    "label": "Desert Trader 3",
    "asset": "npc_cf_desert_trader_03",
    "kind": "npc",
    "family": "Desert",
    "size": [
      32,
      32
    ],
    "animations": [
      "idle"
    ],
    "sourcePath": "references/Cute_Fantasy_Desert/NPC/Traders/Desert_Trader_3.png",
    "companions": []
  },
  {
    "id": "npc_cf_pharaoh",
    "label": "Pharaoh",
    "asset": "npc_cf_pharaoh",
    "kind": "npc",
    "family": "Desert",
    "size": [
      32,
      32
    ],
    "animations": [
      "idle_down",
      "idle_right",
      "idle_up",
      "walk_down",
      "walk_right",
      "walk_up",
      "defeat",
      "hurt_down",
      "hurt_right",
      "hurt_up"
    ],
    "sourcePath": "references/Cute_Fantasy_Desert/NPC/Pharaoh.png",
    "companions": []
  },
  {
    "id": "npc_cf_reindeer",
    "label": "Reindeer",
    "asset": "npc_cf_reindeer",
    "kind": "npc",
    "family": "Holiday",
    "size": [
      64,
      64
    ],
    "animations": [
      "idle_side",
      "walk_side",
      "run_side"
    ],
    "sourcePath": "references/Cute_Fantasy_Christmass/Characters/Reindeer.png",
    "companions": []
  },
  {
    "id": "npc_cf_santa_claus",
    "label": "Santa Claus",
    "asset": "npc_cf_santa_claus",
    "kind": "npc",
    "family": "Holiday",
    "size": [
      32,
      32
    ],
    "animations": [
      "idle_down",
      "idle_right",
      "idle_up",
      "walk_down",
      "walk_right",
      "walk_up",
      "defeat",
      "hurt_down",
      "hurt_right",
      "hurt_up"
    ],
    "sourcePath": "references/Cute_Fantasy_Christmass/Characters/Santa_Claus.png",
    "companions": []
  },
  {
    "id": "npc_cf_santa_helper",
    "label": "Santa Helper",
    "asset": "npc_cf_santa_helper",
    "kind": "npc",
    "family": "Holiday",
    "size": [
      32,
      32
    ],
    "animations": [
      "idle_down",
      "idle_right",
      "idle_up",
      "walk_down",
      "walk_right",
      "walk_up",
      "defeat",
      "hurt_down",
      "hurt_right",
      "hurt_up"
    ],
    "sourcePath": "references/Cute_Fantasy_Christmass/Characters/Santa_Claus_Helper.png",
    "companions": []
  },
  {
    "id": "npc_cf_witch",
    "label": "Witch",
    "asset": "npc_cf_witch",
    "kind": "npc",
    "family": "Holiday",
    "size": [
      32,
      32
    ],
    "animations": [
      "idle_down",
      "idle_right",
      "idle_up",
      "walk_down",
      "walk_right",
      "walk_up",
      "cast_down",
      "cast_right",
      "cast_up"
    ],
    "sourcePath": "references/Cute_Fantasy_Halloween/Witch/Witch.png",
    "companions": [
      "effect_cf_witch_bat",
      "effect_cf_witch_broom",
      "effect_cf_witch_cauldron"
    ]
  },
  {
    "id": "npc_cf_bartender_bruno",
    "label": "Bartender Bruno",
    "asset": "npc_cf_bartender_bruno",
    "kind": "npc",
    "family": "Professions",
    "size": [
      32,
      40
    ],
    "animations": [
      "idle_down",
      "idle_right",
      "idle_up",
      "walk_down",
      "walk_right",
      "walk_up",
      "defeat"
    ],
    "sourcePath": "references/Cute_Fantasy/NPCs (Premade)/Bartender_Bruno.png",
    "companions": []
  },
  {
    "id": "npc_cf_bartender_katy",
    "label": "Bartender Katy",
    "asset": "npc_cf_bartender_katy",
    "kind": "npc",
    "family": "Professions",
    "size": [
      32,
      40
    ],
    "animations": [
      "idle_down",
      "idle_right",
      "idle_up",
      "walk_down",
      "walk_right",
      "walk_up",
      "defeat"
    ],
    "sourcePath": "references/Cute_Fantasy/NPCs (Premade)/Bartender_Katy.png",
    "companions": []
  },
  {
    "id": "npc_cf_chef_chloe",
    "label": "Chef Chloe",
    "asset": "npc_cf_chef_chloe",
    "kind": "npc",
    "family": "Professions",
    "size": [
      32,
      40
    ],
    "animations": [
      "idle_down",
      "idle_right",
      "idle_up",
      "walk_down",
      "walk_right",
      "walk_up",
      "defeat"
    ],
    "sourcePath": "references/Cute_Fantasy/NPCs (Premade)/Chef_Chloe.png",
    "companions": []
  },
  {
    "id": "npc_cf_farmer_bob",
    "label": "Farmer Bob",
    "asset": "npc_cf_farmer_bob",
    "kind": "npc",
    "family": "Professions",
    "size": [
      32,
      40
    ],
    "animations": [
      "idle_down",
      "idle_right",
      "idle_up",
      "walk_down",
      "walk_right",
      "walk_up",
      "defeat",
      "chop_down",
      "chop_right",
      "chop_up",
      "water_down",
      "water_right",
      "water_up"
    ],
    "sourcePath": "references/Cute_Fantasy/NPCs (Premade)/Farmer_Bob.png",
    "companions": []
  },
  {
    "id": "npc_cf_farmer_buba",
    "label": "Farmer Buba",
    "asset": "npc_cf_farmer_buba",
    "kind": "npc",
    "family": "Professions",
    "size": [
      32,
      40
    ],
    "animations": [
      "idle_down",
      "idle_right",
      "idle_up",
      "walk_down",
      "walk_right",
      "walk_up",
      "defeat",
      "chop_down",
      "chop_right",
      "chop_up",
      "water_down",
      "water_right",
      "water_up"
    ],
    "sourcePath": "references/Cute_Fantasy/NPCs (Premade)/Farmer_Buba.png",
    "companions": []
  },
  {
    "id": "npc_cf_fisherman_fin",
    "label": "Fisherman Fin",
    "asset": "npc_cf_fisherman_fin",
    "kind": "npc",
    "family": "Professions",
    "size": [
      32,
      40
    ],
    "animations": [
      "idle_down",
      "idle_right",
      "idle_up",
      "walk_down",
      "walk_right",
      "walk_up",
      "defeat",
      "cast_down",
      "cast_right",
      "cast_up",
      "reel_down",
      "reel_right",
      "reel_up"
    ],
    "sourcePath": "references/Cute_Fantasy/NPCs (Premade)/Fisherman_Fin.png",
    "companions": []
  },
  {
    "id": "npc_cf_lumberjack_jack",
    "label": "Lumberjack Jack",
    "asset": "npc_cf_lumberjack_jack",
    "kind": "npc",
    "family": "Professions",
    "size": [
      32,
      40
    ],
    "animations": [
      "idle_down",
      "idle_right",
      "idle_up",
      "walk_down",
      "walk_right",
      "walk_up",
      "defeat",
      "chop_down",
      "chop_right",
      "chop_up"
    ],
    "sourcePath": "references/Cute_Fantasy/NPCs (Premade)/Lumberjack_Jack.png",
    "companions": []
  },
  {
    "id": "npc_cf_miner_mike",
    "label": "Miner Mike",
    "asset": "npc_cf_miner_mike",
    "kind": "npc",
    "family": "Professions",
    "size": [
      32,
      40
    ],
    "animations": [
      "idle_down",
      "idle_right",
      "idle_up",
      "walk_down",
      "walk_right",
      "walk_up",
      "defeat",
      "mine_down",
      "mine_right",
      "mine_up"
    ],
    "sourcePath": "references/Cute_Fantasy/NPCs (Premade)/Miner_Mike.png",
    "companions": []
  },
  {
    "id": "actor_cf_angel_01",
    "label": "Angel 1",
    "asset": "actor_cf_angel_01",
    "kind": "faction",
    "family": "Angels",
    "size": [
      64,
      64
    ],
    "animations": [
      "idle_down",
      "idle_right",
      "idle_up",
      "walk_down",
      "walk_right",
      "walk_up",
      "defeat",
      "attack_down",
      "attack_right",
      "attack_up",
      "hurt_down",
      "hurt_right",
      "hurt_up"
    ],
    "sourcePath": "references/Cute_Fantasy_Characters/Angels/Angel_1.png",
    "companions": []
  },
  {
    "id": "actor_cf_angel_02",
    "label": "Angel 2",
    "asset": "actor_cf_angel_02",
    "kind": "faction",
    "family": "Angels",
    "size": [
      64,
      64
    ],
    "animations": [
      "idle_down",
      "idle_right",
      "idle_up",
      "walk_down",
      "walk_right",
      "walk_up",
      "defeat",
      "attack_down",
      "attack_right",
      "attack_up",
      "hurt_down",
      "hurt_right",
      "hurt_up"
    ],
    "sourcePath": "references/Cute_Fantasy_Characters/Angels/Angel_2.png",
    "companions": []
  },
  {
    "id": "actor_cf_goblin_archer",
    "label": "Goblin Archer",
    "asset": "actor_cf_goblin_archer",
    "kind": "faction",
    "family": "Goblins",
    "size": [
      48,
      48
    ],
    "animations": [
      "idle_down",
      "idle_right",
      "idle_up",
      "walk_down",
      "walk_right",
      "walk_up",
      "defeat",
      "attack_down",
      "attack_right",
      "attack_up",
      "hurt_down",
      "hurt_right",
      "hurt_up"
    ],
    "sourcePath": "references/Cute_Fantasy_Characters/Goblins/Goblin_Archer.png",
    "companions": [
      "effect_cf_bow_stages",
      "projectile_cf_crossbow_bolt"
    ]
  },
  {
    "id": "actor_cf_goblin_maceman",
    "label": "Goblin Maceman",
    "asset": "actor_cf_goblin_maceman",
    "kind": "faction",
    "family": "Goblins",
    "size": [
      32,
      32
    ],
    "animations": [
      "idle_down",
      "idle_right",
      "idle_up",
      "walk_down",
      "walk_right",
      "walk_up",
      "defeat",
      "attack_down",
      "attack_right",
      "attack_up",
      "hurt_down",
      "hurt_right",
      "hurt_up"
    ],
    "sourcePath": "references/Cute_Fantasy_Characters/Goblins/Goblin_Maceman.png",
    "companions": []
  },
  {
    "id": "actor_cf_goblin_spearman",
    "label": "Goblin Spearman",
    "asset": "actor_cf_goblin_spearman",
    "kind": "faction",
    "family": "Goblins",
    "size": [
      48,
      48
    ],
    "animations": [
      "idle_down",
      "idle_right",
      "idle_up",
      "walk_down",
      "walk_right",
      "walk_up",
      "defeat",
      "attack_down",
      "attack_right",
      "attack_up",
      "hurt_down",
      "hurt_right",
      "hurt_up"
    ],
    "sourcePath": "references/Cute_Fantasy_Characters/Goblins/Goblin_Spearman.png",
    "companions": []
  },
  {
    "id": "actor_cf_goblin_thief",
    "label": "Goblin Thief",
    "asset": "actor_cf_goblin_thief",
    "kind": "faction",
    "family": "Goblins",
    "size": [
      32,
      32
    ],
    "animations": [
      "idle_down",
      "idle_right",
      "idle_up",
      "walk_down",
      "walk_right",
      "walk_up",
      "defeat",
      "attack_down",
      "attack_right",
      "attack_up",
      "hurt_down",
      "hurt_right",
      "hurt_up"
    ],
    "sourcePath": "references/Cute_Fantasy_Characters/Goblins/Goblin_Thief.png",
    "companions": []
  },
  {
    "id": "actor_cf_knight_archer",
    "label": "Knight Archer",
    "asset": "actor_cf_knight_archer",
    "kind": "faction",
    "family": "Knights",
    "size": [
      48,
      48
    ],
    "animations": [
      "idle_down",
      "idle_right",
      "idle_up",
      "walk_down",
      "walk_right",
      "walk_up",
      "defeat",
      "attack_down",
      "attack_right",
      "attack_up",
      "hurt_down",
      "hurt_right",
      "hurt_up"
    ],
    "sourcePath": "references/Cute_Fantasy_Characters/Knights/Archer.png",
    "companions": [
      "effect_cf_bow_stages",
      "projectile_cf_crossbow_bolt"
    ]
  },
  {
    "id": "actor_cf_knight_spearman",
    "label": "Knight Spearman",
    "asset": "actor_cf_knight_spearman",
    "kind": "faction",
    "family": "Knights",
    "size": [
      48,
      48
    ],
    "animations": [
      "idle_down",
      "idle_right",
      "idle_up",
      "walk_down",
      "walk_right",
      "walk_up",
      "defeat",
      "attack_down",
      "attack_right",
      "attack_up",
      "hurt_down",
      "hurt_right",
      "hurt_up"
    ],
    "sourcePath": "references/Cute_Fantasy_Characters/Knights/Spearman.png",
    "companions": []
  },
  {
    "id": "actor_cf_knight_swordman",
    "label": "Knight Swordman",
    "asset": "actor_cf_knight_swordman",
    "kind": "faction",
    "family": "Knights",
    "size": [
      48,
      48
    ],
    "animations": [
      "idle_down",
      "idle_right",
      "idle_up",
      "walk_down",
      "walk_right",
      "walk_up",
      "defeat",
      "attack_down",
      "attack_right",
      "attack_up",
      "hurt_down",
      "hurt_right",
      "hurt_up"
    ],
    "sourcePath": "references/Cute_Fantasy_Characters/Knights/Swordman.png",
    "companions": []
  },
  {
    "id": "actor_cf_knight_templar",
    "label": "Knight Templar",
    "asset": "actor_cf_knight_templar",
    "kind": "faction",
    "family": "Knights",
    "size": [
      48,
      48
    ],
    "animations": [
      "idle_down",
      "idle_right",
      "idle_up",
      "walk_down",
      "walk_right",
      "walk_up",
      "defeat",
      "attack_down",
      "attack_right",
      "attack_up",
      "hurt_down",
      "hurt_right",
      "hurt_up"
    ],
    "sourcePath": "references/Cute_Fantasy_Characters/Knights/Templar.png",
    "companions": []
  },
  {
    "id": "actor_cf_orc_archer",
    "label": "Orc Archer",
    "asset": "actor_cf_orc_archer",
    "kind": "faction",
    "family": "Orcs",
    "size": [
      48,
      48
    ],
    "animations": [
      "idle_down",
      "idle_right",
      "idle_up",
      "walk_down",
      "walk_right",
      "walk_up",
      "defeat",
      "attack_down",
      "attack_right",
      "attack_up",
      "hurt_down",
      "hurt_right",
      "hurt_up"
    ],
    "sourcePath": "references/Cute_Fantasy_Characters/Orcs/Orc_Archer.png",
    "companions": [
      "effect_cf_bow_stages",
      "projectile_cf_crossbow_bolt"
    ]
  },
  {
    "id": "actor_cf_orc_chief",
    "label": "Orc Chief",
    "asset": "actor_cf_orc_chief",
    "kind": "faction",
    "family": "Orcs",
    "size": [
      64,
      64
    ],
    "animations": [
      "idle_down",
      "idle_right",
      "idle_up",
      "walk_down",
      "walk_right",
      "walk_up",
      "special",
      "defeat"
    ],
    "sourcePath": "references/Cute_Fantasy_Characters/Orcs/Orc_Chief.png",
    "companions": []
  },
  {
    "id": "actor_cf_orc_grunt",
    "label": "Orc Grunt",
    "asset": "actor_cf_orc_grunt",
    "kind": "faction",
    "family": "Orcs",
    "size": [
      64,
      64
    ],
    "animations": [
      "idle_down",
      "idle_right",
      "idle_up",
      "walk_down",
      "walk_right",
      "walk_up",
      "special",
      "defeat"
    ],
    "sourcePath": "references/Cute_Fantasy_Characters/Orcs/Orc_Grunt.png",
    "companions": []
  },
  {
    "id": "actor_cf_orc_peon",
    "label": "Orc Peon",
    "asset": "actor_cf_orc_peon",
    "kind": "faction",
    "family": "Orcs",
    "size": [
      64,
      64
    ],
    "animations": [
      "idle_down",
      "idle_right",
      "idle_up",
      "walk_down",
      "walk_right",
      "walk_up",
      "special",
      "defeat"
    ],
    "sourcePath": "references/Cute_Fantasy_Characters/Orcs/Orc_Peon.png",
    "companions": []
  },
  {
    "id": "enemy_cf_desert_atgier_01",
    "label": "Desert Atgier 1",
    "asset": "enemy_cf_desert_atgier_01",
    "kind": "enemy",
    "family": "Desert Hostiles",
    "size": [
      64,
      64
    ],
    "animations": [
      "idle_down",
      "idle_right",
      "idle_up",
      "walk_down",
      "walk_right",
      "walk_up",
      "defeat",
      "attack_down",
      "attack_right",
      "attack_up",
      "hurt_down",
      "hurt_right",
      "hurt_up"
    ],
    "sourcePath": "references/Cute_Fantasy_Desert/enemies/Desert_Warrior_Atgier_1.png",
    "companions": []
  },
  {
    "id": "enemy_cf_desert_atgier_02",
    "label": "Desert Atgier 2",
    "asset": "enemy_cf_desert_atgier_02",
    "kind": "enemy",
    "family": "Desert Hostiles",
    "size": [
      64,
      64
    ],
    "animations": [
      "idle_down",
      "idle_right",
      "idle_up",
      "walk_down",
      "walk_right",
      "walk_up",
      "defeat",
      "attack_down",
      "attack_right",
      "attack_up",
      "hurt_down",
      "hurt_right",
      "hurt_up"
    ],
    "sourcePath": "references/Cute_Fantasy_Desert/enemies/Desert_Warrior_Atgier_2.png",
    "companions": []
  },
  {
    "id": "enemy_cf_desert_bow_01",
    "label": "Desert Bowman 1",
    "asset": "enemy_cf_desert_bow_01",
    "kind": "enemy",
    "family": "Desert Hostiles",
    "size": [
      64,
      64
    ],
    "animations": [
      "idle_down",
      "idle_right",
      "idle_up",
      "walk_down",
      "walk_right",
      "walk_up",
      "defeat",
      "attack_down",
      "attack_right",
      "attack_up",
      "hurt_down",
      "hurt_right",
      "hurt_up"
    ],
    "sourcePath": "references/Cute_Fantasy_Desert/enemies/Desert_Warrior_Bow_1.png",
    "companions": [
      "effect_cf_bow_stages",
      "projectile_cf_crossbow_bolt"
    ]
  },
  {
    "id": "enemy_cf_desert_bow_02",
    "label": "Desert Bowman 2",
    "asset": "enemy_cf_desert_bow_02",
    "kind": "enemy",
    "family": "Desert Hostiles",
    "size": [
      64,
      64
    ],
    "animations": [
      "idle_down",
      "idle_right",
      "idle_up",
      "walk_down",
      "walk_right",
      "walk_up",
      "defeat",
      "attack_down",
      "attack_right",
      "attack_up",
      "hurt_down",
      "hurt_right",
      "hurt_up"
    ],
    "sourcePath": "references/Cute_Fantasy_Desert/enemies/Desert_Warrior_Bow_2.png",
    "companions": [
      "effect_cf_bow_stages",
      "projectile_cf_crossbow_bolt"
    ]
  },
  {
    "id": "enemy_cf_mummy",
    "label": "Mummy",
    "asset": "enemy_cf_mummy",
    "kind": "enemy",
    "family": "Desert Hostiles",
    "size": [
      32,
      32
    ],
    "animations": [
      "idle_down",
      "idle_right",
      "idle_up",
      "walk_down",
      "walk_right",
      "walk_up",
      "defeat",
      "attack_down",
      "attack_right",
      "attack_up",
      "hurt_down",
      "hurt_right",
      "hurt_up"
    ],
    "sourcePath": "references/Cute_Fantasy_Desert/enemies/Mummy.png",
    "companions": []
  },
  {
    "id": "enemy_cf_shroomling_alive_big",
    "label": "Alive Shroomling (Big)",
    "asset": "enemy_cf_shroomling_alive_big",
    "kind": "enemy",
    "family": "Shroomlands",
    "size": [
      16,
      16
    ],
    "animations": [
      "state_01",
      "state_02",
      "state_03"
    ],
    "sourcePath": "references/Cute_Fantasy_ShroomLands/Shroomlings/Big_Alive_Shroomling.png",
    "companions": []
  },
  {
    "id": "enemy_cf_shroomling_alive_small",
    "label": "Alive Shroomling (Small)",
    "asset": "enemy_cf_shroomling_alive_small",
    "kind": "enemy",
    "family": "Shroomlands",
    "size": [
      16,
      16
    ],
    "animations": [
      "state_01",
      "state_02",
      "state_03"
    ],
    "sourcePath": "references/Cute_Fantasy_ShroomLands/Shroomlings/Small_Alive_Shroomling.png",
    "companions": []
  },
  {
    "id": "enemy_cf_shroomling_blue",
    "label": "Blue Shroomling",
    "asset": "enemy_cf_shroomling_blue",
    "kind": "enemy",
    "family": "Shroomlands",
    "size": [
      16,
      16
    ],
    "animations": [
      "state_01",
      "state_02",
      "state_03",
      "state_04",
      "state_05",
      "state_06",
      "state_07",
      "state_08",
      "state_09",
      "state_10",
      "state_11",
      "state_12",
      "state_13",
      "state_14",
      "state_15",
      "state_16",
      "state_17",
      "state_18",
      "state_19",
      "state_20",
      "state_21",
      "state_22",
      "state_23",
      "state_24",
      "state_25",
      "state_26"
    ],
    "sourcePath": "references/Cute_Fantasy_ShroomLands/Shroomlings/Blue_Shroomling.png",
    "companions": []
  },
  {
    "id": "enemy_cf_bombschroom",
    "label": "Bombschroom",
    "asset": "enemy_cf_bombschroom",
    "kind": "enemy",
    "family": "Shroomlands",
    "size": [
      16,
      16
    ],
    "animations": [
      "state_01",
      "state_02",
      "state_03",
      "state_04",
      "state_05",
      "state_06",
      "state_07",
      "state_08",
      "state_09",
      "state_10",
      "state_11",
      "state_12",
      "state_13",
      "state_14",
      "state_15",
      "state_16",
      "state_17",
      "state_18",
      "state_19",
      "state_20",
      "state_21"
    ],
    "sourcePath": "references/Cute_Fantasy/Enemies/Bombschroom/Bombschroom.png",
    "companions": [
      "effect_cf_bombschroom_gas"
    ]
  },
  {
    "id": "enemy_cf_shroomling_green",
    "label": "Green Shroomling",
    "asset": "enemy_cf_shroomling_green",
    "kind": "enemy",
    "family": "Shroomlands",
    "size": [
      16,
      16
    ],
    "animations": [
      "state_01",
      "state_02",
      "state_03",
      "state_04",
      "state_05",
      "state_06",
      "state_07",
      "state_08",
      "state_09",
      "state_10",
      "state_11",
      "state_12",
      "state_13",
      "state_14",
      "state_15",
      "state_16",
      "state_17",
      "state_18",
      "state_19",
      "state_20",
      "state_21",
      "state_22",
      "state_23",
      "state_24",
      "state_25",
      "state_26"
    ],
    "sourcePath": "references/Cute_Fantasy_ShroomLands/Shroomlings/Green_Shroomling.png",
    "companions": []
  },
  {
    "id": "enemy_cf_shroomling_purple",
    "label": "Purple Shroomling",
    "asset": "enemy_cf_shroomling_purple",
    "kind": "enemy",
    "family": "Shroomlands",
    "size": [
      16,
      16
    ],
    "animations": [
      "state_01",
      "state_02",
      "state_03",
      "state_04",
      "state_05",
      "state_06",
      "state_07",
      "state_08",
      "state_09",
      "state_10",
      "state_11",
      "state_12",
      "state_13",
      "state_14",
      "state_15",
      "state_16",
      "state_17",
      "state_18",
      "state_19",
      "state_20",
      "state_21",
      "state_22",
      "state_23",
      "state_24",
      "state_25",
      "state_26"
    ],
    "sourcePath": "references/Cute_Fantasy_ShroomLands/Shroomlings/Purple_Shroomling.png",
    "companions": []
  },
  {
    "id": "enemy_cf_snail_small_01",
    "label": "Small Snail 1",
    "asset": "enemy_cf_snail_small_01",
    "kind": "enemy",
    "family": "Shroomlands",
    "size": [
      16,
      16
    ],
    "animations": [
      "idle"
    ],
    "sourcePath": "references/Cute_Fantasy_ShroomLands/Snails/Snail_Small_1.png",
    "companions": []
  },
  {
    "id": "enemy_cf_snail_small_02",
    "label": "Small Snail 2",
    "asset": "enemy_cf_snail_small_02",
    "kind": "enemy",
    "family": "Shroomlands",
    "size": [
      16,
      16
    ],
    "animations": [
      "idle"
    ],
    "sourcePath": "references/Cute_Fantasy_ShroomLands/Snails/Snail_Small_2.png",
    "companions": []
  },
  {
    "id": "enemy_cf_snail_small_03",
    "label": "Small Snail 3",
    "asset": "enemy_cf_snail_small_03",
    "kind": "enemy",
    "family": "Shroomlands",
    "size": [
      16,
      16
    ],
    "animations": [
      "idle"
    ],
    "sourcePath": "references/Cute_Fantasy_ShroomLands/Snails/Snail_Small_3.png",
    "companions": []
  },
  {
    "id": "enemy_cf_snail_small_04",
    "label": "Small Snail 4",
    "asset": "enemy_cf_snail_small_04",
    "kind": "enemy",
    "family": "Shroomlands",
    "size": [
      16,
      16
    ],
    "animations": [
      "idle"
    ],
    "sourcePath": "references/Cute_Fantasy_ShroomLands/Snails/Snail_Small_4.png",
    "companions": []
  },
  {
    "id": "wildlife_cf_snail_01",
    "label": "Snail 1",
    "asset": "wildlife_cf_snail_01",
    "kind": "enemy",
    "family": "Shroomlands",
    "size": [
      32,
      32
    ],
    "animations": [
      "idle_side",
      "idle_down",
      "idle_up",
      "walk_side",
      "walk_down",
      "walk_up"
    ],
    "sourcePath": "references/Cute_Fantasy_ShroomLands/Snails/Snail_1.png",
    "companions": []
  },
  {
    "id": "wildlife_cf_snail_02",
    "label": "Snail 2",
    "asset": "wildlife_cf_snail_02",
    "kind": "enemy",
    "family": "Shroomlands",
    "size": [
      32,
      32
    ],
    "animations": [
      "idle_side",
      "idle_down",
      "idle_up",
      "walk_side",
      "walk_down",
      "walk_up"
    ],
    "sourcePath": "references/Cute_Fantasy_ShroomLands/Snails/Snail_2.png",
    "companions": []
  },
  {
    "id": "wildlife_cf_snail_03",
    "label": "Snail 3",
    "asset": "wildlife_cf_snail_03",
    "kind": "enemy",
    "family": "Shroomlands",
    "size": [
      32,
      32
    ],
    "animations": [
      "idle_side",
      "idle_down",
      "idle_up",
      "walk_side",
      "walk_down",
      "walk_up"
    ],
    "sourcePath": "references/Cute_Fantasy_ShroomLands/Snails/Snail_3.png",
    "companions": []
  },
  {
    "id": "wildlife_cf_snail_04",
    "label": "Snail 4",
    "asset": "wildlife_cf_snail_04",
    "kind": "enemy",
    "family": "Shroomlands",
    "size": [
      32,
      32
    ],
    "animations": [
      "idle_side",
      "idle_down",
      "idle_up",
      "walk_side",
      "walk_down",
      "walk_up"
    ],
    "sourcePath": "references/Cute_Fantasy_ShroomLands/Snails/Snail_4.png",
    "companions": []
  },
  {
    "id": "enemy_cf_shroomling_yellow",
    "label": "Yellow Shroomling",
    "asset": "enemy_cf_shroomling_yellow",
    "kind": "enemy",
    "family": "Shroomlands",
    "size": [
      16,
      16
    ],
    "animations": [
      "state_01",
      "state_02",
      "state_03",
      "state_04",
      "state_05",
      "state_06",
      "state_07",
      "state_08",
      "state_09",
      "state_10",
      "state_11",
      "state_12",
      "state_13",
      "state_14",
      "state_15",
      "state_16",
      "state_17",
      "state_18",
      "state_19",
      "state_20",
      "state_21",
      "state_22",
      "state_23",
      "state_24",
      "state_25",
      "state_26"
    ],
    "sourcePath": "references/Cute_Fantasy_ShroomLands/Shroomlings/Yellow_Shroomling.png",
    "companions": []
  },
  {
    "id": "enemy_cf_skeleton",
    "label": "Skeleton",
    "asset": "enemy_cf_skeleton",
    "kind": "enemy",
    "family": "Skeletons",
    "size": [
      32,
      32
    ],
    "animations": [
      "idle_down",
      "idle_right",
      "idle_up",
      "walk_down",
      "walk_right",
      "walk_up",
      "defeat",
      "hurt_down",
      "hurt_right",
      "hurt_up"
    ],
    "sourcePath": "references/Cute_Fantasy/Enemies/Skeleton/Skeleton.png",
    "companions": []
  },
  {
    "id": "enemy_cf_skeleton_bowman",
    "label": "Skeleton Bowman",
    "asset": "enemy_cf_skeleton_bowman",
    "kind": "enemy",
    "family": "Skeletons",
    "size": [
      32,
      32
    ],
    "animations": [
      "idle_down",
      "idle_right",
      "idle_up",
      "walk_down",
      "walk_right",
      "walk_up",
      "defeat",
      "attack_down",
      "attack_right",
      "attack_up",
      "hurt_down",
      "hurt_right",
      "hurt_up"
    ],
    "sourcePath": "references/Cute_Fantasy/Enemies/Skeleton/Skeleton_Bowman/Merged/Skeleton_Bowman.png",
    "companions": [
      "weapon_cf_skeleton_bow",
      "projectile_cf_crossbow_bolt"
    ]
  },
  {
    "id": "enemy_cf_skeleton_mage",
    "label": "Skeleton Mage",
    "asset": "enemy_cf_skeleton_mage",
    "kind": "enemy",
    "family": "Skeletons",
    "size": [
      32,
      32
    ],
    "animations": [
      "idle_down",
      "idle_right",
      "idle_up",
      "walk_down",
      "walk_right",
      "walk_up",
      "defeat",
      "cast_down",
      "cast_right",
      "cast_up",
      "hurt_down",
      "hurt_right",
      "hurt_up"
    ],
    "sourcePath": "references/Cute_Fantasy/Enemies/Skeleton/Skeleton_Mage.png",
    "companions": [
      "projectile_cf_skeleton_mage"
    ]
  },
  {
    "id": "enemy_cf_skeleton_swordman",
    "label": "Skeleton Swordman",
    "asset": "enemy_cf_skeleton_swordman",
    "kind": "enemy",
    "family": "Skeletons",
    "size": [
      32,
      32
    ],
    "animations": [
      "idle_down",
      "idle_right",
      "idle_up",
      "walk_down",
      "walk_right",
      "walk_up",
      "defeat",
      "attack_down",
      "attack_right",
      "attack_up",
      "special_down",
      "special_right",
      "special_up",
      "hurt_down",
      "hurt_right",
      "hurt_up"
    ],
    "sourcePath": "references/Cute_Fantasy/Enemies/Skeleton/Skeleton_Swordman.png",
    "companions": []
  },
  {
    "id": "enemy_cf_slime_big_blue",
    "label": "Big Blue Slime",
    "asset": "enemy_cf_slime_big_blue",
    "kind": "enemy",
    "family": "Slimes",
    "size": [
      64,
      64
    ],
    "animations": [
      "idle",
      "move",
      "hurt",
      "defeat"
    ],
    "sourcePath": "references/Cute_Fantasy/Enemies/Slime/Slime_Big/Slime_Big_Blue.png",
    "companions": []
  },
  {
    "id": "enemy_cf_slime_big_green",
    "label": "Big Green Slime",
    "asset": "enemy_cf_slime_big_green",
    "kind": "enemy",
    "family": "Slimes",
    "size": [
      64,
      64
    ],
    "animations": [
      "idle",
      "move",
      "hurt",
      "defeat"
    ],
    "sourcePath": "references/Cute_Fantasy/Enemies/Slime/Slime_Big/Slime_Big_Green.png",
    "companions": []
  },
  {
    "id": "enemy_cf_slime_big_pink",
    "label": "Big Pink Slime",
    "asset": "enemy_cf_slime_big_pink",
    "kind": "enemy",
    "family": "Slimes",
    "size": [
      64,
      64
    ],
    "animations": [
      "idle",
      "move",
      "hurt",
      "defeat"
    ],
    "sourcePath": "references/Cute_Fantasy/Enemies/Slime/Slime_Big/Slime_Big_Pink.png",
    "companions": []
  },
  {
    "id": "enemy_cf_slime_big_red",
    "label": "Big Red Slime",
    "asset": "enemy_cf_slime_big_red",
    "kind": "enemy",
    "family": "Slimes",
    "size": [
      64,
      64
    ],
    "animations": [
      "idle",
      "move",
      "hurt",
      "defeat"
    ],
    "sourcePath": "references/Cute_Fantasy/Enemies/Slime/Slime_Big/Slime_Big_Red.png",
    "companions": []
  },
  {
    "id": "enemy_cf_slime_big_yellow",
    "label": "Big Yellow Slime",
    "asset": "enemy_cf_slime_big_yellow",
    "kind": "enemy",
    "family": "Slimes",
    "size": [
      64,
      64
    ],
    "animations": [
      "idle",
      "move",
      "hurt",
      "defeat"
    ],
    "sourcePath": "references/Cute_Fantasy/Enemies/Slime/Slime_Big/Slime_Big_Yellow.png",
    "companions": []
  },
  {
    "id": "enemy_cf_slime_medium_blue",
    "label": "Medium Blue Slime",
    "asset": "enemy_cf_slime_medium_blue",
    "kind": "enemy",
    "family": "Slimes",
    "size": [
      32,
      32
    ],
    "animations": [
      "idle",
      "move",
      "hurt",
      "defeat"
    ],
    "sourcePath": "references/Cute_Fantasy/Enemies/Slime/Slime_Medium/Slime_Medium_Blue.png",
    "companions": []
  },
  {
    "id": "enemy_cf_slime_medium_green",
    "label": "Medium Green Slime",
    "asset": "enemy_cf_slime_medium_green",
    "kind": "enemy",
    "family": "Slimes",
    "size": [
      32,
      32
    ],
    "animations": [
      "idle",
      "move",
      "hurt",
      "defeat"
    ],
    "sourcePath": "references/Cute_Fantasy/Enemies/Slime/Slime_Medium/Slime_Medium_Green.png",
    "companions": []
  },
  {
    "id": "enemy_cf_slime_medium_pink",
    "label": "Medium Pink Slime",
    "asset": "enemy_cf_slime_medium_pink",
    "kind": "enemy",
    "family": "Slimes",
    "size": [
      32,
      32
    ],
    "animations": [
      "idle",
      "move",
      "hurt",
      "defeat"
    ],
    "sourcePath": "references/Cute_Fantasy/Enemies/Slime/Slime_Medium/Slime_Medium_Pink.png",
    "companions": []
  },
  {
    "id": "enemy_cf_slime_medium_red",
    "label": "Medium Red Slime",
    "asset": "enemy_cf_slime_medium_red",
    "kind": "enemy",
    "family": "Slimes",
    "size": [
      32,
      32
    ],
    "animations": [
      "idle",
      "move",
      "hurt",
      "defeat"
    ],
    "sourcePath": "references/Cute_Fantasy/Enemies/Slime/Slime_Medium/Slime_Medium_Red.png",
    "companions": []
  },
  {
    "id": "enemy_cf_slime_medium_yellow",
    "label": "Medium Yellow Slime",
    "asset": "enemy_cf_slime_medium_yellow",
    "kind": "enemy",
    "family": "Slimes",
    "size": [
      32,
      32
    ],
    "animations": [
      "idle",
      "move",
      "hurt",
      "defeat"
    ],
    "sourcePath": "references/Cute_Fantasy/Enemies/Slime/Slime_Medium/Slime_Medium_Yellow.png",
    "companions": []
  },
  {
    "id": "enemy_cf_slime_small_blue",
    "label": "Small Blue Slime",
    "asset": "enemy_cf_slime_small_blue",
    "kind": "enemy",
    "family": "Slimes",
    "size": [
      16,
      16
    ],
    "animations": [
      "idle",
      "move",
      "hurt",
      "defeat"
    ],
    "sourcePath": "references/Cute_Fantasy/Enemies/Slime/Slime_Small/Slime_Small_Blue.png",
    "companions": []
  },
  {
    "id": "enemy_cf_slime_small_green",
    "label": "Small Green Slime",
    "asset": "enemy_cf_slime_small_green",
    "kind": "enemy",
    "family": "Slimes",
    "size": [
      16,
      16
    ],
    "animations": [
      "idle",
      "move",
      "hurt",
      "defeat"
    ],
    "sourcePath": "references/Cute_Fantasy/Enemies/Slime/Slime_Small/Slime_Small_Green.png",
    "companions": []
  },
  {
    "id": "enemy_cf_slime_small_pink",
    "label": "Small Pink Slime",
    "asset": "enemy_cf_slime_small_pink",
    "kind": "enemy",
    "family": "Slimes",
    "size": [
      16,
      16
    ],
    "animations": [
      "idle",
      "move",
      "hurt",
      "defeat"
    ],
    "sourcePath": "references/Cute_Fantasy/Enemies/Slime/Slime_Small/Slime_Small_Pink.png",
    "companions": []
  },
  {
    "id": "enemy_cf_slime_small_red",
    "label": "Small Red Slime",
    "asset": "enemy_cf_slime_small_red",
    "kind": "enemy",
    "family": "Slimes",
    "size": [
      16,
      16
    ],
    "animations": [
      "idle",
      "move",
      "hurt",
      "defeat"
    ],
    "sourcePath": "references/Cute_Fantasy/Enemies/Slime/Slime_Small/Slime_Small_Red.png",
    "companions": []
  },
  {
    "id": "enemy_cf_slime_small_yellow",
    "label": "Small Yellow Slime",
    "asset": "enemy_cf_slime_small_yellow",
    "kind": "enemy",
    "family": "Slimes",
    "size": [
      16,
      16
    ],
    "animations": [
      "idle",
      "move",
      "hurt",
      "defeat"
    ],
    "sourcePath": "references/Cute_Fantasy/Enemies/Slime/Slime_Small/Slime_Small_Yellow.png",
    "companions": []
  },
  {
    "id": "enemy_cf_cowling_01",
    "label": "Cowling 1",
    "asset": "enemy_cf_cowling_01",
    "kind": "enemy",
    "family": "Volcano",
    "size": [
      48,
      48
    ],
    "animations": [
      "idle_down",
      "idle_right",
      "idle_up",
      "walk_down",
      "walk_right",
      "walk_up",
      "defeat",
      "attack_down",
      "attack_right",
      "attack_up",
      "hurt_down",
      "hurt_right",
      "hurt_up"
    ],
    "sourcePath": "references/Cute_Fantasy_Volcano/Enemies/Cowling_1.png",
    "companions": []
  },
  {
    "id": "enemy_cf_cowling_02",
    "label": "Cowling 2",
    "asset": "enemy_cf_cowling_02",
    "kind": "enemy",
    "family": "Volcano",
    "size": [
      48,
      48
    ],
    "animations": [
      "idle_down",
      "idle_right",
      "idle_up",
      "walk_down",
      "walk_right",
      "walk_up",
      "defeat",
      "attack_down",
      "attack_right",
      "attack_up",
      "hurt_down",
      "hurt_right",
      "hurt_up"
    ],
    "sourcePath": "references/Cute_Fantasy_Volcano/Enemies/Cowling_2.png",
    "companions": []
  },
  {
    "id": "enemy_cf_cowling_mage_01",
    "label": "Cowling Mage 1",
    "asset": "enemy_cf_cowling_mage_01",
    "kind": "enemy",
    "family": "Volcano",
    "size": [
      48,
      48
    ],
    "animations": [
      "idle_down",
      "idle_right",
      "idle_up",
      "walk_down",
      "walk_right",
      "walk_up",
      "defeat",
      "cast_down",
      "cast_right",
      "cast_up",
      "hurt_down",
      "hurt_right",
      "hurt_up"
    ],
    "sourcePath": "references/Cute_Fantasy_Volcano/Enemies/Cowling_Mage_1.png",
    "companions": []
  },
  {
    "id": "enemy_cf_cowling_mage_02",
    "label": "Cowling Mage 2",
    "asset": "enemy_cf_cowling_mage_02",
    "kind": "enemy",
    "family": "Volcano",
    "size": [
      48,
      48
    ],
    "animations": [
      "idle_down",
      "idle_right",
      "idle_up",
      "walk_down",
      "walk_right",
      "walk_up",
      "defeat",
      "cast_down",
      "cast_right",
      "cast_up",
      "hurt_down",
      "hurt_right",
      "hurt_up"
    ],
    "sourcePath": "references/Cute_Fantasy_Volcano/Enemies/Cowling_Mage_2.png",
    "companions": []
  },
  {
    "id": "enemy_cf_flying_skull",
    "label": "Flying Skull",
    "asset": "enemy_cf_flying_skull",
    "kind": "enemy",
    "family": "Volcano",
    "size": [
      32,
      32
    ],
    "animations": [
      "idle",
      "move",
      "attack",
      "defeat"
    ],
    "sourcePath": "references/Cute_Fantasy_Volcano/Enemies/Flying_Skull.png",
    "companions": []
  },
  {
    "id": "effect_cf_bow_stages",
    "label": "Bow Charge Stages",
    "asset": "effect_cf_bow_stages",
    "kind": "effect",
    "family": "Combat Equipment",
    "size": [
      16,
      16
    ],
    "animations": [
      "charge"
    ],
    "sourcePath": "references/Cute_Fantasy/Other/Bow_Stages.png",
    "companions": []
  },
  {
    "id": "effect_cf_mounted_crossbow",
    "label": "Mounted Crossbow",
    "asset": "effect_cf_mounted_crossbow",
    "kind": "effect",
    "family": "Combat Equipment",
    "size": [
      16,
      16
    ],
    "animations": [
      "fire"
    ],
    "sourcePath": "references/Cute_Fantasy_Dungeons/Objects/Mounted_Crossbow_anim.png",
    "companions": []
  },
  {
    "id": "weapon_cf_skeleton_bow",
    "label": "Skeleton Bow Layers",
    "asset": "weapon_cf_skeleton_bow",
    "kind": "effect",
    "family": "Combat Equipment",
    "size": [
      32,
      32
    ],
    "animations": [
      "state_01",
      "state_02",
      "state_03",
      "state_04",
      "state_05",
      "state_06",
      "state_07",
      "state_08",
      "state_09"
    ],
    "sourcePath": "references/Cute_Fantasy/Enemies/Skeleton/Skeleton_Bowman/Separated/Skeleton_Bowman_Bow.png",
    "companions": []
  },
  {
    "id": "projectile_cf_crossbow_bolt",
    "label": "Crossbow Bolt",
    "asset": "projectile_cf_crossbow_bolt",
    "kind": "effect",
    "family": "Projectiles",
    "size": [
      16,
      16
    ],
    "animations": [
      "base"
    ],
    "sourcePath": "references/Cute_Fantasy_Dungeons/Objects/Crossbow_Bolt.png",
    "companions": []
  },
  {
    "id": "projectile_cf_skeleton_mage",
    "label": "Skeleton Mage Projectile",
    "asset": "projectile_cf_skeleton_mage",
    "kind": "effect",
    "family": "Projectiles",
    "size": [
      16,
      16
    ],
    "animations": [
      "travel"
    ],
    "sourcePath": "references/Cute_Fantasy/Other/Skeleton_Mage_Projectile.png",
    "companions": []
  },
  {
    "id": "effect_cf_bombschroom_gas",
    "label": "Toxic Gas Cloud",
    "asset": "effect_cf_bombschroom_gas",
    "kind": "effect",
    "family": "VFX",
    "size": [
      16,
      16
    ],
    "animations": [
      "state_01",
      "state_02"
    ],
    "sourcePath": "references/Cute_Fantasy/Enemies/Bombschroom/Toxic_Gas_Cloud_VFX.png",
    "companions": []
  },
  {
    "id": "effect_cf_witch_bat",
    "label": "Witch Bat",
    "asset": "effect_cf_witch_bat",
    "kind": "effect",
    "family": "Witch Companions",
    "size": [
      16,
      16
    ],
    "animations": [
      "fly"
    ],
    "sourcePath": "references/Cute_Fantasy_Halloween/Witch/Bat.png",
    "companions": []
  },
  {
    "id": "effect_cf_witch_broom",
    "label": "Witch Broom",
    "asset": "effect_cf_witch_broom",
    "kind": "effect",
    "family": "Witch Companions",
    "size": [
      32,
      32
    ],
    "animations": [
      "state_01",
      "state_02"
    ],
    "sourcePath": "references/Cute_Fantasy_Halloween/Witch/Broom.png",
    "companions": []
  },
  {
    "id": "effect_cf_witch_cauldron",
    "label": "Witch Cauldron",
    "asset": "effect_cf_witch_cauldron",
    "kind": "effect",
    "family": "Witch Companions",
    "size": [
      32,
      32
    ],
    "animations": [
      "bubble"
    ],
    "sourcePath": "references/Cute_Fantasy_Halloween/Witch/Witch_Cauldron_Anim.png",
    "companions": []
  }
] as const satisfies readonly CuteFantasyActorCatalogEntry[];
