// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  reason: __t.string(),
  clientMutationId: __t.string(),
  dryRun: __t.bool(),
  expectedWorldVersion: __t.string(),
  previewFingerprint: __t.option(__t.string()),
  body: __t.string(),
};
