// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const params = {
  spaceId: __t.string(),
  x0: __t.i32(),
  y0: __t.i32(),
  x1: __t.i32(),
  y1: __t.i32(),
  cursor: __t.option(__t.string()),
  limit: __t.u32(),
  kinds: __t.array(__t.string()),
  text: __t.string(),
};
export const returnType = __t.string()