// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  packId: __t.string().primaryKey().name("pack_id"),
  revision: __t.u64(),
  contentHash: __t.string().name("content_hash"),
  engineVersion: __t.u32().name("engine_version"),
  definitionCount: __t.u32().name("definition_count"),
  updatedBy: __t.identity().name("updated_by"),
  updatedAt: __t.timestamp().name("updated_at"),
  clientMutationId: __t.string().name("client_mutation_id"),
});
