// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  npcId: __t.u64().primaryKey().name("npc_id"),
  targetIdentity: __t.identity().name("target_identity"),
  sequence: __t.u64(),
  pattern: __t.string(),
  startedTick: __t.u64().name("started_tick"),
  lastProcessedTick: __t.u64().name("last_processed_tick"),
  tellTicks: __t.u16().name("tell_ticks"),
  activeTicks: __t.u16().name("active_ticks"),
  recoveryTicks: __t.u16().name("recovery_ticks"),
  originX: __t.i32().name("origin_x"),
  originY: __t.i32().name("origin_y"),
  targetX: __t.i32().name("target_x"),
  targetY: __t.i32().name("target_y"),
  elevation: __t.i16(),
  damageCenti: __t.u32().name("damage_centi"),
  hitIdentities: __t.array(__t.identity()).name("hit_identities"),
  spaceId: __t.u16().name("space_id"),
  chunkX: __t.i16().name("chunk_x"),
  chunkY: __t.i16().name("chunk_y"),
});
