// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.8.2 (commit 524b4487d949b61a07d4f39c862d1290259dfd20).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import AbandonQuestReducer from "./abandon_quest_reducer";
import AbandonRogueRunReducer from "./abandon_rogue_run_reducer";
import AcceptPartyInviteReducer from "./accept_party_invite_reducer";
import AcceptTradeRequestReducer from "./accept_trade_request_reducer";
import AcknowledgeInventoryProtocolReducer from "./acknowledge_inventory_protocol_reducer";
import ActivateOutdoorEncounterReducer from "./activate_outdoor_encounter_reducer";
import AdminBackfillLegacyChestsReducer from "./admin_backfill_legacy_chests_reducer";
import AdminClearCursorReducer from "./admin_clear_cursor_reducer";
import AdminDespawnEntityReducer from "./admin_despawn_entity_reducer";
import AdminDrainLegacyChestsReducer from "./admin_drain_legacy_chests_reducer";
import AdminDrainOverflowReducer from "./admin_drain_overflow_reducer";
import AdminGiveItemsReducer from "./admin_give_items_reducer";
import AdminGlobalNoticeReducer from "./admin_global_notice_reducer";
import AdminGrantContentEditorReducer from "./admin_grant_content_editor_reducer";
import AdminGrantSkillPointsReducer from "./admin_grant_skill_points_reducer";
import AdminGrantSupportReducer from "./admin_grant_support_reducer";
import AdminKickReducer from "./admin_kick_reducer";
import AdminMoveEntityReducer from "./admin_move_entity_reducer";
import AdminMoveHomesteadReducer from "./admin_move_homestead_reducer";
import AdminMoveHomesteadExactReducer from "./admin_move_homestead_exact_reducer";
import AdminNotifyReducer from "./admin_notify_reducer";
import AdminPlaytestApplyEffectReducer from "./admin_playtest_apply_effect_reducer";
import AdminPlaytestGrantUpgradeReducer from "./admin_playtest_grant_upgrade_reducer";
import AdminPlaytestSpawnReducer from "./admin_playtest_spawn_reducer";
import AdminRelocateNpcReducer from "./admin_relocate_npc_reducer";
import AdminRemoveItemsReducer from "./admin_remove_items_reducer";
import AdminRepairEntityReducer from "./admin_repair_entity_reducer";
import AdminRepairPortalPairReducer from "./admin_repair_portal_pair_reducer";
import AdminReplaceEntityReducer from "./admin_replace_entity_reducer";
import AdminResetQuestsReducer from "./admin_reset_quests_reducer";
import AdminResetSkillTreeReducer from "./admin_reset_skill_tree_reducer";
import AdminRespawnReducer from "./admin_respawn_reducer";
import AdminRespawnResourcesReducer from "./admin_respawn_resources_reducer";
import AdminRestoreMapReducer from "./admin_restore_map_reducer";
import AdminRestoreMissingContainerReducer from "./admin_restore_missing_container_reducer";
import AdminRevokeContentEditorReducer from "./admin_revoke_content_editor_reducer";
import AdminRevokeSupportReducer from "./admin_revoke_support_reducer";
import AdminRunWorldRepairReducer from "./admin_run_world_repair_reducer";
import AdminSetChestMigrationPhaseReducer from "./admin_set_chest_migration_phase_reducer";
import AdminSetContainerSlotReducer from "./admin_set_container_slot_reducer";
import AdminSetDisplayNameReducer from "./admin_set_display_name_reducer";
import AdminSetEntityStateReducer from "./admin_set_entity_state_reducer";
import AdminSetMotdReducer from "./admin_set_motd_reducer";
import AdminSetQuestStateReducer from "./admin_set_quest_state_reducer";
import AdminSetSlotReducer from "./admin_set_slot_reducer";
import AdminSetSpaceFlagsReducer from "./admin_set_space_flags_reducer";
import AdminSetSpawnReducer from "./admin_set_spawn_reducer";
import AdminSetStatsReducer from "./admin_set_stats_reducer";
import AdminSetTimeReducer from "./admin_set_time_reducer";
import AdminSetVitalsReducer from "./admin_set_vitals_reducer";
import AdminSetWalletReducer from "./admin_set_wallet_reducer";
import AdminSetWeatherReducer from "./admin_set_weather_reducer";
import AdminSetWindReducer from "./admin_set_wind_reducer";
import AdminSpawnEntityReducer from "./admin_spawn_entity_reducer";
import AdminTeleportPlayerReducer from "./admin_teleport_player_reducer";
import AdminUndoPlayerReducer from "./admin_undo_player_reducer";
import AdminUnstickReducer from "./admin_unstick_reducer";
import AdminVerifyLegacyChestsReducer from "./admin_verify_legacy_chests_reducer";
import ApproveMemberReducer from "./approve_member_reducer";
import BuyMerchantCartReducer from "./buy_merchant_cart_reducer";
import BuyMerchantItemReducer from "./buy_merchant_item_reducer";
import CancelTradeReducer from "./cancel_trade_reducer";
import ChooseDialogueOptionReducer from "./choose_dialogue_option_reducer";
import ChooseRogueDoorReducer from "./choose_rogue_door_reducer";
import ChooseRogueRewardReducer from "./choose_rogue_reward_reducer";
import ClaimOutdoorRewardReducer from "./claim_outdoor_reward_reducer";
import ClearContentDraftReducer from "./clear_content_draft_reducer";
import CloseChestReducer from "./close_chest_reducer";
import CloseCraftingReducer from "./close_crafting_reducer";
import CloseHearthStashReducer from "./close_hearth_stash_reducer";
import CloseNpcDialogueReducer from "./close_npc_dialogue_reducer";
import ClosePlaceableReducer from "./close_placeable_reducer";
import CombatDefenseReducer from "./combat_defense_reducer";
import CraftInventoryRecipeReducer from "./craft_inventory_recipe_reducer";
import CreateChatChannelReducer from "./create_chat_channel_reducer";
import CreatePartyReducer from "./create_party_reducer";
import DeclineTradeReducer from "./decline_trade_reducer";
import DistributeChestItemReducer from "./distribute_chest_item_reducer";
import DistributeInventoryItemReducer from "./distribute_inventory_item_reducer";
import DropInventoryCursorReducer from "./drop_inventory_cursor_reducer";
import DropSelectedReducer from "./drop_selected_reducer";
import EditResidenceArchitectureReducer from "./edit_residence_architecture_reducer";
import FillCraftingRecipeReducer from "./fill_crafting_recipe_reducer";
import FulfillVillageOrderReducer from "./fulfill_village_order_reducer";
import GatherWorldResourceReducer from "./gather_world_resource_reducer";
import GrantContentEditorReducer from "./grant_content_editor_reducer";
import HarvestCropTileReducer from "./harvest_crop_tile_reducer";
import HeartbeatReducer from "./heartbeat_reducer";
import InstallHearthGatheringSitesReducer from "./install_hearth_gathering_sites_reducer";
import InteractEntityReducer from "./interact_entity_reducer";
import InteractHorseReducer from "./interact_horse_reducer";
import InteractNpcReducer from "./interact_npc_reducer";
import InventoryCursorClickReducer from "./inventory_cursor_click_reducer";
import InventoryCursorPickupAllReducer from "./inventory_cursor_pickup_all_reducer";
import InventoryCursorQuickCraftReducer from "./inventory_cursor_quick_craft_reducer";
import InventoryCursorSwapHotbarReducer from "./inventory_cursor_swap_hotbar_reducer";
import InviteChatMemberReducer from "./invite_chat_member_reducer";
import InviteToPartyReducer from "./invite_to_party_reducer";
import JoinChatChannelReducer from "./join_chat_channel_reducer";
import JumpHorseReducer from "./jump_horse_reducer";
import LeaveChatChannelReducer from "./leave_chat_channel_reducer";
import LeavePartyReducer from "./leave_party_reducer";
import MoveChestItemReducer from "./move_chest_item_reducer";
import MoveHearthFurnitureReducer from "./move_hearth_furniture_reducer";
import MoveInventoryItemReducer from "./move_inventory_item_reducer";
import MovePlaceableItemReducer from "./move_placeable_item_reducer";
import OpenHearthStashReducer from "./open_hearth_stash_reducer";
import OpenHearthSupplyCacheReducer from "./open_hearth_supply_cache_reducer";
import PickupEmbeddedArrowReducer from "./pickup_embedded_arrow_reducer";
import PickupHearthFurnitureReducer from "./pickup_hearth_furniture_reducer";
import PickupQuestWorldItemReducer from "./pickup_quest_world_item_reducer";
import PickupWorldItemReducer from "./pickup_world_item_reducer";
import PlaceHearthFurnitureReducer from "./place_hearth_furniture_reducer";
import PlaceHomesteadBuildableReducer from "./place_homestead_buildable_reducer";
import PrioritizeEquipmentSkillReducer from "./prioritize_equipment_skill_reducer";
import PublishContentChangeSetReducer from "./publish_content_change_set_reducer";
import PublishLiveMapDocumentReducer from "./publish_live_map_document_reducer";
import PurchaseHomesteadUpgradeReducer from "./purchase_homestead_upgrade_reducer";
import PurchaseResidenceExpansionReducer from "./purchase_residence_expansion_reducer";
import PurchaseSkillNodeReducer from "./purchase_skill_node_reducer";
import QuickMoveAllMenuItemsReducer from "./quick_move_all_menu_items_reducer";
import QuickMoveMenuItemReducer from "./quick_move_menu_item_reducer";
import RemoveHomesteadBuildableReducer from "./remove_homestead_buildable_reducer";
import RemoveHomesteadMemberReducer from "./remove_homestead_member_reducer";
import RemovePartyMemberReducer from "./remove_party_member_reducer";
import RemoveTradeOfferItemReducer from "./remove_trade_offer_item_reducer";
import ReportClientErrorReducer from "./report_client_error_reducer";
import RequestTradeReducer from "./request_trade_reducer";
import ResetSkillTreeReducer from "./reset_skill_tree_reducer";
import RestoreContentRevisionReducer from "./restore_content_revision_reducer";
import RestoreLiveMapRevisionReducer from "./restore_live_map_revision_reducer";
import ReturnInventoryCursorReducer from "./return_inventory_cursor_reducer";
import RevokeContentEditorReducer from "./revoke_content_editor_reducer";
import RevokeMemberReducer from "./revoke_member_reducer";
import SaveContentDraftReducer from "./save_content_draft_reducer";
import SelectHotbarReducer from "./select_hotbar_reducer";
import SellMerchantCartReducer from "./sell_merchant_cart_reducer";
import SellMerchantItemReducer from "./sell_merchant_item_reducer";
import SendChatMessageReducer from "./send_chat_message_reducer";
import SendWhisperReducer from "./send_whisper_reducer";
import SendWorldSpeechReducer from "./send_world_speech_reducer";
import SetAppearanceReducer from "./set_appearance_reducer";
import SetDisplayNameReducer from "./set_display_name_reducer";
import SetHomesteadMemberRoleReducer from "./set_homestead_member_role_reducer";
import SetInputReducer from "./set_input_reducer";
import SetMessageOfDayReducer from "./set_message_of_day_reducer";
import SetQuestPinnedReducer from "./set_quest_pinned_reducer";
import SetTradeAcceptedReducer from "./set_trade_accepted_reducer";
import SetTradeOfferBronzeReducer from "./set_trade_offer_bronze_reducer";
import SetTradeOfferItemReducer from "./set_trade_offer_item_reducer";
import SetWorldTimeReducer from "./set_world_time_reducer";
import SetWorldWeatherReducer from "./set_world_weather_reducer";
import SetWorldWindDirectionReducer from "./set_world_wind_direction_reducer";
import SitHearthFurnitureReducer from "./sit_hearth_furniture_reducer";
import SkipRogueRewardReducer from "./skip_rogue_reward_reducer";
import SortMenuContainerReducer from "./sort_menu_container_reducer";
import StandHearthFurnitureReducer from "./stand_hearth_furniture_reducer";
import StartRogueRunReducer from "./start_rogue_run_reducer";
import TendTreeReducer from "./tend_tree_reducer";
import ThrowMenuItemReducer from "./throw_menu_item_reducer";
import ToggleHomesteadGateReducer from "./toggle_homestead_gate_reducer";
import TravelHearthFerryReducer from "./travel_hearth_ferry_reducer";
import UnlockHearthLegendaryRecipeReducer from "./unlock_hearth_legendary_recipe_reducer";
import UsePortalReducer from "./use_portal_reducer";
import UseSelectedReducer from "./use_selected_reducer";

// Import all procedure arg schemas
import * as AdminAuditPageProcedure from "./admin_audit_page_procedure";
import * as AdminChestMigrationStatusProcedure from "./admin_chest_migration_status_procedure";
import * as AdminClientErrorsProcedure from "./admin_client_errors_procedure";
import * as AdminConnectionsPageProcedure from "./admin_connections_page_procedure";
import * as AdminContainerContentsProcedure from "./admin_container_contents_procedure";
import * as AdminEntitiesInAreaProcedure from "./admin_entities_in_area_procedure";
import * as AdminFindPlayersProcedure from "./admin_find_players_procedure";
import * as AdminHomesteadProcedure from "./admin_homestead_procedure";
import * as AdminMissingContainerRecoveryProcedure from "./admin_missing_container_recovery_procedure";
import * as AdminPlayerInventoryProcedure from "./admin_player_inventory_procedure";
import * as AdminPlayerMutationResultProcedure from "./admin_player_mutation_result_procedure";
import * as AdminPlayerSnapshotProcedure from "./admin_player_snapshot_procedure";
import * as AdminTelemetryProcedure from "./admin_telemetry_procedure";
import * as AdminValidateWorldProcedure from "./admin_validate_world_procedure";

// Import all table schema definitions
import ActiveFarmSkillNodesRow from "./active_farm_skill_nodes_table";
import ActiveFarmUpgradesRow from "./active_farm_upgrades_table";
import ActiveFishingCastsRow from "./active_fishing_casts_table";
import CellarExcavationRow from "./cellar_excavation_table";
import ContentDefinitionRow from "./content_definition_table";
import ContentHeadRow from "./content_head_table";
import EnemyAttackRow from "./enemy_attack_table";
import HomesteadRow from "./homestead_table";
import LiveMapDocumentRow from "./live_map_document_table";
import OnlinePlayerAppearancesRow from "./online_player_appearances_table";
import OnlinePlayerPublicRow from "./online_player_public_table";
import OutdoorEnemyProfileRow from "./outdoor_enemy_profile_table";
import OwnActiveChestRow from "./own_active_chest_table";
import OwnActiveDialogueRow from "./own_active_dialogue_table";
import OwnActiveHearthStashRow from "./own_active_hearth_stash_table";
import OwnActivePlaceableRow from "./own_active_placeable_table";
import OwnAdminMutationPreviewsRow from "./own_admin_mutation_previews_table";
import OwnAdminWorldValidationReportsRow from "./own_admin_world_validation_reports_table";
import OwnCharacterProfileRow from "./own_character_profile_table";
import OwnChatChannelsRow from "./own_chat_channels_table";
import OwnCombatStateRow from "./own_combat_state_table";
import OwnConnectionNoticesRow from "./own_connection_notices_table";
import OwnContentDraftRow from "./own_content_draft_table";
import OwnContentEditorGrantRow from "./own_content_editor_grant_table";
import OwnContentRevisionsRow from "./own_content_revisions_table";
import OwnCookingJobRow from "./own_cooking_job_table";
import OwnCurrentHomesteadRow from "./own_current_homestead_table";
import OwnEffectsRow from "./own_effects_table";
import OwnEquipmentPreferencesRow from "./own_equipment_preferences_table";
import OwnFishingCastRow from "./own_fishing_cast_table";
import OwnHearthStashSlotsRow from "./own_hearth_stash_slots_table";
import OwnHomesteadMembersRow from "./own_homestead_members_table";
import OwnHomesteadUpgradesRow from "./own_homestead_upgrades_table";
import OwnInventoryCursorRow from "./own_inventory_cursor_table";
import OwnInventoryOverflowRow from "./own_inventory_overflow_table";
import OwnInventorySlotsRow from "./own_inventory_slots_table";
import OwnKnownRecipesRow from "./own_known_recipes_table";
import OwnMembershipRow from "./own_membership_table";
import OwnOpenChestSlotsRow from "./own_open_chest_slots_table";
import OwnOpenPlaceableSlotsRow from "./own_open_placeable_slots_table";
import OwnOutdoorRewardsRow from "./own_outdoor_rewards_table";
import OwnPlacedPlaceableDamageRow from "./own_placed_placeable_damage_table";
import OwnPlacedPlaceableSlotsRow from "./own_placed_placeable_slots_table";
import OwnPlayerPredictionRow from "./own_player_prediction_table";
import OwnPlayerQuestBaselinesRow from "./own_player_quest_baselines_table";
import OwnPlayerQuestsRow from "./own_player_quests_table";
import OwnPlayerSkillNodesRow from "./own_player_skill_nodes_table";
import OwnPlayerSkillTracksRow from "./own_player_skill_tracks_table";
import OwnPlayerSpawnRow from "./own_player_spawn_table";
import OwnPlayerStatisticMilestonesRow from "./own_player_statistic_milestones_table";
import OwnPlayerStatisticsRow from "./own_player_statistics_table";
import OwnPlayerThoughtRow from "./own_player_thought_table";
import OwnQuestWorldItemsRow from "./own_quest_world_items_table";
import OwnRogueRewardOffersRow from "./own_rogue_reward_offers_table";
import OwnRogueRoomExitsRow from "./own_rogue_room_exits_table";
import OwnRogueRunRow from "./own_rogue_run_table";
import OwnRogueRunUpgradesRow from "./own_rogue_run_upgrades_table";
import OwnSessionChatNoticesRow from "./own_session_chat_notices_table";
import OwnStatsRow from "./own_stats_table";
import OwnSupportGrantRow from "./own_support_grant_table";
import OwnSurvivalRow from "./own_survival_table";
import OwnTradeOffersRow from "./own_trade_offers_table";
import OwnTradeSessionRow from "./own_trade_session_table";
import OwnVillageOrdersRow from "./own_village_orders_table";
import OwnWalletRow from "./own_wallet_table";
import PlayerAppearanceRow from "./player_appearance_table";
import PlayerJumpStateRow from "./player_jump_state_table";
import PlayerPartyRow from "./player_party_table";
import PlayerPartyMemberRow from "./player_party_member_table";
import PlayerPositionRow from "./player_position_table";
import PlayerPublicRow from "./player_public_table";
import RogueEnemyProfileRow from "./rogue_enemy_profile_table";
import RuntimeContentDefinitionsRow from "./runtime_content_definitions_table";
import SpaceAdminFlagRow from "./space_admin_flag_table";
import SpacePortalRow from "./space_portal_table";
import VisibleChatMessagesRow from "./visible_chat_messages_table";
import VisibleWorldSpeechRow from "./visible_world_speech_table";
import WorldCampfireStateRow from "./world_campfire_state_table";
import WorldChestRow from "./world_chest_table";
import WorldClockRow from "./world_clock_table";
import WorldCombatTargetRow from "./world_combat_target_table";
import WorldCropRow from "./world_crop_table";
import WorldEnvironmentRow from "./world_environment_table";
import WorldHiveRow from "./world_hive_table";
import WorldItemRow from "./world_item_table";
import WorldMerchantRow from "./world_merchant_table";
import WorldNpcRow from "./world_npc_table";
import WorldPlaceableRow from "./world_placeable_table";
import WorldProjectileRow from "./world_projectile_table";
import WorldResourceRow from "./world_resource_table";
import WorldSeedRow from "./world_seed_table";
import WorldSoilRow from "./world_soil_table";
import WorldSurfaceRow from "./world_surface_table";
import WorldTreeRow from "./world_tree_table";
import WorldWildlifeProfileRow from "./world_wildlife_profile_table";
import WorldWindRow from "./world_wind_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  cellarExcavation: __table({
    name: 'cellar_excavation',
    indexes: [
      { accessor: 'id', name: 'cellar_excavation_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'by_chunk', name: 'cellar_excavation_space_id_chunk_x_chunk_y_idx_btree', algorithm: 'btree', columns: [
        'spaceId',
        'chunkX',
        'chunkY',
      ] },
      { accessor: 'by_space', name: 'cellar_excavation_space_id_idx_btree', algorithm: 'btree', columns: [
        'spaceId',
      ] },
    ],
    constraints: [
      { name: 'cellar_excavation_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, CellarExcavationRow),
  contentDefinition: __table({
    name: 'content_definition',
    indexes: [
      { accessor: 'id', name: 'content_definition_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'by_kind', name: 'content_definition_kind_idx_btree', algorithm: 'btree', columns: [
        'kind',
      ] },
    ],
    constraints: [
      { name: 'content_definition_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ContentDefinitionRow),
  contentHead: __table({
    name: 'content_head',
    indexes: [
      { accessor: 'packId', name: 'content_head_pack_id_idx_btree', algorithm: 'btree', columns: [
        'packId',
      ] },
    ],
    constraints: [
      { name: 'content_head_pack_id_key', constraint: 'unique', columns: ['packId'] },
    ],
  }, ContentHeadRow),
  enemyAttack: __table({
    name: 'enemy_attack',
    indexes: [
      { accessor: 'npcId', name: 'enemy_attack_npc_id_idx_btree', algorithm: 'btree', columns: [
        'npcId',
      ] },
      { accessor: 'by_chunk', name: 'enemy_attack_space_id_chunk_x_chunk_y_idx_btree', algorithm: 'btree', columns: [
        'spaceId',
        'chunkX',
        'chunkY',
      ] },
      { accessor: 'by_target', name: 'enemy_attack_target_identity_idx_btree', algorithm: 'btree', columns: [
        'targetIdentity',
      ] },
    ],
    constraints: [
      { name: 'enemy_attack_npc_id_key', constraint: 'unique', columns: ['npcId'] },
    ],
  }, EnemyAttackRow),
  homestead: __table({
    name: 'homestead',
    indexes: [
      { accessor: 'by_overworld_location', name: 'homestead_overworld_tile_x_overworld_tile_y_idx_btree', algorithm: 'btree', columns: [
        'overworldTileX',
        'overworldTileY',
      ] },
      { accessor: 'by_owner', name: 'homestead_owner_idx_hash', algorithm: 'btree', columns: [
        'owner',
      ] },
      { accessor: 'by_residence_space', name: 'homestead_residence_space_id_idx_btree', algorithm: 'btree', columns: [
        'residenceSpaceId',
      ] },
      { accessor: 'spaceId', name: 'homestead_space_id_idx_btree', algorithm: 'btree', columns: [
        'spaceId',
      ] },
    ],
    constraints: [
      { name: 'homestead_space_id_key', constraint: 'unique', columns: ['spaceId'] },
    ],
  }, HomesteadRow),
  liveMapDocument: __table({
    name: 'live_map_document',
    indexes: [
      { accessor: 'mapId', name: 'live_map_document_map_id_idx_btree', algorithm: 'btree', columns: [
        'mapId',
      ] },
    ],
    constraints: [
      { name: 'live_map_document_map_id_key', constraint: 'unique', columns: ['mapId'] },
    ],
  }, LiveMapDocumentRow),
  outdoorEnemyProfile: __table({
    name: 'outdoor_enemy_profile',
    indexes: [
      { accessor: 'by_encounter', name: 'outdoor_enemy_profile_encounter_id_idx_btree', algorithm: 'btree', columns: [
        'encounterId',
      ] },
      { accessor: 'npcId', name: 'outdoor_enemy_profile_npc_id_idx_btree', algorithm: 'btree', columns: [
        'npcId',
      ] },
      { accessor: 'by_chunk', name: 'outdoor_enemy_profile_space_id_chunk_x_chunk_y_idx_btree', algorithm: 'btree', columns: [
        'spaceId',
        'chunkX',
        'chunkY',
      ] },
    ],
    constraints: [
      { name: 'outdoor_enemy_profile_npc_id_key', constraint: 'unique', columns: ['npcId'] },
    ],
  }, OutdoorEnemyProfileRow),
  playerAppearance: __table({
    name: 'player_appearance',
    indexes: [
      { accessor: 'identity', name: 'player_appearance_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'player_appearance_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, PlayerAppearanceRow),
  playerJumpState: __table({
    name: 'player_jump_state',
    indexes: [
      { accessor: 'identity', name: 'player_jump_state_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
      { accessor: 'by_chunk', name: 'player_jump_state_space_id_chunk_x_chunk_y_idx_btree', algorithm: 'btree', columns: [
        'spaceId',
        'chunkX',
        'chunkY',
      ] },
    ],
    constraints: [
      { name: 'player_jump_state_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, PlayerJumpStateRow),
  playerParty: __table({
    name: 'player_party',
    indexes: [
      { accessor: 'id', name: 'player_party_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'player_party_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PlayerPartyRow),
  playerPartyMember: __table({
    name: 'player_party_member',
    indexes: [
      { accessor: 'identity', name: 'player_party_member_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
      { accessor: 'by_party', name: 'player_party_member_party_id_idx_btree', algorithm: 'btree', columns: [
        'partyId',
      ] },
    ],
    constraints: [
      { name: 'player_party_member_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, PlayerPartyMemberRow),
  playerPosition: __table({
    name: 'player_position',
    indexes: [
      { accessor: 'identity', name: 'player_position_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
      { accessor: 'by_chunk', name: 'player_position_space_id_chunk_x_chunk_y_idx_btree', algorithm: 'btree', columns: [
        'spaceId',
        'chunkX',
        'chunkY',
      ] },
    ],
    constraints: [
      { name: 'player_position_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, PlayerPositionRow),
  playerPublic: __table({
    name: 'player_public',
    indexes: [
      { accessor: 'by_display_name', name: 'player_public_display_name_idx_btree', algorithm: 'btree', columns: [
        'displayName',
      ] },
      { accessor: 'identity', name: 'player_public_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
      { accessor: 'by_online', name: 'player_public_online_idx_btree', algorithm: 'btree', columns: [
        'online',
      ] },
    ],
    constraints: [
      { name: 'player_public_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, PlayerPublicRow),
  rogueEnemyProfile: __table({
    name: 'rogue_enemy_profile',
    indexes: [
      { accessor: 'npcId', name: 'rogue_enemy_profile_npc_id_idx_btree', algorithm: 'btree', columns: [
        'npcId',
      ] },
      { accessor: 'by_run', name: 'rogue_enemy_profile_run_id_idx_btree', algorithm: 'btree', columns: [
        'runId',
      ] },
      { accessor: 'by_chunk', name: 'rogue_enemy_profile_space_id_chunk_x_chunk_y_idx_btree', algorithm: 'btree', columns: [
        'spaceId',
        'chunkX',
        'chunkY',
      ] },
    ],
    constraints: [
      { name: 'rogue_enemy_profile_npc_id_key', constraint: 'unique', columns: ['npcId'] },
    ],
  }, RogueEnemyProfileRow),
  spaceAdminFlag: __table({
    name: 'space_admin_flag',
    indexes: [
      { accessor: 'spaceId', name: 'space_admin_flag_space_id_idx_btree', algorithm: 'btree', columns: [
        'spaceId',
      ] },
    ],
    constraints: [
      { name: 'space_admin_flag_space_id_key', constraint: 'unique', columns: ['spaceId'] },
    ],
  }, SpaceAdminFlagRow),
  spacePortal: __table({
    name: 'space_portal',
    indexes: [
      { accessor: 'by_from_space', name: 'space_portal_from_space_idx_btree', algorithm: 'btree', columns: [
        'fromSpace',
      ] },
      { accessor: 'id', name: 'space_portal_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'space_portal_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, SpacePortalRow),
  worldCampfireState: __table({
    name: 'world_campfire_state',
    indexes: [
      { accessor: 'id', name: 'world_campfire_state_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'by_location', name: 'world_campfire_state_space_id_tile_x_tile_y_idx_btree', algorithm: 'btree', columns: [
        'spaceId',
        'tileX',
        'tileY',
      ] },
    ],
    constraints: [
      { name: 'world_campfire_state_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, WorldCampfireStateRow),
  worldChest: __table({
    name: 'world_chest',
    indexes: [
      { accessor: 'by_carrier', name: 'world_chest_carried_by_idx_btree', algorithm: 'btree', columns: [
        'carriedBy',
      ] },
      { accessor: 'id', name: 'world_chest_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'by_migration_order', name: 'world_chest_id_space_id_idx_btree', algorithm: 'btree', columns: [
        'id',
        'spaceId',
      ] },
      { accessor: 'by_chunk', name: 'world_chest_space_id_chunk_x_chunk_y_idx_btree', algorithm: 'btree', columns: [
        'spaceId',
        'chunkX',
        'chunkY',
      ] },
    ],
    constraints: [
      { name: 'world_chest_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, WorldChestRow),
  worldClock: __table({
    name: 'world_clock',
    indexes: [
      { accessor: 'id', name: 'world_clock_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'world_clock_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, WorldClockRow),
  worldCombatTarget: __table({
    name: 'world_combat_target',
    indexes: [
      { accessor: 'by_carrier', name: 'world_combat_target_carried_by_idx_btree', algorithm: 'btree', columns: [
        'carriedBy',
      ] },
      { accessor: 'id', name: 'world_combat_target_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'by_chunk', name: 'world_combat_target_space_id_chunk_x_chunk_y_idx_btree', algorithm: 'btree', columns: [
        'spaceId',
        'chunkX',
        'chunkY',
      ] },
    ],
    constraints: [
      { name: 'world_combat_target_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, WorldCombatTargetRow),
  worldCrop: __table({
    name: 'world_crop',
    indexes: [
      { accessor: 'id', name: 'world_crop_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'by_chunk', name: 'world_crop_space_id_chunk_x_chunk_y_idx_btree', algorithm: 'btree', columns: [
        'spaceId',
        'chunkX',
        'chunkY',
      ] },
    ],
    constraints: [
      { name: 'world_crop_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, WorldCropRow),
  worldEnvironment: __table({
    name: 'world_environment',
    indexes: [
      { accessor: 'id', name: 'world_environment_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'world_environment_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, WorldEnvironmentRow),
  worldHive: __table({
    name: 'world_hive',
    indexes: [
      { accessor: 'id', name: 'world_hive_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'by_chunk', name: 'world_hive_space_id_chunk_x_chunk_y_idx_btree', algorithm: 'btree', columns: [
        'spaceId',
        'chunkX',
        'chunkY',
      ] },
    ],
    constraints: [
      { name: 'world_hive_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, WorldHiveRow),
  worldItem: __table({
    name: 'world_item',
    indexes: [
      { accessor: 'by_expires_tick', name: 'world_item_expires_tick_idx_btree', algorithm: 'btree', columns: [
        'expiresTick',
      ] },
      { accessor: 'id', name: 'world_item_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'by_chunk', name: 'world_item_space_id_chunk_x_chunk_y_idx_btree', algorithm: 'btree', columns: [
        'spaceId',
        'chunkX',
        'chunkY',
      ] },
    ],
    constraints: [
      { name: 'world_item_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, WorldItemRow),
  worldMerchant: __table({
    name: 'world_merchant',
    indexes: [
      { accessor: 'npcId', name: 'world_merchant_npc_id_idx_btree', algorithm: 'btree', columns: [
        'npcId',
      ] },
    ],
    constraints: [
      { name: 'world_merchant_npc_id_key', constraint: 'unique', columns: ['npcId'] },
    ],
  }, WorldMerchantRow),
  worldNpc: __table({
    name: 'world_npc',
    indexes: [
      { accessor: 'id', name: 'world_npc_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'by_rider', name: 'world_npc_rider_idx_hash', algorithm: 'btree', columns: [
        'rider',
      ] },
      { accessor: 'by_chunk', name: 'world_npc_space_id_chunk_x_chunk_y_idx_btree', algorithm: 'btree', columns: [
        'spaceId',
        'chunkX',
        'chunkY',
      ] },
    ],
    constraints: [
      { name: 'world_npc_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, WorldNpcRow),
  worldPlaceable: __table({
    name: 'world_placeable',
    indexes: [
      { accessor: 'by_carrier', name: 'world_placeable_carried_by_idx_btree', algorithm: 'btree', columns: [
        'carriedBy',
      ] },
      { accessor: 'id', name: 'world_placeable_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'by_placer', name: 'world_placeable_placed_by_idx_btree', algorithm: 'btree', columns: [
        'placedBy',
      ] },
      { accessor: 'by_chunk', name: 'world_placeable_space_id_chunk_x_chunk_y_idx_btree', algorithm: 'btree', columns: [
        'spaceId',
        'chunkX',
        'chunkY',
      ] },
    ],
    constraints: [
      { name: 'world_placeable_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, WorldPlaceableRow),
  worldProjectile: __table({
    name: 'world_projectile',
    indexes: [
      { accessor: 'id', name: 'world_projectile_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'by_chunk', name: 'world_projectile_space_id_chunk_x_chunk_y_idx_btree', algorithm: 'btree', columns: [
        'spaceId',
        'chunkX',
        'chunkY',
      ] },
    ],
    constraints: [
      { name: 'world_projectile_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, WorldProjectileRow),
  worldResource: __table({
    name: 'world_resource',
    indexes: [
      { accessor: 'by_depleted', name: 'world_resource_depleted_idx_btree', algorithm: 'btree', columns: [
        'depleted',
      ] },
      { accessor: 'id', name: 'world_resource_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'by_regrowth_progress', name: 'world_resource_regrowth_progress_idx_btree', algorithm: 'btree', columns: [
        'regrowthProgress',
      ] },
      { accessor: 'by_chunk', name: 'world_resource_space_id_chunk_x_chunk_y_idx_btree', algorithm: 'btree', columns: [
        'spaceId',
        'chunkX',
        'chunkY',
      ] },
    ],
    constraints: [
      { name: 'world_resource_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, WorldResourceRow),
  worldSeed: __table({
    name: 'world_seed',
    indexes: [
      { accessor: 'id', name: 'world_seed_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'world_seed_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, WorldSeedRow),
  worldSoil: __table({
    name: 'world_soil',
    indexes: [
      { accessor: 'id', name: 'world_soil_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'by_chunk', name: 'world_soil_space_id_chunk_x_chunk_y_idx_btree', algorithm: 'btree', columns: [
        'spaceId',
        'chunkX',
        'chunkY',
      ] },
    ],
    constraints: [
      { name: 'world_soil_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, WorldSoilRow),
  worldSurface: __table({
    name: 'world_surface',
    indexes: [
      { accessor: 'id', name: 'world_surface_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'by_chunk', name: 'world_surface_space_id_chunk_x_chunk_y_idx_btree', algorithm: 'btree', columns: [
        'spaceId',
        'chunkX',
        'chunkY',
      ] },
    ],
    constraints: [
      { name: 'world_surface_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, WorldSurfaceRow),
  worldTree: __table({
    name: 'world_tree',
    indexes: [
      { accessor: 'id', name: 'world_tree_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'by_chunk', name: 'world_tree_space_id_chunk_x_chunk_y_idx_btree', algorithm: 'btree', columns: [
        'spaceId',
        'chunkX',
        'chunkY',
      ] },
    ],
    constraints: [
      { name: 'world_tree_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, WorldTreeRow),
  worldWildlifeProfile: __table({
    name: 'world_wildlife_profile',
    indexes: [
      { accessor: 'npcId', name: 'world_wildlife_profile_npc_id_idx_btree', algorithm: 'btree', columns: [
        'npcId',
      ] },
      { accessor: 'by_chunk', name: 'world_wildlife_profile_space_id_chunk_x_chunk_y_idx_btree', algorithm: 'btree', columns: [
        'spaceId',
        'chunkX',
        'chunkY',
      ] },
    ],
    constraints: [
      { name: 'world_wildlife_profile_npc_id_key', constraint: 'unique', columns: ['npcId'] },
    ],
  }, WorldWildlifeProfileRow),
  worldWind: __table({
    name: 'world_wind',
    indexes: [
      { accessor: 'id', name: 'world_wind_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'world_wind_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, WorldWindRow),
  activeFarmSkillNodes: __table({
    name: 'active_farm_skill_nodes',
    indexes: [
    ],
    constraints: [
    ],
  }, ActiveFarmSkillNodesRow),
  activeFarmUpgrades: __table({
    name: 'active_farm_upgrades',
    indexes: [
    ],
    constraints: [
    ],
  }, ActiveFarmUpgradesRow),
  activeFishingCasts: __table({
    name: 'active_fishing_casts',
    indexes: [
    ],
    constraints: [
    ],
  }, ActiveFishingCastsRow),
  onlinePlayerAppearances: __table({
    name: 'online_player_appearances',
    indexes: [
    ],
    constraints: [
    ],
  }, OnlinePlayerAppearancesRow),
  onlinePlayerPublic: __table({
    name: 'online_player_public',
    indexes: [
    ],
    constraints: [
    ],
  }, OnlinePlayerPublicRow),
  ownActiveChest: __table({
    name: 'own_active_chest',
    indexes: [
    ],
    constraints: [
    ],
  }, OwnActiveChestRow),
  ownActiveDialogue: __table({
    name: 'own_active_dialogue',
    indexes: [
    ],
    constraints: [
    ],
  }, OwnActiveDialogueRow),
  ownActiveHearthStash: __table({
    name: 'own_active_hearth_stash',
    indexes: [
    ],
    constraints: [
    ],
  }, OwnActiveHearthStashRow),
  ownActivePlaceable: __table({
    name: 'own_active_placeable',
    indexes: [
    ],
    constraints: [
    ],
  }, OwnActivePlaceableRow),
  ownAdminMutationPreviews: __table({
    name: 'own_admin_mutation_previews',
    indexes: [
    ],
    constraints: [
    ],
  }, OwnAdminMutationPreviewsRow),
  ownAdminWorldValidationReports: __table({
    name: 'own_admin_world_validation_reports',
    indexes: [
    ],
    constraints: [
    ],
  }, OwnAdminWorldValidationReportsRow),
  ownCharacterProfile: __table({
    name: 'own_character_profile',
    indexes: [
    ],
    constraints: [
    ],
  }, OwnCharacterProfileRow),
  ownChatChannels: __table({
    name: 'own_chat_channels',
    indexes: [
    ],
    constraints: [
    ],
  }, OwnChatChannelsRow),
  ownCombatState: __table({
    name: 'own_combat_state',
    indexes: [
    ],
    constraints: [
    ],
  }, OwnCombatStateRow),
  ownConnectionNotices: __table({
    name: 'own_connection_notices',
    indexes: [
    ],
    constraints: [
    ],
  }, OwnConnectionNoticesRow),
  ownContentDraft: __table({
    name: 'own_content_draft',
    indexes: [
    ],
    constraints: [
    ],
  }, OwnContentDraftRow),
  ownContentEditorGrant: __table({
    name: 'own_content_editor_grant',
    indexes: [
    ],
    constraints: [
    ],
  }, OwnContentEditorGrantRow),
  ownContentRevisions: __table({
    name: 'own_content_revisions',
    indexes: [
    ],
    constraints: [
    ],
  }, OwnContentRevisionsRow),
  ownCookingJob: __table({
    name: 'own_cooking_job',
    indexes: [
    ],
    constraints: [
    ],
  }, OwnCookingJobRow),
  ownCurrentHomestead: __table({
    name: 'own_current_homestead',
    indexes: [
    ],
    constraints: [
    ],
  }, OwnCurrentHomesteadRow),
  ownEffects: __table({
    name: 'own_effects',
    indexes: [
    ],
    constraints: [
    ],
  }, OwnEffectsRow),
  ownEquipmentPreferences: __table({
    name: 'own_equipment_preferences',
    indexes: [
    ],
    constraints: [
    ],
  }, OwnEquipmentPreferencesRow),
  ownFishingCast: __table({
    name: 'own_fishing_cast',
    indexes: [
    ],
    constraints: [
    ],
  }, OwnFishingCastRow),
  ownHearthStashSlots: __table({
    name: 'own_hearth_stash_slots',
    indexes: [
    ],
    constraints: [
    ],
  }, OwnHearthStashSlotsRow),
  ownHomesteadMembers: __table({
    name: 'own_homestead_members',
    indexes: [
    ],
    constraints: [
    ],
  }, OwnHomesteadMembersRow),
  ownHomesteadUpgrades: __table({
    name: 'own_homestead_upgrades',
    indexes: [
    ],
    constraints: [
    ],
  }, OwnHomesteadUpgradesRow),
  ownInventoryCursor: __table({
    name: 'own_inventory_cursor',
    indexes: [
    ],
    constraints: [
    ],
  }, OwnInventoryCursorRow),
  ownInventoryOverflow: __table({
    name: 'own_inventory_overflow',
    indexes: [
    ],
    constraints: [
    ],
  }, OwnInventoryOverflowRow),
  ownInventorySlots: __table({
    name: 'own_inventory_slots',
    indexes: [
    ],
    constraints: [
    ],
  }, OwnInventorySlotsRow),
  ownKnownRecipes: __table({
    name: 'own_known_recipes',
    indexes: [
    ],
    constraints: [
    ],
  }, OwnKnownRecipesRow),
  ownMembership: __table({
    name: 'own_membership',
    indexes: [
    ],
    constraints: [
    ],
  }, OwnMembershipRow),
  ownOpenChestSlots: __table({
    name: 'own_open_chest_slots',
    indexes: [
    ],
    constraints: [
    ],
  }, OwnOpenChestSlotsRow),
  ownOpenPlaceableSlots: __table({
    name: 'own_open_placeable_slots',
    indexes: [
    ],
    constraints: [
    ],
  }, OwnOpenPlaceableSlotsRow),
  ownOutdoorRewards: __table({
    name: 'own_outdoor_rewards',
    indexes: [
    ],
    constraints: [
    ],
  }, OwnOutdoorRewardsRow),
  ownPlacedPlaceableDamage: __table({
    name: 'own_placed_placeable_damage',
    indexes: [
    ],
    constraints: [
    ],
  }, OwnPlacedPlaceableDamageRow),
  ownPlacedPlaceableSlots: __table({
    name: 'own_placed_placeable_slots',
    indexes: [
    ],
    constraints: [
    ],
  }, OwnPlacedPlaceableSlotsRow),
  ownPlayerPrediction: __table({
    name: 'own_player_prediction',
    indexes: [
    ],
    constraints: [
    ],
  }, OwnPlayerPredictionRow),
  ownPlayerQuestBaselines: __table({
    name: 'own_player_quest_baselines',
    indexes: [
    ],
    constraints: [
    ],
  }, OwnPlayerQuestBaselinesRow),
  ownPlayerQuests: __table({
    name: 'own_player_quests',
    indexes: [
    ],
    constraints: [
    ],
  }, OwnPlayerQuestsRow),
  ownPlayerSkillNodes: __table({
    name: 'own_player_skill_nodes',
    indexes: [
    ],
    constraints: [
    ],
  }, OwnPlayerSkillNodesRow),
  ownPlayerSkillTracks: __table({
    name: 'own_player_skill_tracks',
    indexes: [
    ],
    constraints: [
    ],
  }, OwnPlayerSkillTracksRow),
  ownPlayerSpawn: __table({
    name: 'own_player_spawn',
    indexes: [
    ],
    constraints: [
    ],
  }, OwnPlayerSpawnRow),
  ownPlayerStatisticMilestones: __table({
    name: 'own_player_statistic_milestones',
    indexes: [
    ],
    constraints: [
    ],
  }, OwnPlayerStatisticMilestonesRow),
  ownPlayerStatistics: __table({
    name: 'own_player_statistics',
    indexes: [
    ],
    constraints: [
    ],
  }, OwnPlayerStatisticsRow),
  ownPlayerThought: __table({
    name: 'own_player_thought',
    indexes: [
    ],
    constraints: [
    ],
  }, OwnPlayerThoughtRow),
  ownQuestWorldItems: __table({
    name: 'own_quest_world_items',
    indexes: [
    ],
    constraints: [
    ],
  }, OwnQuestWorldItemsRow),
  ownRogueRewardOffers: __table({
    name: 'own_rogue_reward_offers',
    indexes: [
    ],
    constraints: [
    ],
  }, OwnRogueRewardOffersRow),
  ownRogueRoomExits: __table({
    name: 'own_rogue_room_exits',
    indexes: [
    ],
    constraints: [
    ],
  }, OwnRogueRoomExitsRow),
  ownRogueRun: __table({
    name: 'own_rogue_run',
    indexes: [
    ],
    constraints: [
    ],
  }, OwnRogueRunRow),
  ownRogueRunUpgrades: __table({
    name: 'own_rogue_run_upgrades',
    indexes: [
    ],
    constraints: [
    ],
  }, OwnRogueRunUpgradesRow),
  ownSessionChatNotices: __table({
    name: 'own_session_chat_notices',
    indexes: [
    ],
    constraints: [
    ],
  }, OwnSessionChatNoticesRow),
  ownStats: __table({
    name: 'own_stats',
    indexes: [
    ],
    constraints: [
    ],
  }, OwnStatsRow),
  ownSupportGrant: __table({
    name: 'own_support_grant',
    indexes: [
    ],
    constraints: [
    ],
  }, OwnSupportGrantRow),
  ownSurvival: __table({
    name: 'own_survival',
    indexes: [
    ],
    constraints: [
    ],
  }, OwnSurvivalRow),
  ownTradeOffers: __table({
    name: 'own_trade_offers',
    indexes: [
    ],
    constraints: [
    ],
  }, OwnTradeOffersRow),
  ownTradeSession: __table({
    name: 'own_trade_session',
    indexes: [
    ],
    constraints: [
    ],
  }, OwnTradeSessionRow),
  ownVillageOrders: __table({
    name: 'own_village_orders',
    indexes: [
    ],
    constraints: [
    ],
  }, OwnVillageOrdersRow),
  ownWallet: __table({
    name: 'own_wallet',
    indexes: [
    ],
    constraints: [
    ],
  }, OwnWalletRow),
  runtimeContentDefinitions: __table({
    name: 'runtime_content_definitions',
    indexes: [
    ],
    constraints: [
    ],
  }, RuntimeContentDefinitionsRow),
  visibleChatMessages: __table({
    name: 'visible_chat_messages',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleChatMessagesRow),
  visibleWorldSpeech: __table({
    name: 'visible_world_speech',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleWorldSpeechRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("abandon_quest", AbandonQuestReducer),
  __reducerSchema("abandon_rogue_run", AbandonRogueRunReducer),
  __reducerSchema("accept_party_invite", AcceptPartyInviteReducer),
  __reducerSchema("accept_trade_request", AcceptTradeRequestReducer),
  __reducerSchema("acknowledge_inventory_protocol", AcknowledgeInventoryProtocolReducer),
  __reducerSchema("activate_outdoor_encounter", ActivateOutdoorEncounterReducer),
  __reducerSchema("admin_backfill_legacy_chests", AdminBackfillLegacyChestsReducer),
  __reducerSchema("admin_clear_cursor", AdminClearCursorReducer),
  __reducerSchema("admin_despawn_entity", AdminDespawnEntityReducer),
  __reducerSchema("admin_drain_legacy_chests", AdminDrainLegacyChestsReducer),
  __reducerSchema("admin_drain_overflow", AdminDrainOverflowReducer),
  __reducerSchema("admin_give_items", AdminGiveItemsReducer),
  __reducerSchema("admin_global_notice", AdminGlobalNoticeReducer),
  __reducerSchema("admin_grant_content_editor", AdminGrantContentEditorReducer),
  __reducerSchema("admin_grant_skill_points", AdminGrantSkillPointsReducer),
  __reducerSchema("admin_grant_support", AdminGrantSupportReducer),
  __reducerSchema("admin_kick", AdminKickReducer),
  __reducerSchema("admin_move_entity", AdminMoveEntityReducer),
  __reducerSchema("admin_move_homestead", AdminMoveHomesteadReducer),
  __reducerSchema("admin_move_homestead_exact", AdminMoveHomesteadExactReducer),
  __reducerSchema("admin_notify", AdminNotifyReducer),
  __reducerSchema("admin_playtest_apply_effect", AdminPlaytestApplyEffectReducer),
  __reducerSchema("admin_playtest_grant_upgrade", AdminPlaytestGrantUpgradeReducer),
  __reducerSchema("admin_playtest_spawn", AdminPlaytestSpawnReducer),
  __reducerSchema("admin_relocate_npc", AdminRelocateNpcReducer),
  __reducerSchema("admin_remove_items", AdminRemoveItemsReducer),
  __reducerSchema("admin_repair_entity", AdminRepairEntityReducer),
  __reducerSchema("admin_repair_portal_pair", AdminRepairPortalPairReducer),
  __reducerSchema("admin_replace_entity", AdminReplaceEntityReducer),
  __reducerSchema("admin_reset_quests", AdminResetQuestsReducer),
  __reducerSchema("admin_reset_skill_tree", AdminResetSkillTreeReducer),
  __reducerSchema("admin_respawn", AdminRespawnReducer),
  __reducerSchema("admin_respawn_resources", AdminRespawnResourcesReducer),
  __reducerSchema("admin_restore_map", AdminRestoreMapReducer),
  __reducerSchema("admin_restore_missing_container", AdminRestoreMissingContainerReducer),
  __reducerSchema("admin_revoke_content_editor", AdminRevokeContentEditorReducer),
  __reducerSchema("admin_revoke_support", AdminRevokeSupportReducer),
  __reducerSchema("admin_run_world_repair", AdminRunWorldRepairReducer),
  __reducerSchema("admin_set_chest_migration_phase", AdminSetChestMigrationPhaseReducer),
  __reducerSchema("admin_set_container_slot", AdminSetContainerSlotReducer),
  __reducerSchema("admin_set_display_name", AdminSetDisplayNameReducer),
  __reducerSchema("admin_set_entity_state", AdminSetEntityStateReducer),
  __reducerSchema("admin_set_motd", AdminSetMotdReducer),
  __reducerSchema("admin_set_quest_state", AdminSetQuestStateReducer),
  __reducerSchema("admin_set_slot", AdminSetSlotReducer),
  __reducerSchema("admin_set_space_flags", AdminSetSpaceFlagsReducer),
  __reducerSchema("admin_set_spawn", AdminSetSpawnReducer),
  __reducerSchema("admin_set_stats", AdminSetStatsReducer),
  __reducerSchema("admin_set_time", AdminSetTimeReducer),
  __reducerSchema("admin_set_vitals", AdminSetVitalsReducer),
  __reducerSchema("admin_set_wallet", AdminSetWalletReducer),
  __reducerSchema("admin_set_weather", AdminSetWeatherReducer),
  __reducerSchema("admin_set_wind", AdminSetWindReducer),
  __reducerSchema("admin_spawn_entity", AdminSpawnEntityReducer),
  __reducerSchema("admin_teleport_player", AdminTeleportPlayerReducer),
  __reducerSchema("admin_undo_player", AdminUndoPlayerReducer),
  __reducerSchema("admin_unstick", AdminUnstickReducer),
  __reducerSchema("admin_verify_legacy_chests", AdminVerifyLegacyChestsReducer),
  __reducerSchema("approve_member", ApproveMemberReducer),
  __reducerSchema("buy_merchant_cart", BuyMerchantCartReducer),
  __reducerSchema("buy_merchant_item", BuyMerchantItemReducer),
  __reducerSchema("cancel_trade", CancelTradeReducer),
  __reducerSchema("choose_dialogue_option", ChooseDialogueOptionReducer),
  __reducerSchema("choose_rogue_door", ChooseRogueDoorReducer),
  __reducerSchema("choose_rogue_reward", ChooseRogueRewardReducer),
  __reducerSchema("claim_outdoor_reward", ClaimOutdoorRewardReducer),
  __reducerSchema("clear_content_draft", ClearContentDraftReducer),
  __reducerSchema("close_chest", CloseChestReducer),
  __reducerSchema("close_crafting", CloseCraftingReducer),
  __reducerSchema("close_hearth_stash", CloseHearthStashReducer),
  __reducerSchema("close_npc_dialogue", CloseNpcDialogueReducer),
  __reducerSchema("close_placeable", ClosePlaceableReducer),
  __reducerSchema("combat_defense", CombatDefenseReducer),
  __reducerSchema("craft_inventory_recipe", CraftInventoryRecipeReducer),
  __reducerSchema("create_chat_channel", CreateChatChannelReducer),
  __reducerSchema("create_party", CreatePartyReducer),
  __reducerSchema("decline_trade", DeclineTradeReducer),
  __reducerSchema("distribute_chest_item", DistributeChestItemReducer),
  __reducerSchema("distribute_inventory_item", DistributeInventoryItemReducer),
  __reducerSchema("drop_inventory_cursor", DropInventoryCursorReducer),
  __reducerSchema("drop_selected", DropSelectedReducer),
  __reducerSchema("edit_residence_architecture", EditResidenceArchitectureReducer),
  __reducerSchema("fill_crafting_recipe", FillCraftingRecipeReducer),
  __reducerSchema("fulfill_village_order", FulfillVillageOrderReducer),
  __reducerSchema("gather_world_resource", GatherWorldResourceReducer),
  __reducerSchema("grant_content_editor", GrantContentEditorReducer),
  __reducerSchema("harvest_crop_tile", HarvestCropTileReducer),
  __reducerSchema("heartbeat", HeartbeatReducer),
  __reducerSchema("install_hearth_gathering_sites", InstallHearthGatheringSitesReducer),
  __reducerSchema("interact_entity", InteractEntityReducer),
  __reducerSchema("interact_horse", InteractHorseReducer),
  __reducerSchema("interact_npc", InteractNpcReducer),
  __reducerSchema("inventory_cursor_click", InventoryCursorClickReducer),
  __reducerSchema("inventory_cursor_pickup_all", InventoryCursorPickupAllReducer),
  __reducerSchema("inventory_cursor_quick_craft", InventoryCursorQuickCraftReducer),
  __reducerSchema("inventory_cursor_swap_hotbar", InventoryCursorSwapHotbarReducer),
  __reducerSchema("invite_chat_member", InviteChatMemberReducer),
  __reducerSchema("invite_to_party", InviteToPartyReducer),
  __reducerSchema("join_chat_channel", JoinChatChannelReducer),
  __reducerSchema("jump_horse", JumpHorseReducer),
  __reducerSchema("leave_chat_channel", LeaveChatChannelReducer),
  __reducerSchema("leave_party", LeavePartyReducer),
  __reducerSchema("move_chest_item", MoveChestItemReducer),
  __reducerSchema("move_hearth_furniture", MoveHearthFurnitureReducer),
  __reducerSchema("move_inventory_item", MoveInventoryItemReducer),
  __reducerSchema("move_placeable_item", MovePlaceableItemReducer),
  __reducerSchema("open_hearth_stash", OpenHearthStashReducer),
  __reducerSchema("open_hearth_supply_cache", OpenHearthSupplyCacheReducer),
  __reducerSchema("pickup_embedded_arrow", PickupEmbeddedArrowReducer),
  __reducerSchema("pickup_hearth_furniture", PickupHearthFurnitureReducer),
  __reducerSchema("pickup_quest_world_item", PickupQuestWorldItemReducer),
  __reducerSchema("pickup_world_item", PickupWorldItemReducer),
  __reducerSchema("place_hearth_furniture", PlaceHearthFurnitureReducer),
  __reducerSchema("place_homestead_buildable", PlaceHomesteadBuildableReducer),
  __reducerSchema("prioritize_equipment_skill", PrioritizeEquipmentSkillReducer),
  __reducerSchema("publish_content_change_set", PublishContentChangeSetReducer),
  __reducerSchema("publish_live_map_document", PublishLiveMapDocumentReducer),
  __reducerSchema("purchase_homestead_upgrade", PurchaseHomesteadUpgradeReducer),
  __reducerSchema("purchase_residence_expansion", PurchaseResidenceExpansionReducer),
  __reducerSchema("purchase_skill_node", PurchaseSkillNodeReducer),
  __reducerSchema("quick_move_all_menu_items", QuickMoveAllMenuItemsReducer),
  __reducerSchema("quick_move_menu_item", QuickMoveMenuItemReducer),
  __reducerSchema("remove_homestead_buildable", RemoveHomesteadBuildableReducer),
  __reducerSchema("remove_homestead_member", RemoveHomesteadMemberReducer),
  __reducerSchema("remove_party_member", RemovePartyMemberReducer),
  __reducerSchema("remove_trade_offer_item", RemoveTradeOfferItemReducer),
  __reducerSchema("report_client_error", ReportClientErrorReducer),
  __reducerSchema("request_trade", RequestTradeReducer),
  __reducerSchema("reset_skill_tree", ResetSkillTreeReducer),
  __reducerSchema("restore_content_revision", RestoreContentRevisionReducer),
  __reducerSchema("restore_live_map_revision", RestoreLiveMapRevisionReducer),
  __reducerSchema("return_inventory_cursor", ReturnInventoryCursorReducer),
  __reducerSchema("revoke_content_editor", RevokeContentEditorReducer),
  __reducerSchema("revoke_member", RevokeMemberReducer),
  __reducerSchema("save_content_draft", SaveContentDraftReducer),
  __reducerSchema("select_hotbar", SelectHotbarReducer),
  __reducerSchema("sell_merchant_cart", SellMerchantCartReducer),
  __reducerSchema("sell_merchant_item", SellMerchantItemReducer),
  __reducerSchema("send_chat_message", SendChatMessageReducer),
  __reducerSchema("send_whisper", SendWhisperReducer),
  __reducerSchema("send_world_speech", SendWorldSpeechReducer),
  __reducerSchema("set_appearance", SetAppearanceReducer),
  __reducerSchema("set_display_name", SetDisplayNameReducer),
  __reducerSchema("set_homestead_member_role", SetHomesteadMemberRoleReducer),
  __reducerSchema("set_input", SetInputReducer),
  __reducerSchema("set_message_of_day", SetMessageOfDayReducer),
  __reducerSchema("set_quest_pinned", SetQuestPinnedReducer),
  __reducerSchema("set_trade_accepted", SetTradeAcceptedReducer),
  __reducerSchema("set_trade_offer_bronze", SetTradeOfferBronzeReducer),
  __reducerSchema("set_trade_offer_item", SetTradeOfferItemReducer),
  __reducerSchema("set_world_time", SetWorldTimeReducer),
  __reducerSchema("set_world_weather", SetWorldWeatherReducer),
  __reducerSchema("set_world_wind_direction", SetWorldWindDirectionReducer),
  __reducerSchema("sit_hearth_furniture", SitHearthFurnitureReducer),
  __reducerSchema("skip_rogue_reward", SkipRogueRewardReducer),
  __reducerSchema("sort_menu_container", SortMenuContainerReducer),
  __reducerSchema("stand_hearth_furniture", StandHearthFurnitureReducer),
  __reducerSchema("start_rogue_run", StartRogueRunReducer),
  __reducerSchema("tend_tree", TendTreeReducer),
  __reducerSchema("throw_menu_item", ThrowMenuItemReducer),
  __reducerSchema("toggle_homestead_gate", ToggleHomesteadGateReducer),
  __reducerSchema("travel_hearth_ferry", TravelHearthFerryReducer),
  __reducerSchema("unlock_hearth_legendary_recipe", UnlockHearthLegendaryRecipeReducer),
  __reducerSchema("use_portal", UsePortalReducer),
  __reducerSchema("use_selected", UseSelectedReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
  __procedureSchema("admin_audit_page", AdminAuditPageProcedure.params, AdminAuditPageProcedure.returnType),
  __procedureSchema("admin_chest_migration_status", AdminChestMigrationStatusProcedure.params, AdminChestMigrationStatusProcedure.returnType),
  __procedureSchema("admin_client_errors", AdminClientErrorsProcedure.params, AdminClientErrorsProcedure.returnType),
  __procedureSchema("admin_connections_page", AdminConnectionsPageProcedure.params, AdminConnectionsPageProcedure.returnType),
  __procedureSchema("admin_container_contents", AdminContainerContentsProcedure.params, AdminContainerContentsProcedure.returnType),
  __procedureSchema("admin_entities_in_area", AdminEntitiesInAreaProcedure.params, AdminEntitiesInAreaProcedure.returnType),
  __procedureSchema("admin_find_players", AdminFindPlayersProcedure.params, AdminFindPlayersProcedure.returnType),
  __procedureSchema("admin_homestead", AdminHomesteadProcedure.params, AdminHomesteadProcedure.returnType),
  __procedureSchema("admin_missing_container_recovery", AdminMissingContainerRecoveryProcedure.params, AdminMissingContainerRecoveryProcedure.returnType),
  __procedureSchema("admin_player_inventory", AdminPlayerInventoryProcedure.params, AdminPlayerInventoryProcedure.returnType),
  __procedureSchema("admin_player_mutation_result", AdminPlayerMutationResultProcedure.params, AdminPlayerMutationResultProcedure.returnType),
  __procedureSchema("admin_player_snapshot", AdminPlayerSnapshotProcedure.params, AdminPlayerSnapshotProcedure.returnType),
  __procedureSchema("admin_telemetry", AdminTelemetryProcedure.params, AdminTelemetryProcedure.returnType),
  __procedureSchema("admin_validate_world", AdminValidateWorldProcedure.params, AdminValidateWorldProcedure.returnType),
);

type __SchemaWithTableAccessorAliases = Omit<typeof tablesSchema.schemaType, "tables"> & {
  tables: typeof tablesSchema.schemaType.tables & {
    /** @deprecated Use `cellarExcavation` instead. This alias will be removed in the next major version. */
    readonly "cellar_excavation": Omit<typeof tablesSchema.schemaType.tables["cellarExcavation"], "accessorName"> & { readonly accessorName: "cellar_excavation" };
    /** @deprecated Use `contentDefinition` instead. This alias will be removed in the next major version. */
    readonly "content_definition": Omit<typeof tablesSchema.schemaType.tables["contentDefinition"], "accessorName"> & { readonly accessorName: "content_definition" };
    /** @deprecated Use `contentHead` instead. This alias will be removed in the next major version. */
    readonly "content_head": Omit<typeof tablesSchema.schemaType.tables["contentHead"], "accessorName"> & { readonly accessorName: "content_head" };
    /** @deprecated Use `enemyAttack` instead. This alias will be removed in the next major version. */
    readonly "enemy_attack": Omit<typeof tablesSchema.schemaType.tables["enemyAttack"], "accessorName"> & { readonly accessorName: "enemy_attack" };
    /** @deprecated Use `liveMapDocument` instead. This alias will be removed in the next major version. */
    readonly "live_map_document": Omit<typeof tablesSchema.schemaType.tables["liveMapDocument"], "accessorName"> & { readonly accessorName: "live_map_document" };
    /** @deprecated Use `outdoorEnemyProfile` instead. This alias will be removed in the next major version. */
    readonly "outdoor_enemy_profile": Omit<typeof tablesSchema.schemaType.tables["outdoorEnemyProfile"], "accessorName"> & { readonly accessorName: "outdoor_enemy_profile" };
    /** @deprecated Use `playerAppearance` instead. This alias will be removed in the next major version. */
    readonly "player_appearance": Omit<typeof tablesSchema.schemaType.tables["playerAppearance"], "accessorName"> & { readonly accessorName: "player_appearance" };
    /** @deprecated Use `playerJumpState` instead. This alias will be removed in the next major version. */
    readonly "player_jump_state": Omit<typeof tablesSchema.schemaType.tables["playerJumpState"], "accessorName"> & { readonly accessorName: "player_jump_state" };
    /** @deprecated Use `playerParty` instead. This alias will be removed in the next major version. */
    readonly "player_party": Omit<typeof tablesSchema.schemaType.tables["playerParty"], "accessorName"> & { readonly accessorName: "player_party" };
    /** @deprecated Use `playerPartyMember` instead. This alias will be removed in the next major version. */
    readonly "player_party_member": Omit<typeof tablesSchema.schemaType.tables["playerPartyMember"], "accessorName"> & { readonly accessorName: "player_party_member" };
    /** @deprecated Use `playerPosition` instead. This alias will be removed in the next major version. */
    readonly "player_position": Omit<typeof tablesSchema.schemaType.tables["playerPosition"], "accessorName"> & { readonly accessorName: "player_position" };
    /** @deprecated Use `playerPublic` instead. This alias will be removed in the next major version. */
    readonly "player_public": Omit<typeof tablesSchema.schemaType.tables["playerPublic"], "accessorName"> & { readonly accessorName: "player_public" };
    /** @deprecated Use `rogueEnemyProfile` instead. This alias will be removed in the next major version. */
    readonly "rogue_enemy_profile": Omit<typeof tablesSchema.schemaType.tables["rogueEnemyProfile"], "accessorName"> & { readonly accessorName: "rogue_enemy_profile" };
    /** @deprecated Use `spaceAdminFlag` instead. This alias will be removed in the next major version. */
    readonly "space_admin_flag": Omit<typeof tablesSchema.schemaType.tables["spaceAdminFlag"], "accessorName"> & { readonly accessorName: "space_admin_flag" };
    /** @deprecated Use `spacePortal` instead. This alias will be removed in the next major version. */
    readonly "space_portal": Omit<typeof tablesSchema.schemaType.tables["spacePortal"], "accessorName"> & { readonly accessorName: "space_portal" };
    /** @deprecated Use `worldCampfireState` instead. This alias will be removed in the next major version. */
    readonly "world_campfire_state": Omit<typeof tablesSchema.schemaType.tables["worldCampfireState"], "accessorName"> & { readonly accessorName: "world_campfire_state" };
    /** @deprecated Use `worldChest` instead. This alias will be removed in the next major version. */
    readonly "world_chest": Omit<typeof tablesSchema.schemaType.tables["worldChest"], "accessorName"> & { readonly accessorName: "world_chest" };
    /** @deprecated Use `worldClock` instead. This alias will be removed in the next major version. */
    readonly "world_clock": Omit<typeof tablesSchema.schemaType.tables["worldClock"], "accessorName"> & { readonly accessorName: "world_clock" };
    /** @deprecated Use `worldCombatTarget` instead. This alias will be removed in the next major version. */
    readonly "world_combat_target": Omit<typeof tablesSchema.schemaType.tables["worldCombatTarget"], "accessorName"> & { readonly accessorName: "world_combat_target" };
    /** @deprecated Use `worldCrop` instead. This alias will be removed in the next major version. */
    readonly "world_crop": Omit<typeof tablesSchema.schemaType.tables["worldCrop"], "accessorName"> & { readonly accessorName: "world_crop" };
    /** @deprecated Use `worldEnvironment` instead. This alias will be removed in the next major version. */
    readonly "world_environment": Omit<typeof tablesSchema.schemaType.tables["worldEnvironment"], "accessorName"> & { readonly accessorName: "world_environment" };
    /** @deprecated Use `worldHive` instead. This alias will be removed in the next major version. */
    readonly "world_hive": Omit<typeof tablesSchema.schemaType.tables["worldHive"], "accessorName"> & { readonly accessorName: "world_hive" };
    /** @deprecated Use `worldItem` instead. This alias will be removed in the next major version. */
    readonly "world_item": Omit<typeof tablesSchema.schemaType.tables["worldItem"], "accessorName"> & { readonly accessorName: "world_item" };
    /** @deprecated Use `worldMerchant` instead. This alias will be removed in the next major version. */
    readonly "world_merchant": Omit<typeof tablesSchema.schemaType.tables["worldMerchant"], "accessorName"> & { readonly accessorName: "world_merchant" };
    /** @deprecated Use `worldNpc` instead. This alias will be removed in the next major version. */
    readonly "world_npc": Omit<typeof tablesSchema.schemaType.tables["worldNpc"], "accessorName"> & { readonly accessorName: "world_npc" };
    /** @deprecated Use `worldPlaceable` instead. This alias will be removed in the next major version. */
    readonly "world_placeable": Omit<typeof tablesSchema.schemaType.tables["worldPlaceable"], "accessorName"> & { readonly accessorName: "world_placeable" };
    /** @deprecated Use `worldProjectile` instead. This alias will be removed in the next major version. */
    readonly "world_projectile": Omit<typeof tablesSchema.schemaType.tables["worldProjectile"], "accessorName"> & { readonly accessorName: "world_projectile" };
    /** @deprecated Use `worldResource` instead. This alias will be removed in the next major version. */
    readonly "world_resource": Omit<typeof tablesSchema.schemaType.tables["worldResource"], "accessorName"> & { readonly accessorName: "world_resource" };
    /** @deprecated Use `worldSeed` instead. This alias will be removed in the next major version. */
    readonly "world_seed": Omit<typeof tablesSchema.schemaType.tables["worldSeed"], "accessorName"> & { readonly accessorName: "world_seed" };
    /** @deprecated Use `worldSoil` instead. This alias will be removed in the next major version. */
    readonly "world_soil": Omit<typeof tablesSchema.schemaType.tables["worldSoil"], "accessorName"> & { readonly accessorName: "world_soil" };
    /** @deprecated Use `worldSurface` instead. This alias will be removed in the next major version. */
    readonly "world_surface": Omit<typeof tablesSchema.schemaType.tables["worldSurface"], "accessorName"> & { readonly accessorName: "world_surface" };
    /** @deprecated Use `worldTree` instead. This alias will be removed in the next major version. */
    readonly "world_tree": Omit<typeof tablesSchema.schemaType.tables["worldTree"], "accessorName"> & { readonly accessorName: "world_tree" };
    /** @deprecated Use `worldWildlifeProfile` instead. This alias will be removed in the next major version. */
    readonly "world_wildlife_profile": Omit<typeof tablesSchema.schemaType.tables["worldWildlifeProfile"], "accessorName"> & { readonly accessorName: "world_wildlife_profile" };
    /** @deprecated Use `worldWind` instead. This alias will be removed in the next major version. */
    readonly "world_wind": Omit<typeof tablesSchema.schemaType.tables["worldWind"], "accessorName"> & { readonly accessorName: "world_wind" };
  };
};

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.8.2" as const,
  },
  tables: tablesSchema.schemaType.tables as __SchemaWithTableAccessorAliases["tables"],
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  __SchemaWithTableAccessorAliases,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

const tableAccessorAliases = {
  "cellar_excavation": "cellarExcavation",
  "content_definition": "contentDefinition",
  "content_head": "contentHead",
  "enemy_attack": "enemyAttack",
  "live_map_document": "liveMapDocument",
  "outdoor_enemy_profile": "outdoorEnemyProfile",
  "player_appearance": "playerAppearance",
  "player_jump_state": "playerJumpState",
  "player_party": "playerParty",
  "player_party_member": "playerPartyMember",
  "player_position": "playerPosition",
  "player_public": "playerPublic",
  "rogue_enemy_profile": "rogueEnemyProfile",
  "space_admin_flag": "spaceAdminFlag",
  "space_portal": "spacePortal",
  "world_campfire_state": "worldCampfireState",
  "world_chest": "worldChest",
  "world_clock": "worldClock",
  "world_combat_target": "worldCombatTarget",
  "world_crop": "worldCrop",
  "world_environment": "worldEnvironment",
  "world_hive": "worldHive",
  "world_item": "worldItem",
  "world_merchant": "worldMerchant",
  "world_npc": "worldNpc",
  "world_placeable": "worldPlaceable",
  "world_projectile": "worldProjectile",
  "world_resource": "worldResource",
  "world_seed": "worldSeed",
  "world_soil": "worldSoil",
  "world_surface": "worldSurface",
  "world_tree": "worldTree",
  "world_wildlife_profile": "worldWildlifeProfile",
  "world_wind": "worldWind",
} as const;

function __withTableAccessorAliases<T extends object>(target: T, freeze = false): T {
  const out = Object.create(Object.getPrototypeOf(target)) as T & Record<string, unknown>;
  Object.defineProperties(out, Object.getOwnPropertyDescriptors(target));
  for (const [deprecatedAccessor, targetAccessor] of Object.entries(tableAccessorAliases)) {
    if (deprecatedAccessor in out) {
      continue;
    }
    Object.defineProperty(out, deprecatedAccessor, {
      enumerable: true,
      configurable: false,
      get: () => out[targetAccessor],
    });
  }
  return freeze ? Object.freeze(out) : out;
}

type __DbViewBase = __DbConnectionImpl<typeof REMOTE_MODULE>["db"];
export type DbView = __DbViewBase & {
  /** @deprecated Use `cellarExcavation` instead. This alias will be removed in the next major version. */
  readonly "cellar_excavation": __DbViewBase["cellarExcavation"];
  /** @deprecated Use `contentDefinition` instead. This alias will be removed in the next major version. */
  readonly "content_definition": __DbViewBase["contentDefinition"];
  /** @deprecated Use `contentHead` instead. This alias will be removed in the next major version. */
  readonly "content_head": __DbViewBase["contentHead"];
  /** @deprecated Use `enemyAttack` instead. This alias will be removed in the next major version. */
  readonly "enemy_attack": __DbViewBase["enemyAttack"];
  /** @deprecated Use `liveMapDocument` instead. This alias will be removed in the next major version. */
  readonly "live_map_document": __DbViewBase["liveMapDocument"];
  /** @deprecated Use `outdoorEnemyProfile` instead. This alias will be removed in the next major version. */
  readonly "outdoor_enemy_profile": __DbViewBase["outdoorEnemyProfile"];
  /** @deprecated Use `playerAppearance` instead. This alias will be removed in the next major version. */
  readonly "player_appearance": __DbViewBase["playerAppearance"];
  /** @deprecated Use `playerJumpState` instead. This alias will be removed in the next major version. */
  readonly "player_jump_state": __DbViewBase["playerJumpState"];
  /** @deprecated Use `playerParty` instead. This alias will be removed in the next major version. */
  readonly "player_party": __DbViewBase["playerParty"];
  /** @deprecated Use `playerPartyMember` instead. This alias will be removed in the next major version. */
  readonly "player_party_member": __DbViewBase["playerPartyMember"];
  /** @deprecated Use `playerPosition` instead. This alias will be removed in the next major version. */
  readonly "player_position": __DbViewBase["playerPosition"];
  /** @deprecated Use `playerPublic` instead. This alias will be removed in the next major version. */
  readonly "player_public": __DbViewBase["playerPublic"];
  /** @deprecated Use `rogueEnemyProfile` instead. This alias will be removed in the next major version. */
  readonly "rogue_enemy_profile": __DbViewBase["rogueEnemyProfile"];
  /** @deprecated Use `spaceAdminFlag` instead. This alias will be removed in the next major version. */
  readonly "space_admin_flag": __DbViewBase["spaceAdminFlag"];
  /** @deprecated Use `spacePortal` instead. This alias will be removed in the next major version. */
  readonly "space_portal": __DbViewBase["spacePortal"];
  /** @deprecated Use `worldCampfireState` instead. This alias will be removed in the next major version. */
  readonly "world_campfire_state": __DbViewBase["worldCampfireState"];
  /** @deprecated Use `worldChest` instead. This alias will be removed in the next major version. */
  readonly "world_chest": __DbViewBase["worldChest"];
  /** @deprecated Use `worldClock` instead. This alias will be removed in the next major version. */
  readonly "world_clock": __DbViewBase["worldClock"];
  /** @deprecated Use `worldCombatTarget` instead. This alias will be removed in the next major version. */
  readonly "world_combat_target": __DbViewBase["worldCombatTarget"];
  /** @deprecated Use `worldCrop` instead. This alias will be removed in the next major version. */
  readonly "world_crop": __DbViewBase["worldCrop"];
  /** @deprecated Use `worldEnvironment` instead. This alias will be removed in the next major version. */
  readonly "world_environment": __DbViewBase["worldEnvironment"];
  /** @deprecated Use `worldHive` instead. This alias will be removed in the next major version. */
  readonly "world_hive": __DbViewBase["worldHive"];
  /** @deprecated Use `worldItem` instead. This alias will be removed in the next major version. */
  readonly "world_item": __DbViewBase["worldItem"];
  /** @deprecated Use `worldMerchant` instead. This alias will be removed in the next major version. */
  readonly "world_merchant": __DbViewBase["worldMerchant"];
  /** @deprecated Use `worldNpc` instead. This alias will be removed in the next major version. */
  readonly "world_npc": __DbViewBase["worldNpc"];
  /** @deprecated Use `worldPlaceable` instead. This alias will be removed in the next major version. */
  readonly "world_placeable": __DbViewBase["worldPlaceable"];
  /** @deprecated Use `worldProjectile` instead. This alias will be removed in the next major version. */
  readonly "world_projectile": __DbViewBase["worldProjectile"];
  /** @deprecated Use `worldResource` instead. This alias will be removed in the next major version. */
  readonly "world_resource": __DbViewBase["worldResource"];
  /** @deprecated Use `worldSeed` instead. This alias will be removed in the next major version. */
  readonly "world_seed": __DbViewBase["worldSeed"];
  /** @deprecated Use `worldSoil` instead. This alias will be removed in the next major version. */
  readonly "world_soil": __DbViewBase["worldSoil"];
  /** @deprecated Use `worldSurface` instead. This alias will be removed in the next major version. */
  readonly "world_surface": __DbViewBase["worldSurface"];
  /** @deprecated Use `worldTree` instead. This alias will be removed in the next major version. */
  readonly "world_tree": __DbViewBase["worldTree"];
  /** @deprecated Use `worldWildlifeProfile` instead. This alias will be removed in the next major version. */
  readonly "world_wildlife_profile": __DbViewBase["worldWildlifeProfile"];
  /** @deprecated Use `worldWind` instead. This alias will be removed in the next major version. */
  readonly "world_wind": __DbViewBase["worldWind"];
};

type __TablesBase = __QueryBuilder<typeof tablesSchema.schemaType>;
export type Tables = __TablesBase & {
  /** @deprecated Use `cellarExcavation` instead. This alias will be removed in the next major version. */
  readonly "cellar_excavation": __TablesBase["cellarExcavation"];
  /** @deprecated Use `contentDefinition` instead. This alias will be removed in the next major version. */
  readonly "content_definition": __TablesBase["contentDefinition"];
  /** @deprecated Use `contentHead` instead. This alias will be removed in the next major version. */
  readonly "content_head": __TablesBase["contentHead"];
  /** @deprecated Use `enemyAttack` instead. This alias will be removed in the next major version. */
  readonly "enemy_attack": __TablesBase["enemyAttack"];
  /** @deprecated Use `liveMapDocument` instead. This alias will be removed in the next major version. */
  readonly "live_map_document": __TablesBase["liveMapDocument"];
  /** @deprecated Use `outdoorEnemyProfile` instead. This alias will be removed in the next major version. */
  readonly "outdoor_enemy_profile": __TablesBase["outdoorEnemyProfile"];
  /** @deprecated Use `playerAppearance` instead. This alias will be removed in the next major version. */
  readonly "player_appearance": __TablesBase["playerAppearance"];
  /** @deprecated Use `playerJumpState` instead. This alias will be removed in the next major version. */
  readonly "player_jump_state": __TablesBase["playerJumpState"];
  /** @deprecated Use `playerParty` instead. This alias will be removed in the next major version. */
  readonly "player_party": __TablesBase["playerParty"];
  /** @deprecated Use `playerPartyMember` instead. This alias will be removed in the next major version. */
  readonly "player_party_member": __TablesBase["playerPartyMember"];
  /** @deprecated Use `playerPosition` instead. This alias will be removed in the next major version. */
  readonly "player_position": __TablesBase["playerPosition"];
  /** @deprecated Use `playerPublic` instead. This alias will be removed in the next major version. */
  readonly "player_public": __TablesBase["playerPublic"];
  /** @deprecated Use `rogueEnemyProfile` instead. This alias will be removed in the next major version. */
  readonly "rogue_enemy_profile": __TablesBase["rogueEnemyProfile"];
  /** @deprecated Use `spaceAdminFlag` instead. This alias will be removed in the next major version. */
  readonly "space_admin_flag": __TablesBase["spaceAdminFlag"];
  /** @deprecated Use `spacePortal` instead. This alias will be removed in the next major version. */
  readonly "space_portal": __TablesBase["spacePortal"];
  /** @deprecated Use `worldCampfireState` instead. This alias will be removed in the next major version. */
  readonly "world_campfire_state": __TablesBase["worldCampfireState"];
  /** @deprecated Use `worldChest` instead. This alias will be removed in the next major version. */
  readonly "world_chest": __TablesBase["worldChest"];
  /** @deprecated Use `worldClock` instead. This alias will be removed in the next major version. */
  readonly "world_clock": __TablesBase["worldClock"];
  /** @deprecated Use `worldCombatTarget` instead. This alias will be removed in the next major version. */
  readonly "world_combat_target": __TablesBase["worldCombatTarget"];
  /** @deprecated Use `worldCrop` instead. This alias will be removed in the next major version. */
  readonly "world_crop": __TablesBase["worldCrop"];
  /** @deprecated Use `worldEnvironment` instead. This alias will be removed in the next major version. */
  readonly "world_environment": __TablesBase["worldEnvironment"];
  /** @deprecated Use `worldHive` instead. This alias will be removed in the next major version. */
  readonly "world_hive": __TablesBase["worldHive"];
  /** @deprecated Use `worldItem` instead. This alias will be removed in the next major version. */
  readonly "world_item": __TablesBase["worldItem"];
  /** @deprecated Use `worldMerchant` instead. This alias will be removed in the next major version. */
  readonly "world_merchant": __TablesBase["worldMerchant"];
  /** @deprecated Use `worldNpc` instead. This alias will be removed in the next major version. */
  readonly "world_npc": __TablesBase["worldNpc"];
  /** @deprecated Use `worldPlaceable` instead. This alias will be removed in the next major version. */
  readonly "world_placeable": __TablesBase["worldPlaceable"];
  /** @deprecated Use `worldProjectile` instead. This alias will be removed in the next major version. */
  readonly "world_projectile": __TablesBase["worldProjectile"];
  /** @deprecated Use `worldResource` instead. This alias will be removed in the next major version. */
  readonly "world_resource": __TablesBase["worldResource"];
  /** @deprecated Use `worldSeed` instead. This alias will be removed in the next major version. */
  readonly "world_seed": __TablesBase["worldSeed"];
  /** @deprecated Use `worldSoil` instead. This alias will be removed in the next major version. */
  readonly "world_soil": __TablesBase["worldSoil"];
  /** @deprecated Use `worldSurface` instead. This alias will be removed in the next major version. */
  readonly "world_surface": __TablesBase["worldSurface"];
  /** @deprecated Use `worldTree` instead. This alias will be removed in the next major version. */
  readonly "world_tree": __TablesBase["worldTree"];
  /** @deprecated Use `worldWildlifeProfile` instead. This alias will be removed in the next major version. */
  readonly "world_wildlife_profile": __TablesBase["worldWildlifeProfile"];
  /** @deprecated Use `worldWind` instead. This alias will be removed in the next major version. */
  readonly "world_wind": __TablesBase["worldWind"];
};

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
const tablesBase: __TablesBase = __makeQueryBuilder(tablesSchema.schemaType);
export const tables: Tables = __withTableAccessorAliases(tablesBase, true) as Tables;

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The procedures available in this remote SpacetimeDB module. */
export const procedures = __convertToAccessorMap(proceduresSchema.procedures);

/** The context type returned in callbacks for all possible events. */
export type EventContext = Omit<__EventContextInterface<typeof REMOTE_MODULE>, "db"> & { db: DbView };
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = Omit<__ReducerEventContextInterface<typeof REMOTE_MODULE>, "db"> & { db: DbView };
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = Omit<__SubscriptionEventContextInterface<typeof REMOTE_MODULE>, "db"> & { db: DbView };
/** The context type returned in callbacks for error events. */
export type ErrorContext = Omit<__ErrorContextInterface<typeof REMOTE_MODULE>, "db"> & { db: DbView };
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  declare db: DbView;

  constructor(config: __DbConnectionConfig<typeof REMOTE_MODULE>) {
    super(config);
    this.db = __withTableAccessorAliases(this.db) as DbView;
  }

  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

