// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  mapId: __t.string().primaryKey().name("map_id"),
  revision: __t.u32(),
  contentHash: __t.string().name("content_hash"),
  documentJson: __t.string().name("document_json"),
  assetRegistryRevision: __t.string().name("asset_registry_revision"),
  clientMutationId: __t.string().name("client_mutation_id"),
  updatedBy: __t.identity().name("updated_by"),
  updatedAt: __t.timestamp().name("updated_at"),
});
