// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  npcId: __t.u64().primaryKey().name("npc_id"),
  encounterId: __t.string().name("encounter_id"),
  generation: __t.u64(),
  enemyKind: __t.string().name("enemy_kind"),
  maximumHealth: __t.u16().name("maximum_health"),
  damageCenti: __t.u32().name("damage_centi"),
  nextAttackTick: __t.u64().name("next_attack_tick"),
  attackCycle: __t.u8().name("attack_cycle"),
  wardenPhase: __t.u8().name("warden_phase"),
  phaseCueUntilTick: __t.u64().name("phase_cue_until_tick"),
  role: __t.string(),
  summonState: __t.string().name("summon_state"),
  summonTick: __t.u64().name("summon_tick"),
  summonLastTick: __t.u64().name("summon_last_tick"),
  summonX: __t.i32().name("summon_x"),
  summonY: __t.i32().name("summon_y"),
  spaceId: __t.u16().name("space_id"),
  chunkX: __t.i16().name("chunk_x"),
  chunkY: __t.i16().name("chunk_y"),
});
