// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  owner: __t.identity(),
  partyId: __t.option(__t.u64()).name("party_id"),
  spaceId: __t.u16().name("space_id"),
  instanceKind: __t.string().name("instance_kind"),
  seed: __t.u32(),
  roomNumber: __t.u8().name("room_number"),
  roomKind: __t.string().name("room_kind"),
  theme: __t.string(),
  phase: __t.string(),
  wave: __t.u8(),
  maximumWaves: __t.u8().name("maximum_waves"),
  currency: __t.u16(),
  createdTick: __t.u64().name("created_tick"),
  updatedTick: __t.u64().name("updated_tick"),
});
