// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  identity: __t.identity(),
  questId: __t.string().name("quest_id"),
  state: __t.string(),
  acceptedTick: __t.u64().name("accepted_tick"),
  completedTick: __t.option(__t.u64()).name("completed_tick"),
  turnedInTick: __t.option(__t.u64()).name("turned_in_tick"),
  pinned: __t.bool(),
});
