// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  identity: __t.identity(),
  completionId: __t.string().name("completion_id"),
  itemsJson: __t.string().name("items_json"),
  combatExperience: __t.u32().name("combat_experience"),
  claimed: __t.bool(),
  claimedTick: __t.u64().name("claimed_tick"),
});
