// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  identity: __t.identity(),
  scope: __t.string(),
  grantedBy: __t.identity().name("granted_by"),
  grantedAt: __t.timestamp().name("granted_at"),
  revokedAt: __t.option(__t.timestamp()).name("revoked_at"),
  reason: __t.string(),
});
