// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string(),
  title: __t.string(),
  npcId: __t.u64().name("npc_id"),
  itemKind: __t.string().name("item_kind"),
  quantity: __t.u32(),
  saleValueBronze: __t.u64().name("sale_value_bronze"),
  bonusBronze: __t.u64().name("bonus_bronze"),
  totalBronze: __t.u64().name("total_bronze"),
  revision: __t.u64(),
  contentHash: __t.string().name("content_hash"),
});
