// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  ownerConnection: __t.string().name("owner_connection"),
  sequence: __t.u64(),
  kind: __t.string(),
  startedTick: __t.u64().name("started_tick"),
  readyTick: __t.u64().name("ready_tick"),
  lastProcessedTick: __t.u64().name("last_processed_tick"),
  holdUpdatedAtMicros: __t.u64().name("hold_updated_at_micros"),
  spaceId: __t.u16().name("space_id"),
  originX: __t.i32().name("origin_x"),
  originY: __t.i32().name("origin_y"),
  targetX: __t.i32().name("target_x"),
  targetY: __t.i32().name("target_y"),
  facingX: __t.i32().name("facing_x"),
  facingY: __t.i32().name("facing_y"),
  elevation: __t.i16(),
});
