// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  revision: __t.u64().primaryKey(),
  packId: __t.string().name("pack_id"),
  parentRevision: __t.u64().name("parent_revision"),
  changeSetJson: __t.string().name("change_set_json"),
  inverseChangeSetJson: __t.string().name("inverse_change_set_json"),
  hash: __t.string(),
  actor: __t.identity(),
  timestamp: __t.timestamp(),
  note: __t.string(),
  clientMutationId: __t.string().name("client_mutation_id"),
  requestHash: __t.string().name("request_hash"),
});
