// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  spaceId: __t.u16().primaryKey().name("space_id"),
  owner: __t.identity(),
  ownerName: __t.string().name("owner_name"),
  overworldTileX: __t.u16().name("overworld_tile_x"),
  overworldTileY: __t.u16().name("overworld_tile_y"),
  sizeTier: __t.u8().name("size_tier"),
  siteSeed: __t.u32().name("site_seed"),
  accessMode: __t.string().name("access_mode"),
  establishedTick: __t.u64().name("established_tick"),
  residenceSpaceId: __t.option(__t.u16()).name("residence_space_id"),
  gateOpen: __t.bool().name("gate_open"),
});
