// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  actor: __t.identity(),
  targetIdentity: __t.identity().name("target_identity"),
  operation: __t.string(),
  clientMutationId: __t.string().name("client_mutation_id"),
  baseVersion: __t.string().name("base_version"),
  fingerprint: __t.string(),
  previewJson: __t.string().name("preview_json"),
  expiresAtMicros: __t.u64().name("expires_at_micros"),
});
