// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  runId: __t.u64().name("run_id"),
  slot: __t.u8(),
  upgradeId: __t.string().name("upgrade_id"),
  rarity: __t.string(),
  magnitudePermille: __t.u16().name("magnitude_permille"),
  cost: __t.u16(),
});
