// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  str: __t.u8(),
  dex: __t.u8(),
  con: __t.u8(),
  int: __t.u8(),
  wis: __t.u8(),
  cha: __t.u8(),
  healthCenti: __t.u32().name("health_centi"),
  manaCenti: __t.u32().name("mana_centi"),
  vigourCenti: __t.u32().name("vigour_centi"),
  healthRemainder: __t.u32().name("health_remainder"),
  manaRemainder: __t.u32().name("mana_remainder"),
  vigourRemainder: __t.u32().name("vigour_remainder"),
  regenTick: __t.u64().name("regen_tick"),
  lastSwingTick: __t.u64().name("last_swing_tick"),
});
