// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  spawnSlot: __t.u8().name("spawn_slot"),
  wood: __t.u32(),
  stone: __t.u32(),
  selectedSlot: __t.u8().name("selected_slot"),
  debugBackpackSlots: __t.u16().name("debug_backpack_slots"),
  hungerCenti: __t.u16().name("hunger_centi"),
  hungerUpdatedTick: __t.u64().name("hunger_updated_tick"),
});
