// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  runId: __t.u64().name("run_id"),
  slot: __t.u8(),
  direction: __t.string(),
  destinationKind: __t.string().name("destination_kind"),
  label: __t.string(),
  tileX: __t.i16().name("tile_x"),
  tileY: __t.i16().name("tile_y"),
});
