// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  identity: __t.identity(),
  track: __t.string(),
  experience: __t.u64(),
  spentPoints: __t.u16().name("spent_points"),
  bonusPoints: __t.u16().name("bonus_points"),
  respecCount: __t.u16().name("respec_count"),
});
