// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  npcId: __t.u64().primaryKey().name("npc_id"),
  runId: __t.u64().name("run_id"),
  archetype: __t.string(),
  maxHealth: __t.u16().name("max_health"),
  damage: __t.u16(),
  speedPermille: __t.u16().name("speed_permille"),
  wave: __t.u8(),
  rewardCurrency: __t.u8().name("reward_currency"),
  nextAttackTick: __t.u64().name("next_attack_tick"),
  chunkX: __t.i16().name("chunk_x"),
  chunkY: __t.i16().name("chunk_y"),
  spaceId: __t.u16().name("space_id"),
});
