// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const ActiveChest = __t.object("ActiveChest", {
  identity: __t.identity(),
  chestId: __t.u64(),
});
export type ActiveChest = __Infer<typeof ActiveChest>;

export const ActiveDialogue = __t.object("ActiveDialogue", {
  identity: __t.identity(),
  npcId: __t.u64(),
  dialogueId: __t.string(),
  nodeId: __t.string(),
});
export type ActiveDialogue = __Infer<typeof ActiveDialogue>;

export const ActiveFishingCasts = __t.object("ActiveFishingCasts", {});
export type ActiveFishingCasts = __Infer<typeof ActiveFishingCasts>;

export const ActiveHearthStash = __t.object("ActiveHearthStash", {
  identity: __t.identity(),
  connectionId: __t.connectionId(),
  endpointId: __t.string(),
});
export type ActiveHearthStash = __Infer<typeof ActiveHearthStash>;

export const ActivePlaceable = __t.object("ActivePlaceable", {
  identity: __t.identity(),
  placeableId: __t.u64(),
});
export type ActivePlaceable = __Infer<typeof ActivePlaceable>;

export const AdminInventoryStackInput = __t.object("AdminInventoryStackInput", {
  itemKind: __t.string(),
  quantity: __t.u16(),
  durability: __t.option(__t.u16()),
});
export type AdminInventoryStackInput = __Infer<typeof AdminInventoryStackInput>;

export const AdminMutationPreview = __t.object("AdminMutationPreview", {
  id: __t.string(),
  actor: __t.identity(),
  targetIdentity: __t.identity(),
  operation: __t.string(),
  clientMutationId: __t.string(),
  baseVersion: __t.string(),
  fingerprint: __t.string(),
  previewJson: __t.string(),
  expiresAtMicros: __t.u64(),
});
export type AdminMutationPreview = __Infer<typeof AdminMutationPreview>;

export const AdminObjectStackInput = __t.object("AdminObjectStackInput", {
  itemKind: __t.string(),
  quantity: __t.u16(),
  durability: __t.option(__t.u16()),
  lit: __t.option(__t.bool()),
});
export type AdminObjectStackInput = __Infer<typeof AdminObjectStackInput>;

export const AdminPlayerMutationCommit = __t.object("AdminPlayerMutationCommit", {
  id: __t.string(),
  actor: __t.identity(),
  clientMutationId: __t.string(),
  auditId: __t.u64(),
  targetIdentity: __t.identity(),
  operation: __t.string(),
  committedVersion: __t.string(),
  sourceAuditId: __t.option(__t.u64()),
});
export type AdminPlayerMutationCommit = __Infer<typeof AdminPlayerMutationCommit>;

export const AdminPlayerUndo = __t.object("AdminPlayerUndo", {
  sourceAuditId: __t.u64(),
  actor: __t.identity(),
  clientMutationId: __t.string(),
  targetIdentity: __t.identity(),
  auditId: __t.u64(),
  committedVersion: __t.string(),
});
export type AdminPlayerUndo = __Infer<typeof AdminPlayerUndo>;

export const AdminStatsPatchInput = __t.object("AdminStatsPatchInput", {
  str: __t.option(__t.u8()),
  dex: __t.option(__t.u8()),
  con: __t.option(__t.u8()),
  int: __t.option(__t.u8()),
  wis: __t.option(__t.u8()),
  cha: __t.option(__t.u8()),
});
export type AdminStatsPatchInput = __Infer<typeof AdminStatsPatchInput>;

export const AdminVitalsPatchInput = __t.object("AdminVitalsPatchInput", {
  healthCenti: __t.option(__t.u32()),
  manaCenti: __t.option(__t.u32()),
  vigourCenti: __t.option(__t.u32()),
  hungerCenti: __t.option(__t.u16()),
});
export type AdminVitalsPatchInput = __Infer<typeof AdminVitalsPatchInput>;

export const AdminWorldValidationReport = __t.object("AdminWorldValidationReport", {
  id: __t.string(),
  actor: __t.identity(),
  worldVersion: __t.string(),
  fingerprint: __t.string(),
  reportJson: __t.string(),
  expiresAtMicros: __t.u64(),
});
export type AdminWorldValidationReport = __Infer<typeof AdminWorldValidationReport>;

export const BowCharge = __t.object("BowCharge", {
  identity: __t.identity(),
  startedTick: __t.u64(),
  itemKind: __t.string(),
  fullChargeCostCenti: __t.u32(),
  minimumSwingTicks: __t.u32(),
});
export type BowCharge = __Infer<typeof BowCharge>;

export const CellarDigProgress = __t.object("CellarDigProgress", {
  id: __t.string(),
  spaceId: __t.u16(),
  tileX: __t.i16(),
  tileY: __t.i16(),
  hits: __t.u8(),
  lastHitTick: __t.u64(),
});
export type CellarDigProgress = __Infer<typeof CellarDigProgress>;

export const CellarExcavation = __t.object("CellarExcavation", {
  id: __t.string(),
  spaceId: __t.u16(),
  tileX: __t.i16(),
  tileY: __t.i16(),
  chunkX: __t.i16(),
  chunkY: __t.i16(),
  dugAtTick: __t.u64(),
});
export type CellarExcavation = __Infer<typeof CellarExcavation>;

export const CharacterProfile = __t.object("CharacterProfile", {
  identity: __t.identity(),
  nameChosen: __t.bool(),
  chosenAt: __t.option(__t.timestamp()),
});
export type CharacterProfile = __Infer<typeof CharacterProfile>;

export const ChatChannel = __t.object("ChatChannel", {
  id: __t.u64(),
  slug: __t.string(),
  displayName: __t.string(),
  kind: __t.string(),
  owner: __t.option(__t.identity()),
  createdAt: __t.timestamp(),
});
export type ChatChannel = __Infer<typeof ChatChannel>;

export const ChatChannelMember = __t.object("ChatChannelMember", {
  id: __t.string(),
  channelId: __t.u64(),
  identity: __t.identity(),
  role: __t.string(),
  joinedAt: __t.timestamp(),
});
export type ChatChannelMember = __Infer<typeof ChatChannelMember>;

export const ChatMessage = __t.object("ChatMessage", {
  id: __t.u64(),
  conversationKey: __t.string(),
  channelId: __t.u64(),
  sender: __t.identity(),
  senderDisplayName: __t.string(),
  recipient: __t.option(__t.identity()),
  kind: __t.string(),
  body: __t.string(),
  itemLinksJson: __t.string(),
  sentAt: __t.timestamp(),
});
export type ChatMessage = __Infer<typeof ChatMessage>;

export const ChatMigration = __t.object("ChatMigration", {
  id: __t.u8(),
  sessionNoticesVersion: __t.u8(),
});
export type ChatMigration = __Infer<typeof ChatMigration>;

export const ChatSenderState = __t.object("ChatSenderState", {
  identity: __t.identity(),
  lastSentAtMicros: __t.u64(),
});
export type ChatSenderState = __Infer<typeof ChatSenderState>;

export const ChestMigrationControl = __t.object("ChestMigrationControl", {
  id: __t.u8(),
  phase: __t.string(),
  cursor: __t.option(__t.u64()),
  backfillComplete: __t.bool(),
  verificationFingerprint: __t.string(),
  verificationChestCount: __t.u64(),
  verificationSlotCount: __t.u64(),
  verificationDamageCount: __t.u64(),
  drainFingerprint: __t.string(),
  clientsUsePlaceables: __t.bool(),
  studioUsesPlaceables: __t.bool(),
  updatedAt: __t.timestamp(),
  updatedBy: __t.identity(),
});
export type ChestMigrationControl = __Infer<typeof ChestMigrationControl>;

export const ChestMigrationMapping = __t.object("ChestMigrationMapping", {
  chestId: __t.u64(),
  placeableId: __t.u64(),
});
export type ChestMigrationMapping = __Infer<typeof ChestMigrationMapping>;

export const ClientErrorReport = __t.object("ClientErrorReport", {
  id: __t.string(),
  actor: __t.identity(),
  clientMutationId: __t.string(),
  kind: __t.string(),
  message: __t.string(),
  stack: __t.string(),
  route: __t.string(),
  buildId: __t.string(),
  fingerprint: __t.string(),
  clientObservedAtMs: __t.u64(),
  occurredAtMicros: __t.u64(),
});
export type ClientErrorReport = __Infer<typeof ClientErrorReport>;

export const ConnectionAudit = __t.object("ConnectionAudit", {
  id: __t.u64(),
  connectionId: __t.connectionId(),
  identity: __t.identity(),
  eventKind: __t.string(),
  displayName: __t.string(),
  occurredAt: __t.timestamp(),
  occurredAtMicros: __t.u64(),
});
export type ConnectionAudit = __Infer<typeof ConnectionAudit>;

export const ConnectionNotice = __t.object("ConnectionNotice", {
  connectionId: __t.connectionId(),
  identity: __t.identity(),
  kind: __t.string(),
  body: __t.string(),
  issuedAt: __t.timestamp(),
});
export type ConnectionNotice = __Infer<typeof ConnectionNotice>;

export const ConnectionPresenceV2 = __t.object("ConnectionPresenceV2", {
  connectionId: __t.connectionId(),
  identity: __t.identity(),
  lastSeenAt: __t.timestamp(),
});
export type ConnectionPresenceV2 = __Infer<typeof ConnectionPresenceV2>;

export const ContentDefinition = __t.object("ContentDefinition", {
  id: __t.string(),
  kind: __t.string(),
  slug: __t.string(),
  revision: __t.u64(),
  hash: __t.string(),
  json: __t.string(),
  updatedBy: __t.identity(),
  updatedAt: __t.timestamp(),
});
export type ContentDefinition = __Infer<typeof ContentDefinition>;

export const ContentDraft = __t.object("ContentDraft", {
  identity: __t.identity(),
  baseRevision: __t.u64(),
  changeSetJson: __t.string(),
  updatedAt: __t.timestamp(),
});
export type ContentDraft = __Infer<typeof ContentDraft>;

export const ContentEditorGrant = __t.object("ContentEditorGrant", {
  identity: __t.identity(),
  grantedBy: __t.identity(),
  grantedAt: __t.timestamp(),
  revokedAt: __t.option(__t.timestamp()),
});
export type ContentEditorGrant = __Infer<typeof ContentEditorGrant>;

export const ContentHead = __t.object("ContentHead", {
  packId: __t.string(),
  revision: __t.u64(),
  contentHash: __t.string(),
  engineVersion: __t.u32(),
  definitionCount: __t.u32(),
  updatedBy: __t.identity(),
  updatedAt: __t.timestamp(),
  clientMutationId: __t.string(),
});
export type ContentHead = __Infer<typeof ContentHead>;

export const ContentRevision = __t.object("ContentRevision", {
  revision: __t.u64(),
  packId: __t.string(),
  parentRevision: __t.u64(),
  changeSetJson: __t.string(),
  inverseChangeSetJson: __t.string(),
  hash: __t.string(),
  actor: __t.identity(),
  timestamp: __t.timestamp(),
  note: __t.string(),
  clientMutationId: __t.string(),
  requestHash: __t.string(),
});
export type ContentRevision = __Infer<typeof ContentRevision>;

export const CropPatch = __t.object("CropPatch", {
  id: __t.u64(),
  parcelId: __t.u64(),
  owner: __t.identity(),
  tileX: __t.i16(),
  tileY: __t.i16(),
  chunkX: __t.i16(),
  chunkY: __t.i16(),
  plantedAtTick: __t.u64(),
  watered: __t.bool(),
  wateredAtTick: __t.u64(),
  spaceId: __t.u16(),
});
export type CropPatch = __Infer<typeof CropPatch>;

export const EnemyAttack = __t.object("EnemyAttack", {
  npcId: __t.u64(),
  targetIdentity: __t.identity(),
  sequence: __t.u64(),
  pattern: __t.string(),
  startedTick: __t.u64(),
  lastProcessedTick: __t.u64(),
  tellTicks: __t.u16(),
  activeTicks: __t.u16(),
  recoveryTicks: __t.u16(),
  originX: __t.i32(),
  originY: __t.i32(),
  targetX: __t.i32(),
  targetY: __t.i32(),
  elevation: __t.i16(),
  damageCenti: __t.u32(),
  hitIdentities: __t.array(__t.identity()),
  spaceId: __t.u16(),
  chunkX: __t.i16(),
  chunkY: __t.i16(),
});
export type EnemyAttack = __Infer<typeof EnemyAttack>;

export const EntityTimer = __t.object("EntityTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  entityId: __t.u64(),
  timerId: __t.string(),
  expectedTick: __t.u64(),
});
export type EntityTimer = __Infer<typeof EntityTimer>;

export const FarmActivity = __t.object("FarmActivity", {
  identity: __t.identity(),
  planted: __t.u32(),
  watered: __t.u32(),
  harvested: __t.u32(),
});
export type FarmActivity = __Infer<typeof FarmActivity>;

export const FarmParcel = __t.object("FarmParcel", {
  id: __t.u64(),
  owner: __t.identity(),
  name: __t.string(),
  originX: __t.i16(),
  originY: __t.i16(),
  width: __t.u8(),
  height: __t.u8(),
});
export type FarmParcel = __Infer<typeof FarmParcel>;

export const FishingCast = __t.object("FishingCast", {
  identity: __t.identity(),
  poolId: __t.u64(),
  startedTick: __t.u64(),
  targetTileX: __t.i32(),
  targetTileY: __t.i32(),
});
export type FishingCast = __Infer<typeof FishingCast>;

export const HearthResourceDepletion = __t.object("HearthResourceDepletion", {
  resourceId: __t.u64(),
  activationOrdinal: __t.u32(),
  depletedAtTick: __t.u64(),
  lastObservedTick: __t.u64(),
  quietSinceTick: __t.option(__t.u64()),
  lastObservedMicros: __t.i64(),
});
export type HearthResourceDepletion = __Infer<typeof HearthResourceDepletion>;

export const HearthResourceInstallation = __t.object("HearthResourceInstallation", {
  id: __t.u8(),
  version: __t.u32(),
  mapRevision: __t.u32(),
  mapHash: __t.string(),
  contentHash: __t.string(),
  installedAt: __t.timestamp(),
  installedBy: __t.identity(),
});
export type HearthResourceInstallation = __Infer<typeof HearthResourceInstallation>;

export const HearthStashSlot = __t.object("HearthStashSlot", {
  id: __t.string(),
  identity: __t.identity(),
  slot: __t.u8(),
  itemKind: __t.string(),
  quantity: __t.u16(),
  durability: __t.u16(),
  lit: __t.bool(),
});
export type HearthStashSlot = __Infer<typeof HearthStashSlot>;

export const Homestead = __t.object("Homestead", {
  spaceId: __t.u16(),
  owner: __t.identity(),
  ownerName: __t.string(),
  overworldTileX: __t.u16(),
  overworldTileY: __t.u16(),
  sizeTier: __t.u8(),
  siteSeed: __t.u32(),
  accessMode: __t.string(),
  establishedTick: __t.u64(),
  residenceSpaceId: __t.option(__t.u16()),
  gateOpen: __t.bool(),
  residenceExpansionRank: __t.u8(),
  residenceArchitectureJson: __t.string(),
});
export type Homestead = __Infer<typeof Homestead>;

export const HomesteadDeedClaim = __t.object("HomesteadDeedClaim", {
  identity: __t.identity(),
  purchasedAtTick: __t.u64(),
});
export type HomesteadDeedClaim = __Infer<typeof HomesteadDeedClaim>;

export const HomesteadGuest = __t.object("HomesteadGuest", {
  id: __t.string(),
  spaceId: __t.u16(),
  guest: __t.identity(),
  invitedBy: __t.identity(),
  role: __t.string(),
  grantedTick: __t.u64(),
});
export type HomesteadGuest = __Infer<typeof HomesteadGuest>;

export const HomesteadUpgrade = __t.object("HomesteadUpgrade", {
  id: __t.string(),
  spaceId: __t.u16(),
  upgradeKind: __t.string(),
  rank: __t.u8(),
  purchasedBy: __t.identity(),
  purchasedAtTick: __t.u64(),
});
export type HomesteadUpgrade = __Infer<typeof HomesteadUpgrade>;

export const InventoryCursor = __t.object("InventoryCursor", {
  identity: __t.identity(),
  itemKind: __t.string(),
  quantity: __t.u16(),
  durability: __t.u16(),
  lit: __t.bool(),
});
export type InventoryCursor = __Infer<typeof InventoryCursor>;

export const InventoryMigration = __t.object("InventoryMigration", {
  identity: __t.identity(),
  durabilityVersion: __t.u8(),
  hotbarLayoutVersion: __t.u8(),
  equipmentLayoutVersion: __t.u8(),
});
export type InventoryMigration = __Infer<typeof InventoryMigration>;

export const InventoryOverflow = __t.object("InventoryOverflow", {
  id: __t.u64(),
  identity: __t.identity(),
  itemKind: __t.string(),
  quantity: __t.u16(),
  durability: __t.u16(),
  lit: __t.bool(),
});
export type InventoryOverflow = __Infer<typeof InventoryOverflow>;

export const InventoryOverflowRetry = __t.object("InventoryOverflowRetry", {
  identity: __t.identity(),
});
export type InventoryOverflowRetry = __Infer<typeof InventoryOverflowRetry>;

export const InventoryProtocol = __t.object("InventoryProtocol", {
  connectionId: __t.connectionId(),
  identity: __t.identity(),
  version: __t.u16(),
});
export type InventoryProtocol = __Infer<typeof InventoryProtocol>;

export const InventorySlot = __t.object("InventorySlot", {
  id: __t.string(),
  identity: __t.identity(),
  slot: __t.u8(),
  itemKind: __t.string(),
  quantity: __t.u16(),
  durability: __t.u16(),
  lit: __t.bool(),
});
export type InventorySlot = __Infer<typeof InventorySlot>;

export const LiveMapDocument = __t.object("LiveMapDocument", {
  mapId: __t.string(),
  revision: __t.u32(),
  contentHash: __t.string(),
  documentJson: __t.string(),
  assetRegistryRevision: __t.string(),
  clientMutationId: __t.string(),
  updatedBy: __t.identity(),
  updatedAt: __t.timestamp(),
});
export type LiveMapDocument = __Infer<typeof LiveMapDocument>;

export const LiveMapRevision = __t.object("LiveMapRevision", {
  id: __t.u64(),
  mapId: __t.string(),
  revision: __t.u32(),
  parentRevision: __t.u32(),
  contentHash: __t.string(),
  documentJson: __t.string(),
  clientMutationId: __t.string(),
  actor: __t.identity(),
  occurredAt: __t.timestamp(),
});
export type LiveMapRevision = __Infer<typeof LiveMapRevision>;

export const Membership = __t.object("Membership", {
  identity: __t.identity(),
  role: __t.string(),
  approvedAt: __t.timestamp(),
  approvedBy: __t.identity(),
  revokedAt: __t.option(__t.timestamp()),
  blocked: __t.bool(),
});
export type Membership = __Infer<typeof Membership>;

export const MembershipAudit = __t.object("MembershipAudit", {
  id: __t.u64(),
  actor: __t.identity(),
  target: __t.identity(),
  action: __t.string(),
  role: __t.string(),
  occurredAt: __t.timestamp(),
});
export type MembershipAudit = __Infer<typeof MembershipAudit>;

export const MovementTimer = __t.object("MovementTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type MovementTimer = __Infer<typeof MovementTimer>;

export const OnlinePlayerAppearances = __t.object("OnlinePlayerAppearances", {});
export type OnlinePlayerAppearances = __Infer<typeof OnlinePlayerAppearances>;

export const OnlinePlayerPublic = __t.object("OnlinePlayerPublic", {});
export type OnlinePlayerPublic = __Infer<typeof OnlinePlayerPublic>;

export const OutdoorEncounter = __t.object("OutdoorEncounter", {
  id: __t.string(),
  generation: __t.u64(),
  phase: __t.string(),
  maximumHealthCenti: __t.u32(),
  healthCenti: __t.u32(),
  worldSeed: __t.u32(),
  rewardJson: __t.string(),
  respawnAfterTick: __t.u64(),
  respawnDelayTicks: __t.u64(),
  lastNearbyTick: __t.u64(),
  lastTargetTick: __t.u64(),
  returnStartedTick: __t.u64(),
  activated: __t.bool(),
  conflict: __t.string(),
});
export type OutdoorEncounter = __Infer<typeof OutdoorEncounter>;

export const OutdoorEncounterCompletion = __t.object("OutdoorEncounterCompletion", {
  id: __t.string(),
  encounterId: __t.string(),
  generation: __t.u64(),
  completedTick: __t.u64(),
  rewardRevision: __t.string(),
});
export type OutdoorEncounterCompletion = __Infer<typeof OutdoorEncounterCompletion>;

export const OutdoorEncounterContribution = __t.object("OutdoorEncounterContribution", {
  id: __t.string(),
  encounterId: __t.string(),
  generation: __t.u64(),
  identity: __t.identity(),
  damageCenti: __t.u32(),
  supportCenti: __t.u32(),
  lastUsefulTick: __t.u64(),
});
export type OutdoorEncounterContribution = __Infer<typeof OutdoorEncounterContribution>;

export const OutdoorEnemyProfile = __t.object("OutdoorEnemyProfile", {
  npcId: __t.u64(),
  encounterId: __t.string(),
  generation: __t.u64(),
  enemyKind: __t.string(),
  maximumHealth: __t.u16(),
  damageCenti: __t.u32(),
  nextAttackTick: __t.u64(),
  attackCycle: __t.u8(),
  wardenPhase: __t.u8(),
  phaseCueUntilTick: __t.u64(),
  role: __t.string(),
  summonState: __t.string(),
  summonTick: __t.u64(),
  summonLastTick: __t.u64(),
  summonX: __t.i32(),
  summonY: __t.i32(),
  spaceId: __t.u16(),
  chunkX: __t.i16(),
  chunkY: __t.i16(),
});
export type OutdoorEnemyProfile = __Infer<typeof OutdoorEnemyProfile>;

export const OutdoorRewardClaim = __t.object("OutdoorRewardClaim", {
  id: __t.string(),
  identity: __t.identity(),
  completionId: __t.string(),
  itemsJson: __t.string(),
  combatExperience: __t.u32(),
  claimed: __t.bool(),
  claimedTick: __t.u64(),
});
export type OutdoorRewardClaim = __Infer<typeof OutdoorRewardClaim>;

export const OwnActiveChest = __t.object("OwnActiveChest", {});
export type OwnActiveChest = __Infer<typeof OwnActiveChest>;

export const OwnActiveDialogue = __t.object("OwnActiveDialogue", {});
export type OwnActiveDialogue = __Infer<typeof OwnActiveDialogue>;

export const OwnActiveHearthStash = __t.object("OwnActiveHearthStash", {});
export type OwnActiveHearthStash = __Infer<typeof OwnActiveHearthStash>;

export const OwnActivePlaceable = __t.object("OwnActivePlaceable", {});
export type OwnActivePlaceable = __Infer<typeof OwnActivePlaceable>;

export const OwnAdminMutationPreviews = __t.object("OwnAdminMutationPreviews", {});
export type OwnAdminMutationPreviews = __Infer<typeof OwnAdminMutationPreviews>;

export const OwnAdminWorldValidationReports = __t.object("OwnAdminWorldValidationReports", {});
export type OwnAdminWorldValidationReports = __Infer<typeof OwnAdminWorldValidationReports>;

export const OwnCharacterProfile = __t.object("OwnCharacterProfile", {});
export type OwnCharacterProfile = __Infer<typeof OwnCharacterProfile>;

export const OwnChatChannels = __t.object("OwnChatChannels", {});
export type OwnChatChannels = __Infer<typeof OwnChatChannels>;

export const OwnCombatState = __t.object("OwnCombatState", {});
export type OwnCombatState = __Infer<typeof OwnCombatState>;

export const OwnConnectionNotices = __t.object("OwnConnectionNotices", {});
export type OwnConnectionNotices = __Infer<typeof OwnConnectionNotices>;

export const OwnContentDraft = __t.object("OwnContentDraft", {});
export type OwnContentDraft = __Infer<typeof OwnContentDraft>;

export const OwnContentEditorGrant = __t.object("OwnContentEditorGrant", {});
export type OwnContentEditorGrant = __Infer<typeof OwnContentEditorGrant>;

export const OwnContentRevisions = __t.object("OwnContentRevisions", {});
export type OwnContentRevisions = __Infer<typeof OwnContentRevisions>;

export const OwnCookingJob = __t.object("OwnCookingJob", {});
export type OwnCookingJob = __Infer<typeof OwnCookingJob>;

export const OwnCurrentHomestead = __t.object("OwnCurrentHomestead", {});
export type OwnCurrentHomestead = __Infer<typeof OwnCurrentHomestead>;

export const OwnEffects = __t.object("OwnEffects", {});
export type OwnEffects = __Infer<typeof OwnEffects>;

export const OwnEquipmentPreferences = __t.object("OwnEquipmentPreferences", {});
export type OwnEquipmentPreferences = __Infer<typeof OwnEquipmentPreferences>;

export const OwnFishingCast = __t.object("OwnFishingCast", {});
export type OwnFishingCast = __Infer<typeof OwnFishingCast>;

export const OwnHearthStashSlots = __t.object("OwnHearthStashSlots", {});
export type OwnHearthStashSlots = __Infer<typeof OwnHearthStashSlots>;

export const OwnHomesteadMembers = __t.object("OwnHomesteadMembers", {});
export type OwnHomesteadMembers = __Infer<typeof OwnHomesteadMembers>;

export const OwnHomesteadUpgrades = __t.object("OwnHomesteadUpgrades", {});
export type OwnHomesteadUpgrades = __Infer<typeof OwnHomesteadUpgrades>;

export const OwnInventoryCursor = __t.object("OwnInventoryCursor", {});
export type OwnInventoryCursor = __Infer<typeof OwnInventoryCursor>;

export const OwnInventoryOverflow = __t.object("OwnInventoryOverflow", {});
export type OwnInventoryOverflow = __Infer<typeof OwnInventoryOverflow>;

export const OwnInventorySlots = __t.object("OwnInventorySlots", {});
export type OwnInventorySlots = __Infer<typeof OwnInventorySlots>;

export const OwnKnownRecipes = __t.object("OwnKnownRecipes", {});
export type OwnKnownRecipes = __Infer<typeof OwnKnownRecipes>;

export const OwnMembership = __t.object("OwnMembership", {});
export type OwnMembership = __Infer<typeof OwnMembership>;

export const OwnOpenChestSlots = __t.object("OwnOpenChestSlots", {});
export type OwnOpenChestSlots = __Infer<typeof OwnOpenChestSlots>;

export const OwnOpenPlaceableSlots = __t.object("OwnOpenPlaceableSlots", {});
export type OwnOpenPlaceableSlots = __Infer<typeof OwnOpenPlaceableSlots>;

export const OwnOutdoorRewards = __t.object("OwnOutdoorRewards", {});
export type OwnOutdoorRewards = __Infer<typeof OwnOutdoorRewards>;

export const OwnPlacedPlaceableDamage = __t.object("OwnPlacedPlaceableDamage", {});
export type OwnPlacedPlaceableDamage = __Infer<typeof OwnPlacedPlaceableDamage>;

export const OwnPlacedPlaceableSlots = __t.object("OwnPlacedPlaceableSlots", {});
export type OwnPlacedPlaceableSlots = __Infer<typeof OwnPlacedPlaceableSlots>;

export const OwnPlayerPrediction = __t.object("OwnPlayerPrediction", {});
export type OwnPlayerPrediction = __Infer<typeof OwnPlayerPrediction>;

export const OwnPlayerQuestBaselines = __t.object("OwnPlayerQuestBaselines", {});
export type OwnPlayerQuestBaselines = __Infer<typeof OwnPlayerQuestBaselines>;

export const OwnPlayerQuests = __t.object("OwnPlayerQuests", {});
export type OwnPlayerQuests = __Infer<typeof OwnPlayerQuests>;

export const OwnPlayerSkillNodes = __t.object("OwnPlayerSkillNodes", {});
export type OwnPlayerSkillNodes = __Infer<typeof OwnPlayerSkillNodes>;

export const OwnPlayerSkillTracks = __t.object("OwnPlayerSkillTracks", {});
export type OwnPlayerSkillTracks = __Infer<typeof OwnPlayerSkillTracks>;

export const OwnPlayerSpawn = __t.object("OwnPlayerSpawn", {});
export type OwnPlayerSpawn = __Infer<typeof OwnPlayerSpawn>;

export const OwnPlayerStatisticMilestones = __t.object("OwnPlayerStatisticMilestones", {});
export type OwnPlayerStatisticMilestones = __Infer<typeof OwnPlayerStatisticMilestones>;

export const OwnPlayerStatistics = __t.object("OwnPlayerStatistics", {});
export type OwnPlayerStatistics = __Infer<typeof OwnPlayerStatistics>;

export const OwnPlayerThought = __t.object("OwnPlayerThought", {});
export type OwnPlayerThought = __Infer<typeof OwnPlayerThought>;

export const OwnQuestWorldItems = __t.object("OwnQuestWorldItems", {});
export type OwnQuestWorldItems = __Infer<typeof OwnQuestWorldItems>;

export const OwnRogueRewardOffers = __t.object("OwnRogueRewardOffers", {});
export type OwnRogueRewardOffers = __Infer<typeof OwnRogueRewardOffers>;

export const OwnRogueRoomExits = __t.object("OwnRogueRoomExits", {});
export type OwnRogueRoomExits = __Infer<typeof OwnRogueRoomExits>;

export const OwnRogueRun = __t.object("OwnRogueRun", {});
export type OwnRogueRun = __Infer<typeof OwnRogueRun>;

export const OwnRogueRunUpgrades = __t.object("OwnRogueRunUpgrades", {});
export type OwnRogueRunUpgrades = __Infer<typeof OwnRogueRunUpgrades>;

export const OwnSessionChatNotices = __t.object("OwnSessionChatNotices", {});
export type OwnSessionChatNotices = __Infer<typeof OwnSessionChatNotices>;

export const OwnStats = __t.object("OwnStats", {});
export type OwnStats = __Infer<typeof OwnStats>;

export const OwnSupportGrant = __t.object("OwnSupportGrant", {});
export type OwnSupportGrant = __Infer<typeof OwnSupportGrant>;

export const OwnSurvival = __t.object("OwnSurvival", {});
export type OwnSurvival = __Infer<typeof OwnSurvival>;

export const OwnTradeOffers = __t.object("OwnTradeOffers", {});
export type OwnTradeOffers = __Infer<typeof OwnTradeOffers>;

export const OwnTradeSession = __t.object("OwnTradeSession", {});
export type OwnTradeSession = __Infer<typeof OwnTradeSession>;

export const OwnVillageOrders = __t.object("OwnVillageOrders", {});
export type OwnVillageOrders = __Infer<typeof OwnVillageOrders>;

export const OwnWallet = __t.object("OwnWallet", {});
export type OwnWallet = __Infer<typeof OwnWallet>;

export const PlayerAppearance = __t.object("PlayerAppearance", {
  identity: __t.identity(),
  hairKind: __t.string(),
  shirtKind: __t.string(),
  pantsKind: __t.string(),
  shoesKind: __t.string(),
});
export type PlayerAppearance = __Infer<typeof PlayerAppearance>;

export const PlayerCombatState = __t.object("PlayerCombatState", {
  identity: __t.identity(),
  ownerConnection: __t.string(),
  sequence: __t.u64(),
  kind: __t.string(),
  startedTick: __t.u64(),
  readyTick: __t.u64(),
  lastProcessedTick: __t.u64(),
  holdUpdatedAtMicros: __t.u64(),
  spaceId: __t.u16(),
  originX: __t.i32(),
  originY: __t.i32(),
  targetX: __t.i32(),
  targetY: __t.i32(),
  facingX: __t.i32(),
  facingY: __t.i32(),
  elevation: __t.i16(),
});
export type PlayerCombatState = __Infer<typeof PlayerCombatState>;

export const PlayerCookingJob = __t.object("PlayerCookingJob", {
  identity: __t.identity(),
  targetKind: __t.string(),
  targetId: __t.u64(),
  spaceId: __t.u16(),
  recipeId: __t.string(),
  inputKind: __t.string(),
  outputKind: __t.string(),
  quantity: __t.u8(),
  startedTick: __t.u64(),
  readyTick: __t.u64(),
});
export type PlayerCookingJob = __Infer<typeof PlayerCookingJob>;

export const PlayerDefenseInput = __t.object("PlayerDefenseInput", {
  connectionId: __t.connectionId(),
  sequence: __t.u64(),
});
export type PlayerDefenseInput = __Infer<typeof PlayerDefenseInput>;

export const PlayerEffect = __t.object("PlayerEffect", {
  id: __t.u64(),
  identity: __t.identity(),
  effectKind: __t.string(),
  stacks: __t.u8(),
  appliedTick: __t.u64(),
  expiresTick: __t.u64(),
});
export type PlayerEffect = __Infer<typeof PlayerEffect>;

export const PlayerEquipmentPreferences = __t.object("PlayerEquipmentPreferences", {
  identity: __t.identity(),
  skillPriority: __t.array(__t.string()),
});
export type PlayerEquipmentPreferences = __Infer<typeof PlayerEquipmentPreferences>;

export const PlayerInput = __t.object("PlayerInput", {
  identity: __t.identity(),
  direction: __t.string(),
  sequence: __t.u64(),
  settledSequence: __t.u64(),
  pendingSequence: __t.u64(),
  updatedAtMicros: __t.u64(),
  runStartClientTick: __t.u64(),
  appliedSteps: __t.u64(),
  settleDirection: __t.string(),
  settleSteps: __t.u8(),
  creditStartedAtMicros: __t.u64(),
  creditedSteps: __t.u64(),
  sprinting: __t.bool(),
  lastProcessedSequence: __t.u64(),
});
export type PlayerInput = __Infer<typeof PlayerInput>;

export const PlayerJumpState = __t.object("PlayerJumpState", {
  identity: __t.identity(),
  fromX: __t.i32(),
  fromY: __t.i32(),
  untilTick: __t.u64(),
  spaceId: __t.u16(),
  chunkX: __t.i16(),
  chunkY: __t.i16(),
});
export type PlayerJumpState = __Infer<typeof PlayerJumpState>;

export const PlayerKnownRecipe = __t.object("PlayerKnownRecipe", {
  id: __t.string(),
  identity: __t.identity(),
  recipeId: __t.string(),
  learnedAtTick: __t.u64(),
  sourceKind: __t.string(),
});
export type PlayerKnownRecipe = __Infer<typeof PlayerKnownRecipe>;

export const PlayerParty = __t.object("PlayerParty", {
  id: __t.u64(),
  leader: __t.identity(),
  createdTick: __t.u64(),
});
export type PlayerParty = __Infer<typeof PlayerParty>;

export const PlayerPartyInvite = __t.object("PlayerPartyInvite", {
  id: __t.string(),
  partyId: __t.u64(),
  inviter: __t.identity(),
  invitee: __t.identity(),
  expiresTick: __t.u64(),
});
export type PlayerPartyInvite = __Infer<typeof PlayerPartyInvite>;

export const PlayerPartyMember = __t.object("PlayerPartyMember", {
  identity: __t.identity(),
  partyId: __t.u64(),
  joinedTick: __t.u64(),
});
export type PlayerPartyMember = __Infer<typeof PlayerPartyMember>;

export const PlayerPosition = __t.object("PlayerPosition", {
  identity: __t.identity(),
  x: __t.i32(),
  y: __t.i32(),
  chunkX: __t.i16(),
  chunkY: __t.i16(),
  facing: __t.string(),
  moving: __t.bool(),
  lastProcessedSequence: __t.u64(),
  authorityTick: __t.u64(),
  actionKind: __t.string(),
  actionStartedTick: __t.u64(),
  equippedKind: __t.string(),
  jumpFromX: __t.option(__t.i32()),
  jumpFromY: __t.option(__t.i32()),
  jumpUntilTick: __t.option(__t.u64()),
  spaceId: __t.u16(),
  equippedLit: __t.bool(),
});
export type PlayerPosition = __Infer<typeof PlayerPosition>;

export const PlayerPredictionState = __t.object("PlayerPredictionState", {
  identity: __t.identity(),
  lastProcessedSequence: __t.u64(),
});
export type PlayerPredictionState = __Infer<typeof PlayerPredictionState>;

export const PlayerProcessJobReceipt = __t.object("PlayerProcessJobReceipt", {
  identity: __t.identity(),
  targetKind: __t.string(),
  targetId: __t.u64(),
  spaceId: __t.u16(),
  recipeId: __t.string(),
  inputKind: __t.string(),
  outputKind: __t.string(),
  quantity: __t.u8(),
  startedTick: __t.u64(),
  readyTick: __t.u64(),
  action: __t.string(),
  resolvedTick: __t.u64(),
  grantedKind: __t.string(),
  farmingExperience: __t.u32(),
});
export type PlayerProcessJobReceipt = __Infer<typeof PlayerProcessJobReceipt>;

export const PlayerPublic = __t.object("PlayerPublic", {
  identity: __t.identity(),
  displayName: __t.string(),
  online: __t.bool(),
  lastActiveAtMicros: __t.u64(),
});
export type PlayerPublic = __Infer<typeof PlayerPublic>;

export const PlayerQuest = __t.object("PlayerQuest", {
  id: __t.string(),
  identity: __t.identity(),
  questId: __t.string(),
  state: __t.string(),
  acceptedTick: __t.u64(),
  completedTick: __t.option(__t.u64()),
  turnedInTick: __t.option(__t.u64()),
  pinned: __t.bool(),
});
export type PlayerQuest = __Infer<typeof PlayerQuest>;

export const PlayerQuestBaseline = __t.object("PlayerQuestBaseline", {
  id: __t.string(),
  identity: __t.identity(),
  questId: __t.string(),
  objectiveId: __t.string(),
  value: __t.u64(),
});
export type PlayerQuestBaseline = __Infer<typeof PlayerQuestBaseline>;

export const PlayerQuestFlag = __t.object("PlayerQuestFlag", {
  id: __t.string(),
  identity: __t.identity(),
  flag: __t.string(),
});
export type PlayerQuestFlag = __Infer<typeof PlayerQuestFlag>;

export const PlayerQuestProgressBaseline = __t.object("PlayerQuestProgressBaseline", {
  id: __t.string(),
  identity: __t.identity(),
  questId: __t.string(),
  objectiveId: __t.string(),
  value: __t.u64(),
  currentValue: __t.option(__t.u64()),
});
export type PlayerQuestProgressBaseline = __Infer<typeof PlayerQuestProgressBaseline>;

export const PlayerQuestReachPresence = __t.object("PlayerQuestReachPresence", {
  id: __t.string(),
  identity: __t.identity(),
  questId: __t.string(),
  objectiveId: __t.string(),
});
export type PlayerQuestReachPresence = __Infer<typeof PlayerQuestReachPresence>;

export const PlayerSeat = __t.object("PlayerSeat", {
  identity: __t.identity(),
  placeableId: __t.u64(),
  spaceId: __t.u16(),
  seatedX: __t.i32(),
  seatedY: __t.i32(),
});
export type PlayerSeat = __Infer<typeof PlayerSeat>;

export const PlayerSkillNode = __t.object("PlayerSkillNode", {
  id: __t.string(),
  identity: __t.identity(),
  track: __t.string(),
  nodeId: __t.string(),
  rank: __t.u8(),
});
export type PlayerSkillNode = __Infer<typeof PlayerSkillNode>;

export const PlayerSkillTrack = __t.object("PlayerSkillTrack", {
  id: __t.string(),
  identity: __t.identity(),
  track: __t.string(),
  experience: __t.u64(),
  spentPoints: __t.u16(),
  bonusPoints: __t.u16(),
  respecCount: __t.u16(),
});
export type PlayerSkillTrack = __Infer<typeof PlayerSkillTrack>;

export const PlayerSpawn = __t.object("PlayerSpawn", {
  identity: __t.identity(),
  tileX: __t.i16(),
  tileY: __t.i16(),
  spaceId: __t.u16(),
});
export type PlayerSpawn = __Infer<typeof PlayerSpawn>;

export const PlayerStatistic = __t.object("PlayerStatistic", {
  id: __t.string(),
  identity: __t.identity(),
  statisticKind: __t.string(),
  subjectKind: __t.string(),
  value: __t.u64(),
  createdTick: __t.u64(),
  updatedTick: __t.u64(),
});
export type PlayerStatistic = __Infer<typeof PlayerStatistic>;

export const PlayerStatisticMilestone = __t.object("PlayerStatisticMilestone", {
  id: __t.string(),
  identity: __t.identity(),
  statisticKind: __t.string(),
  subjectKind: __t.string(),
  threshold: __t.u64(),
  achievedTick: __t.u64(),
});
export type PlayerStatisticMilestone = __Infer<typeof PlayerStatisticMilestone>;

export const PlayerStats = __t.object("PlayerStats", {
  identity: __t.identity(),
  str: __t.u8(),
  dex: __t.u8(),
  con: __t.u8(),
  int: __t.u8(),
  wis: __t.u8(),
  cha: __t.u8(),
  healthCenti: __t.u32(),
  manaCenti: __t.u32(),
  vigourCenti: __t.u32(),
  healthRemainder: __t.u32(),
  manaRemainder: __t.u32(),
  vigourRemainder: __t.u32(),
  regenTick: __t.u64(),
  lastSwingTick: __t.u64(),
});
export type PlayerStats = __Infer<typeof PlayerStats>;

export const PlayerSurvival = __t.object("PlayerSurvival", {
  identity: __t.identity(),
  spawnSlot: __t.u8(),
  wood: __t.u32(),
  stone: __t.u32(),
  selectedSlot: __t.u8(),
  debugBackpackSlots: __t.u16(),
  hungerCenti: __t.u16(),
  hungerUpdatedTick: __t.u64(),
});
export type PlayerSurvival = __Infer<typeof PlayerSurvival>;

export const PlayerSurvivalMigration = __t.object("PlayerSurvivalMigration", {
  identity: __t.identity(),
  hungerVersion: __t.u8(),
});
export type PlayerSurvivalMigration = __Infer<typeof PlayerSurvivalMigration>;

export const PlayerThought = __t.object("PlayerThought", {
  identity: __t.identity(),
  body: __t.string(),
  tone: __t.string(),
  issuedTick: __t.u64(),
  expiresTick: __t.u64(),
});
export type PlayerThought = __Infer<typeof PlayerThought>;

export const PlayerTradeOffer = __t.object("PlayerTradeOffer", {
  id: __t.string(),
  tradeId: __t.string(),
  owner: __t.identity(),
  slot: __t.u8(),
  itemKind: __t.string(),
  quantity: __t.u16(),
  durability: __t.u16(),
  lit: __t.bool(),
});
export type PlayerTradeOffer = __Infer<typeof PlayerTradeOffer>;

export const PlayerTradeSession = __t.object("PlayerTradeSession", {
  id: __t.string(),
  requester: __t.identity(),
  recipient: __t.identity(),
  state: __t.string(),
  requesterAccepted: __t.bool(),
  recipientAccepted: __t.bool(),
  requesterBronze: __t.u64(),
  recipientBronze: __t.u64(),
  revision: __t.u64(),
  createdTick: __t.u64(),
});
export type PlayerTradeSession = __Infer<typeof PlayerTradeSession>;

export const PlayerVillageOrderReceipt = __t.object("PlayerVillageOrderReceipt", {
  identity: __t.identity(),
  revision: __t.u64(),
  lastOrderId: __t.string(),
  completedTick: __t.u64(),
});
export type PlayerVillageOrderReceipt = __Infer<typeof PlayerVillageOrderReceipt>;

export const PlayerWallet = __t.object("PlayerWallet", {
  identity: __t.identity(),
  balanceBronze: __t.u64(),
});
export type PlayerWallet = __Infer<typeof PlayerWallet>;

export const PrivateInventory = __t.object("PrivateInventory", {
  identity: __t.identity(),
  fruit: __t.u64(),
  bottles: __t.u64(),
  knowledge: __t.u32(),
});
export type PrivateInventory = __Infer<typeof PrivateInventory>;

export const ProjectileCharge = __t.object("ProjectileCharge", {
  projectileId: __t.u64(),
  chargeMs: __t.u16(),
  damageCenti: __t.u32(),
  critical: __t.bool(),
});
export type ProjectileCharge = __Infer<typeof ProjectileCharge>;

export const QuestWorldItem = __t.object("QuestWorldItem", {
  id: __t.string(),
  identity: __t.identity(),
  questId: __t.string(),
  objectiveId: __t.string(),
  surfaceId: __t.u64(),
  slot: __t.u8(),
  itemKind: __t.string(),
});
export type QuestWorldItem = __Infer<typeof QuestWorldItem>;

export const RogueEnemyProfile = __t.object("RogueEnemyProfile", {
  npcId: __t.u64(),
  runId: __t.u64(),
  archetype: __t.string(),
  maxHealth: __t.u16(),
  damage: __t.u16(),
  speedPermille: __t.u16(),
  wave: __t.u8(),
  rewardCurrency: __t.u8(),
  nextAttackTick: __t.u64(),
  chunkX: __t.i16(),
  chunkY: __t.i16(),
  spaceId: __t.u16(),
});
export type RogueEnemyProfile = __Infer<typeof RogueEnemyProfile>;

export const RogueRewardOffer = __t.object("RogueRewardOffer", {
  id: __t.string(),
  runId: __t.u64(),
  slot: __t.u8(),
  upgradeId: __t.string(),
  rarity: __t.string(),
  magnitudePermille: __t.u16(),
  cost: __t.u16(),
});
export type RogueRewardOffer = __Infer<typeof RogueRewardOffer>;

export const RogueRoomExit = __t.object("RogueRoomExit", {
  id: __t.string(),
  runId: __t.u64(),
  slot: __t.u8(),
  direction: __t.string(),
  destinationKind: __t.string(),
  label: __t.string(),
  tileX: __t.i16(),
  tileY: __t.i16(),
});
export type RogueRoomExit = __Infer<typeof RogueRoomExit>;

export const RogueRun = __t.object("RogueRun", {
  id: __t.u64(),
  owner: __t.identity(),
  partyId: __t.option(__t.u64()),
  spaceId: __t.u16(),
  instanceKind: __t.string(),
  seed: __t.u32(),
  roomNumber: __t.u8(),
  roomKind: __t.string(),
  theme: __t.string(),
  phase: __t.string(),
  wave: __t.u8(),
  maximumWaves: __t.u8(),
  currency: __t.u16(),
  createdTick: __t.u64(),
  updatedTick: __t.u64(),
});
export type RogueRun = __Infer<typeof RogueRun>;

export const RogueRunMember = __t.object("RogueRunMember", {
  identity: __t.identity(),
  runId: __t.u64(),
  returnSpaceId: __t.u16(),
  returnX: __t.i32(),
  returnY: __t.i32(),
  returnFacing: __t.string(),
  savedHealthCenti: __t.u32(),
  savedManaCenti: __t.u32(),
  savedVigourCenti: __t.u32(),
  savedHealthRemainder: __t.u32(),
  savedManaRemainder: __t.u32(),
  savedVigourRemainder: __t.u32(),
  savedHungerCenti: __t.u16(),
  joinedTick: __t.u64(),
});
export type RogueRunMember = __Infer<typeof RogueRunMember>;

export const RogueRunUpgrade = __t.object("RogueRunUpgrade", {
  id: __t.string(),
  runId: __t.u64(),
  upgradeId: __t.string(),
  rarity: __t.string(),
  stacks: __t.u8(),
  magnitudePermille: __t.u16(),
});
export type RogueRunUpgrade = __Infer<typeof RogueRunUpgrade>;

export const RuntimeContentDefinition = __t.object("RuntimeContentDefinition", {
  id: __t.string(),
  kind: __t.string(),
  json: __t.string(),
});
export type RuntimeContentDefinition = __Infer<typeof RuntimeContentDefinition>;

export const RuntimeContentDefinitions = __t.object("RuntimeContentDefinitions", {});
export type RuntimeContentDefinitions = __Infer<typeof RuntimeContentDefinitions>;

export const SessionChatNotice = __t.object("SessionChatNotice", {
  id: __t.u64(),
  recipientIdentity: __t.identity(),
  recipientConnectionId: __t.connectionId(),
  kind: __t.string(),
  body: __t.string(),
  issuedAt: __t.timestamp(),
});
export type SessionChatNotice = __Infer<typeof SessionChatNotice>;

export const SoilDecayTimer = __t.object("SoilDecayTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  soilId: __t.string(),
  expectedDecayAtTick: __t.u64(),
});
export type SoilDecayTimer = __Infer<typeof SoilDecayTimer>;

export const SpaceAdminFlag = __t.object("SpaceAdminFlag", {
  spaceId: __t.u16(),
  flagsJson: __t.string(),
  updatedBy: __t.identity(),
  updatedAt: __t.timestamp(),
});
export type SpaceAdminFlag = __Infer<typeof SpaceAdminFlag>;

export const SpacePortal = __t.object("SpacePortal", {
  id: __t.u32(),
  kind: __t.string(),
  fromSpace: __t.u16(),
  fromTileX: __t.u16(),
  fromTileY: __t.u16(),
  toSpace: __t.u16(),
  toTileX: __t.u16(),
  toTileY: __t.u16(),
});
export type SpacePortal = __Infer<typeof SpacePortal>;

export const StatsMigration = __t.object("StatsMigration", {
  id: __t.u8(),
  creatureHealthVersion: __t.u8(),
});
export type StatsMigration = __Infer<typeof StatsMigration>;

export const SupportGrant = __t.object("SupportGrant", {
  identity: __t.identity(),
  grantedBy: __t.identity(),
  grantedAt: __t.timestamp(),
  revokedAt: __t.option(__t.timestamp()),
});
export type SupportGrant = __Infer<typeof SupportGrant>;

export const VillageOrderQuote = __t.object("VillageOrderQuote", {
  id: __t.string(),
  title: __t.string(),
  npcId: __t.u64(),
  itemKind: __t.string(),
  quantity: __t.u32(),
  saleValueBronze: __t.u64(),
  bonusBronze: __t.u64(),
  totalBronze: __t.u64(),
  revision: __t.u64(),
  contentHash: __t.string(),
});
export type VillageOrderQuote = __Infer<typeof VillageOrderQuote>;

export const VisibleChatMessages = __t.object("VisibleChatMessages", {});
export type VisibleChatMessages = __Infer<typeof VisibleChatMessages>;

export const VisibleWorldSpeech = __t.object("VisibleWorldSpeech", {});
export type VisibleWorldSpeech = __Infer<typeof VisibleWorldSpeech>;

export const WorldAdminAudit = __t.object("WorldAdminAudit", {
  id: __t.u64(),
  actor: __t.identity(),
  action: __t.string(),
  value: __t.string(),
  occurredAt: __t.timestamp(),
  occurredAtMicros: __t.u64(),
  targetKey: __t.string(),
  payload: __t.string(),
});
export type WorldAdminAudit = __Infer<typeof WorldAdminAudit>;

export const WorldCampfireState = __t.object("WorldCampfireState", {
  id: __t.u64(),
  tileX: __t.i16(),
  tileY: __t.i16(),
  spaceId: __t.u16(),
  lit: __t.bool(),
  manualOverride: __t.bool(),
  automatedByNpc: __t.option(__t.u64()),
});
export type WorldCampfireState = __Infer<typeof WorldCampfireState>;

export const WorldChest = __t.object("WorldChest", {
  id: __t.u64(),
  owner: __t.identity(),
  tileX: __t.i16(),
  tileY: __t.i16(),
  chunkX: __t.i16(),
  chunkY: __t.i16(),
  carriedBy: __t.option(__t.identity()),
  spaceId: __t.u16(),
});
export type WorldChest = __Infer<typeof WorldChest>;

export const WorldChestDamage = __t.object("WorldChestDamage", {
  chestId: __t.u64(),
  hits: __t.u8(),
});
export type WorldChestDamage = __Infer<typeof WorldChestDamage>;

export const WorldChestSlot = __t.object("WorldChestSlot", {
  id: __t.string(),
  chestId: __t.u64(),
  slot: __t.u8(),
  itemKind: __t.string(),
  quantity: __t.u16(),
  durability: __t.u16(),
  lit: __t.bool(),
});
export type WorldChestSlot = __Infer<typeof WorldChestSlot>;

export const WorldClock = __t.object("WorldClock", {
  id: __t.u8(),
  authorityTick: __t.u64(),
});
export type WorldClock = __Infer<typeof WorldClock>;

export const WorldCombatTarget = __t.object("WorldCombatTarget", {
  id: __t.u64(),
  kind: __t.string(),
  x: __t.i32(),
  y: __t.i32(),
  chunkX: __t.i16(),
  chunkY: __t.i16(),
  carriedBy: __t.option(__t.identity()),
  healthCenti: __t.u32(),
  maxHealthCenti: __t.u32(),
  regenTick: __t.u64(),
  lastDamagedTick: __t.u64(),
  spaceId: __t.u16(),
  lastHitCritical: __t.bool(),
  definitionId: __t.string(),
});
export type WorldCombatTarget = __Infer<typeof WorldCombatTarget>;

export const WorldCrop = __t.object("WorldCrop", {
  id: __t.string(),
  owner: __t.identity(),
  cropKind: __t.string(),
  tileX: __t.i16(),
  tileY: __t.i16(),
  chunkX: __t.i16(),
  chunkY: __t.i16(),
  plantedAtTick: __t.u64(),
  growthTicks: __t.u64(),
  growthUpdatedAtTick: __t.u64(),
  spaceId: __t.u16(),
});
export type WorldCrop = __Infer<typeof WorldCrop>;

export const WorldEnvironment = __t.object("WorldEnvironment", {
  id: __t.u8(),
  calendarTick: __t.u64(),
  weatherMode: __t.string(),
  cropCalendarOffset: __t.option(__t.i64()),
});
export type WorldEnvironment = __Infer<typeof WorldEnvironment>;

export const WorldHive = __t.object("WorldHive", {
  id: __t.u64(),
  kind: __t.string(),
  variant: __t.u8(),
  tileX: __t.i16(),
  tileY: __t.i16(),
  chunkX: __t.i16(),
  chunkY: __t.i16(),
  honey: __t.u16(),
  beeCount: __t.u8(),
  nextProductionTick: __t.u64(),
  spaceId: __t.u16(),
});
export type WorldHive = __Infer<typeof WorldHive>;

export const WorldItem = __t.object("WorldItem", {
  id: __t.u64(),
  itemKind: __t.string(),
  quantity: __t.u16(),
  x: __t.i32(),
  y: __t.i32(),
  chunkX: __t.i16(),
  chunkY: __t.i16(),
  droppedAtTick: __t.u64(),
  durability: __t.u16(),
  spaceId: __t.u16(),
  lit: __t.bool(),
  reservedFor: __t.option(__t.identity()),
  reservedUntilTick: __t.u64(),
  expiresTick: __t.u64(),
});
export type WorldItem = __Infer<typeof WorldItem>;

export const WorldMerchant = __t.object("WorldMerchant", {
  npcId: __t.u64(),
  dialogueId: __t.string(),
  shopId: __t.string(),
});
export type WorldMerchant = __Infer<typeof WorldMerchant>;

export const WorldMotd = __t.object("WorldMotd", {
  id: __t.u8(),
  body: __t.string(),
  updatedAt: __t.timestamp(),
  updatedBy: __t.identity(),
});
export type WorldMotd = __Infer<typeof WorldMotd>;

export const WorldNpc = __t.object("WorldNpc", {
  id: __t.u64(),
  kind: __t.string(),
  displayName: __t.string(),
  x: __t.i32(),
  y: __t.i32(),
  homeX: __t.i32(),
  homeY: __t.i32(),
  chunkX: __t.i16(),
  chunkY: __t.i16(),
  facing: __t.string(),
  moving: __t.bool(),
  rider: __t.option(__t.identity()),
  wanderDirection: __t.string(),
  nextDecisionTick: __t.u64(),
  authorityTick: __t.u64(),
  health: __t.u16(),
  spaceId: __t.u16(),
  lastHitCritical: __t.bool(),
  panicUntilTick: __t.option(__t.u64()),
  panicSource: __t.option(__t.identity()),
  panicSourceX: __t.i32(),
  panicSourceY: __t.i32(),
});
export type WorldNpc = __Infer<typeof WorldNpc>;

export const WorldPlaceable = __t.object("WorldPlaceable", {
  id: __t.u64(),
  kind: __t.string(),
  tileX: __t.i16(),
  tileY: __t.i16(),
  chunkX: __t.i16(),
  chunkY: __t.i16(),
  spaceId: __t.u16(),
  placedBy: __t.identity(),
  facing: __t.string(),
  open: __t.bool(),
  smeltStartTick: __t.option(__t.u64()),
  lit: __t.bool(),
  carriedBy: __t.option(__t.identity()),
  barrelSealedTick: __t.option(__t.u64()),
  barrelSealedBy: __t.option(__t.identity()),
  cookStartTick: __t.option(__t.u64()),
  cookStartedBy: __t.option(__t.identity()),
  cookInputKind: __t.option(__t.string()),
  processStartTick: __t.option(__t.u64()),
  processStartedBy: __t.option(__t.identity()),
  processInputKind: __t.option(__t.string()),
  definitionId: __t.string(),
  stateJson: __t.string(),
});
export type WorldPlaceable = __Infer<typeof WorldPlaceable>;

export const WorldPlaceableBuild = __t.object("WorldPlaceableBuild", {
  placeableId: __t.u64(),
  spaceId: __t.u16(),
  placedBy: __t.identity(),
  placedAtTick: __t.u64(),
});
export type WorldPlaceableBuild = __Infer<typeof WorldPlaceableBuild>;

export const WorldPlaceableDamage = __t.object("WorldPlaceableDamage", {
  placeableId: __t.u64(),
  hits: __t.u8(),
});
export type WorldPlaceableDamage = __Infer<typeof WorldPlaceableDamage>;

export const WorldPlaceableSlot = __t.object("WorldPlaceableSlot", {
  id: __t.string(),
  placeableId: __t.u64(),
  slot: __t.u8(),
  itemKind: __t.string(),
  quantity: __t.u16(),
  durability: __t.u16(),
  lit: __t.bool(),
});
export type WorldPlaceableSlot = __Infer<typeof WorldPlaceableSlot>;

export const WorldProjectile = __t.object("WorldProjectile", {
  id: __t.u64(),
  owner: __t.identity(),
  x: __t.i32(),
  y: __t.i32(),
  velocityX: __t.i32(),
  velocityY: __t.i32(),
  chunkX: __t.i16(),
  chunkY: __t.i16(),
  spawnedTick: __t.u64(),
  expiresTick: __t.u64(),
  state: __t.string(),
  hitKind: __t.string(),
  hitId: __t.string(),
  spaceId: __t.u16(),
  weaponItemKind: __t.string(),
  ammunitionItemKind: __t.string(),
  projectileKind: __t.string(),
});
export type WorldProjectile = __Infer<typeof WorldProjectile>;

export const WorldResource = __t.object("WorldResource", {
  id: __t.u64(),
  kind: __t.string(),
  tileX: __t.i16(),
  tileY: __t.i16(),
  chunkX: __t.i16(),
  chunkY: __t.i16(),
  health: __t.u8(),
  depleted: __t.bool(),
  spaceId: __t.u16(),
  growthStage: __t.u8(),
  regrowthProgress: __t.u8(),
  miningClass: __t.string(),
  richness: __t.u8(),
  maximumRichness: __t.u8(),
  yieldProgress: __t.u8(),
  yieldsProduced: __t.u8(),
  producedOre: __t.bool(),
  spawnSiteId: __t.u64(),
  activationOrdinal: __t.u32(),
  respawnAtTick: __t.u64(),
  miningClaimedBy: __t.option(__t.identity()),
  miningPartyId: __t.option(__t.u64()),
  miningClaimUntilTick: __t.u64(),
  definitionId: __t.string(),
});
export type WorldResource = __Infer<typeof WorldResource>;

export const WorldResourceMiningClaim = __t.object("WorldResourceMiningClaim", {
  resourceId: __t.u64(),
  claimedBy: __t.identity(),
  partyId: __t.option(__t.u64()),
  claimUntilTick: __t.u64(),
});
export type WorldResourceMiningClaim = __Infer<typeof WorldResourceMiningClaim>;

export const WorldScalabilityMigration = __t.object("WorldScalabilityMigration", {
  id: __t.u8(),
  wildlifeProfileChunkVersion: __t.u8(),
  horseDismountRecoveryVersion: __t.u8(),
  soilDecayTimerVersion: __t.u8(),
  miningVersion: __t.u8(),
  privateStateVersion: __t.u8(),
  legacyFarmVersion: __t.u8(),
});
export type WorldScalabilityMigration = __Infer<typeof WorldScalabilityMigration>;

export const WorldSeed = __t.object("WorldSeed", {
  id: __t.u8(),
  seed: __t.u32(),
  version: __t.u16(),
  mineVersion: __t.u16(),
});
export type WorldSeed = __Infer<typeof WorldSeed>;

export const WorldSoil = __t.object("WorldSoil", {
  id: __t.string(),
  tileX: __t.i16(),
  tileY: __t.i16(),
  chunkX: __t.i16(),
  chunkY: __t.i16(),
  watered: __t.bool(),
  tilledAtTick: __t.u64(),
  wateredAtTick: __t.u64(),
  spaceId: __t.u16(),
});
export type WorldSoil = __Infer<typeof WorldSoil>;

export const WorldSpeech = __t.object("WorldSpeech", {
  id: __t.u64(),
  speaker: __t.identity(),
  speakerDisplayName: __t.string(),
  kind: __t.string(),
  body: __t.string(),
  x: __t.i32(),
  y: __t.i32(),
  createdTick: __t.u64(),
  expiresTick: __t.u64(),
  spaceId: __t.u16(),
  speakerNpcId: __t.option(__t.u64()),
});
export type WorldSpeech = __Infer<typeof WorldSpeech>;

export const WorldSurface = __t.object("WorldSurface", {
  id: __t.u64(),
  kind: __t.string(),
  tileX: __t.i16(),
  tileY: __t.i16(),
  chunkX: __t.i16(),
  chunkY: __t.i16(),
  capacity: __t.u8(),
  spaceId: __t.u16(),
});
export type WorldSurface = __Infer<typeof WorldSurface>;

export const WorldTree = __t.object("WorldTree", {
  id: __t.u64(),
  owner: __t.identity(),
  x: __t.i32(),
  y: __t.i32(),
  chunkX: __t.i16(),
  chunkY: __t.i16(),
  care: __t.u16(),
  tendCount: __t.u32(),
  lastTendedTick: __t.u64(),
  spaceId: __t.u16(),
});
export type WorldTree = __Infer<typeof WorldTree>;

export const WorldWildlifeGeneration = __t.object("WorldWildlifeGeneration", {
  id: __t.u8(),
  version: __t.u16(),
});
export type WorldWildlifeGeneration = __Infer<typeof WorldWildlifeGeneration>;

export const WorldWildlifeProfile = __t.object("WorldWildlifeProfile", {
  npcId: __t.u64(),
  species: __t.string(),
  variant: __t.u8(),
  packId: __t.u64(),
  habitat: __t.string(),
  chunkX: __t.i16(),
  chunkY: __t.i16(),
  spaceId: __t.u16(),
});
export type WorldWildlifeProfile = __Infer<typeof WorldWildlifeProfile>;

export const WorldWind = __t.object("WorldWind", {
  id: __t.u8(),
  direction: __t.string(),
});
export type WorldWind = __Infer<typeof WorldWind>;

