// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  kind: __t.string(),
  x: __t.i32(),
  y: __t.i32(),
  chunkX: __t.i16().name("chunk_x"),
  chunkY: __t.i16().name("chunk_y"),
  carriedBy: __t.option(__t.identity()).name("carried_by"),
  healthCenti: __t.u32().name("health_centi"),
  maxHealthCenti: __t.u32().name("max_health_centi"),
  regenTick: __t.u64().name("regen_tick"),
  lastDamagedTick: __t.u64().name("last_damaged_tick"),
  spaceId: __t.u16().name("space_id"),
  lastHitCritical: __t.bool().name("last_hit_critical"),
});
