// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  spaceId: __t.u64().primaryKey().name("space_id"),
  revision: __t.u32(),
  mapId: __t.string().name("map_id"),
  contentHash: __t.string().name("content_hash"),
  manifestJson: __t.string().name("manifest_json"),
});
