// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  spaceId: __t.u64().name("space_id"),
  cx: __t.i32(),
  cy: __t.i32(),
  contentHash: __t.string().name("content_hash"),
  revision: __t.u32(),
  byteLength: __t.u32().name("byte_length"),
});
