// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  owner: __t.identity(),
  tileX: __t.i16().name("tile_x"),
  tileY: __t.i16().name("tile_y"),
  chunkX: __t.i16().name("chunk_x"),
  chunkY: __t.i16().name("chunk_y"),
  carriedBy: __t.option(__t.identity()).name("carried_by"),
  spaceId: __t.u16().name("space_id"),
});
