// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  owner: __t.identity(),
  cropKind: __t.string().name("crop_kind"),
  tileX: __t.i16().name("tile_x"),
  tileY: __t.i16().name("tile_y"),
  chunkX: __t.i16().name("chunk_x"),
  chunkY: __t.i16().name("chunk_y"),
  plantedAtTick: __t.u64().name("planted_at_tick"),
  growthTicks: __t.u64().name("growth_ticks"),
  growthUpdatedAtTick: __t.u64().name("growth_updated_at_tick"),
  spaceId: __t.u16().name("space_id"),
});
