// Generated by `npm run world:chunks:asset-inventory` from packages/engine/src/overworld-art.ts. Do not edit.
import type { ChunkAssetInventory } from './assets.js';

export const CHUNK_ASSET_INVENTORY_DATA: ChunkAssetInventory = {
  "terrain": [
    "tile_cf_beach",
    "tile_cf_beach_inset",
    "tile_cf_cave_floor",
    "tile_cf_cave_floor_2",
    "tile_cf_cave_floor_decoration",
    "tile_cf_cave_floor_middle",
    "tile_cf_cave_wall",
    "tile_cf_desert",
    "tile_cf_desert_grass",
    "tile_cf_desert_grass_edge",
    "tile_cf_desert_grass_inset",
    "tile_cf_desert_shore",
    "tile_cf_desert_shore_inset",
    "tile_cf_farmland",
    "tile_cf_farmland_grass_inset",
    "tile_cf_farmland_wet",
    "tile_cf_freshwater",
    "tile_cf_freshwater_inset",
    "tile_cf_grass",
    "tile_cf_grass_dirt_cliff_edge",
    "tile_cf_grass_dirt_cliff_ramp",
    "tile_cf_grass_tuft",
    "tile_cf_hearth_pavement",
    "tile_cf_hearth_townhouse_floor",
    "tile_cf_interior_wall",
    "tile_cf_path",
    "tile_cf_rogue_dungeon_floor",
    "tile_cf_rogue_dungeon_wall",
    "tile_cf_rogue_volcanic_floor",
    "tile_cf_rogue_volcanic_lava",
    "tile_cf_rogue_volcanic_wall",
    "tile_cf_savanna_grass_inset",
    "tile_cf_stone_cliff_inverse_overlay",
    "tile_cf_stone_cliff_variants",
    "tile_cf_water",
    "tile_cf_water_ripples",
    "tile_cf_water_rock_flow",
    "tile_cf_waterfall",
    "tile_cf_waterfall_flow",
    "tile_cf_wood_floor"
  ],
  "natureFamilies": {
    "nature_grass": [
      "grass",
      3
    ],
    "nature_flower_grass": [
      "flower_grass",
      15
    ],
    "nature_flower": [
      "flower",
      5
    ],
    "nature_mushroom": [
      "mushroom",
      8
    ],
    "nature_rock": [
      "rock",
      14
    ],
    "nature_lily_pad": [
      "lily_pad",
      12
    ],
    "nature_water_flower": [
      "water_flower",
      12
    ],
    "nature_cattail": [
      "cattail",
      5
    ],
    "nature_water_grass": [
      "water_grass",
      2
    ],
    "nature_water_rock": [
      "water_rock",
      10
    ],
    "nature_fish_shadow": [
      "fish_shadow",
      1
    ],
    "nature_desert_grass": [
      "desert_grass",
      3
    ],
    "nature_desert_fern": [
      "desert_fern",
      1
    ],
    "nature_desert_bush": [
      "desert_bush",
      2
    ],
    "nature_desert_plant": [
      "desert_plant",
      3
    ],
    "nature_desert_rock": [
      "desert_rock",
      4
    ]
  },
  "resourceAliases": {
    "loose_stone": "resource_cf_rock_stone",
    "cactus": "resource_cf_cactus",
    "tree_oak": "tree_cf_oak_mature",
    "tree_birch": "tree_cf_birch_mature",
    "tree_spruce": "tree_cf_spruce_mature",
    "tree_acacia": "tree_cf_acacia_mature",
    "tree_palm": "tree_cf_palm_mature",
    "tree_cf_fruit_mature": "tree_cf_fruit_mature",
    "tree_sapling": "tree_cf_fruit_small",
    "tree_young": "tree_cf_fruit_medium",
    "tree_oak_sapling": "tree_cf_oak_sapling",
    "tree_oak_young": "tree_cf_oak_young",
    "tree_birch_sapling": "tree_cf_birch_sapling",
    "tree_birch_young": "tree_cf_birch_young",
    "tree_spruce_sapling": "tree_cf_spruce_sapling",
    "tree_spruce_young": "tree_cf_spruce_young",
    "tree_stump_small": "tree_cf_oak_stump_small",
    "tree_stump_medium": "tree_cf_oak_stump_medium",
    "tree_stump": "tree_cf_oak_stump",
    "tree_birch_stump_small": "tree_cf_birch_stump_small",
    "tree_birch_stump_medium": "tree_cf_birch_stump_medium",
    "tree_birch_stump": "tree_cf_birch_stump",
    "tree_spruce_stump_small": "tree_cf_spruce_stump_small",
    "tree_spruce_stump_medium": "tree_cf_spruce_stump_medium",
    "tree_spruce_stump": "tree_cf_spruce_stump",
    "tree_fruit_stump_small": "tree_cf_fruit_stump_small",
    "tree_fruit_stump_medium": "tree_cf_fruit_stump_medium",
    "tree_fruit_stump": "tree_cf_fruit_stump",
    "tree_acacia_stump": "tree_cf_acacia_stump",
    "tree_palm_stump": "tree_cf_palm_stump"
  }
};
