import { expect, it, vi } from 'vitest';
import { uiDialogue } from './dialogue.js';
import { UiRoot } from '../runtime/root.js';
it('uses current choices for numbered and focused activation and preserves close behavior', () => {
    const choose = vi.fn(), close = vi.fn(), root = new UiRoot({ scale: 1 });
    root.resize(600, 400);
    const model = { id: 'greeting', speaker: 'Marlow', body: 'Welcome to the orchard.', choices: [{ id: 'shop', label: 'Show me your shop' }, { id: 'leave', label: 'Goodbye' }] };
    const frame = uiDialogue({ model, choose, onClose: close });
    root.mount(frame);
    root.arrange();
    frame.handleDialogueKey('Digit1');
    expect(choose).toHaveBeenCalledWith('shop');
    frame.updateDialogue({ ...model, id: 'quest', choices: [{ id: 'accept', label: 'Accept quest' }] });
    root.arrange();
    frame.handleDialogueKey('Digit2');
    expect(choose).toHaveBeenCalledTimes(1);
    const button = root.entries().find(e => e.element.id === 'dialogue:accept')!.element;
    root.focus.set(button, 'keyboard');
    root.key({ key: 'Enter' });
    expect(choose).toHaveBeenLastCalledWith('accept');
    frame.handleDialogueKey('Escape');
    expect(close).toHaveBeenCalledOnce();
    root.dispose();
});
it('retains ordinary snapshot focus and scroll, but retires changed choice captures', () => {
    const choose = vi.fn(), root = new UiRoot({ scale: 1 });
    root.resize(320, 180);
    const model = { id: 'greeting', speaker: 'An ordinary title', body: 'A long dialogue. '.repeat(25), choices: Array.from({ length: 15 }, (_, i) => ({ id: String(i), label: 'A long offered choice ' + i })) };
    const frame = uiDialogue({ model, choose, onClose: vi.fn() });
    root.mount(frame);
    root.arrange();
    const button = root.entries().find(e => e.element.id === 'dialogue:10')!.element;
    root.focus.set(button, 'keyboard');
    root.arrange();
    const scroll = frame.children[0]!, offset = scroll.scroll.y;
    frame.updateDialogue({ ...model, speaker: 'Updated ordinary title' });
    root.arrange();
    expect(root.focus.current).toBe(button);
    expect(scroll.scroll.y).toBe(offset);
    const point = { x: button.rect.x + 5, y: button.rect.y + 5 };
    root.pointer({ type: 'down', point, pointerId: 1, button: 0 });
    frame.updateDialogue({ ...model, choices: model.choices.filter(c => c.id !== '10') });
    root.pointer({ type: 'up', point, pointerId: 1, button: 0 });
    expect(choose).not.toHaveBeenCalled();
    root.dispose();
});
