import { expect, it, vi } from 'vitest';
import { UiRoot } from '../runtime/root.js';
import { uiMerchantPanel, type UiMerchantPanelModel } from './merchant-panels.js';
it('presents quotes without sending before confirmation, locks pending and retires changed quote captures', () => {
    const root = new UiRoot({ scale: 1 });
    root.resize(320, 240);
    const select = vi.fn(), confirm = vi.fn();
    const model: UiMerchantPanelModel = { id: 'offers', title: 'VILLAGE ORDERS', lines: ['Milestone'], rows: [{ id: 'one', label: '1. Carrots', detail: 'Receive 30 bronze' }], notice: '', pending: false, backLabel: 'CLOSE' };
    const panel = uiMerchantPanel({ model, select, confirm, back: vi.fn(), close: vi.fn(), page: vi.fn() });
    root.mount(panel);
    root.arrange();
    const find = (id: string) => root.entries().find(e => e.element.id === id)!.element;
    root.focus.set(find('merchant.panel.offer:one'), 'keyboard');
    root.key({ key: 'Enter' });
    expect(select).toHaveBeenCalledExactlyOnceWith('one');
    expect(confirm).not.toHaveBeenCalled();
    const review = { ...model, id: 'review:one:quote1', rows: [], lines: ['YOU DELIVER', '3 carrots', 'YOU RECEIVE 30 bronze'], confirmLabel: 'DELIVER', canConfirm: true };
    panel.updatePanel(review);
    root.arrange();
    const old = find('merchant.panel.confirm');
    root.focus.set(old, 'keyboard');
    root.arrange();
    const point = { x: old.rect.x + 2, y: old.rect.y + 2 };
    root.pointer({ type: 'down', point, pointerId: 1, button: 0 });
    panel.updatePanel({ ...review, id: 'review:one:quote2' });
    root.pointer({ type: 'up', point, pointerId: 1, button: 0 });
    expect(confirm).not.toHaveBeenCalled();
    panel.updatePanel({ ...review, pending: true });
    root.arrange();
    expect(find('merchant.panel.confirm').disabled).toBe(true);
    root.dispose();
});
