import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { bootstrapContentDefinitions, type ItemContentDefinition } from '@orchard/sim';

interface Owners {
  readonly dataGraph: { readonly itemIds: readonly string[] };
  readonly furnitureTransactions: { readonly itemIds: readonly string[] };
}
interface Handler { readonly itemId: string; readonly triggers: readonly string[] }
interface InertGroup { readonly classification: string; readonly itemIds: readonly string[] }
export interface ActionBaselineSources {
  readonly items: readonly ItemContentDefinition[];
  readonly handlers: readonly Handler[];
  readonly owners: Owners;
  readonly inertGroups: readonly InertGroup[];
}
export interface ActionBaselineRow {
  readonly id: string;
  readonly owner: string;
  readonly triggers: readonly string[];
  readonly values: Readonly<Record<string, number>>;
}

/** Inventory only: these paths are observations, not the future modifier registry.
 * Include every numeric leaf so a new authored parameter cannot silently disappear. */
export function numericLeaves(value: unknown, path = ''): Record<string, number> {
  if (typeof value === 'number') {
    if (!Number.isFinite(value)) throw new Error(`Non-finite action baseline value: ${path}`);
    return { [path]: value };
  }
  if (value === null || typeof value !== 'object') return {};
  return Object.fromEntries(Object.entries(value).sort(([a], [b]) => a.localeCompare(b, 'en'))
    .flatMap(([key, child]) => Object.entries(numericLeaves(child, path ? `${path}.${key}` : key))));
}

export function buildActionBaseline(sources: ActionBaselineSources): readonly ActionBaselineRow[] {
  const live = sources.items.filter(item => !item.retired);
  const ids = new Set(live.map(item => item.id as string));
  if (ids.size !== live.length) throw new Error('Duplicate live item ID');
  const ownership = new Map<string, string>();
  const assign = (id: string, owner: string) => {
    if (!ids.has(id)) throw new Error(`Stale action owner: ${id}`);
    if (ownership.has(id)) throw new Error(`Conflicting action owners: ${id}`);
    ownership.set(id, owner);
  };
  for (const id of new Set(sources.handlers.map(handler => handler.itemId))) assign(id, 'callback');
  for (const id of sources.owners.dataGraph.itemIds) assign(id, 'data graph');
  for (const id of sources.owners.furnitureTransactions.itemIds) assign(id, 'furniture transaction');
  for (const group of sources.inertGroups) for (const id of group.itemIds) assign(id, `inert: ${group.classification}`);
  return live.sort((a, b) => a.id.localeCompare(b.id, 'en')).map(item => {
    const owner = ownership.get(item.id);
    if (!owner) throw new Error(`Unclassified action source: ${item.id}`);
    const triggers = owner === 'callback'
      ? [...new Set(sources.handlers.filter(handler => handler.itemId === item.id).flatMap(handler => handler.triggers))].sort()
      : owner === 'data graph' ? ['secondary'] : [];
    if (owner === 'callback' && triggers.length === 0) throw new Error(`Missing action trigger: ${item.id}`);
    return { id: item.id, owner, triggers, values: numericLeaves(item) };
  });
}

export function loadActionBaseline(): readonly ActionBaselineRow[] {
  const audit = new URL('../../lifecycle-authoring/audit/', import.meta.url);
  const metadata = JSON.parse(readFileSync(new URL('../../lifecycle-authoring/generated/item-lifecycle-metadata.json', import.meta.url), 'utf8')) as { handlers: Handler[] };
  const owners = JSON.parse(readFileSync(new URL('reviewed-item-action-owners.json', audit), 'utf8')) as Owners;
  const inert = JSON.parse(readFileSync(new URL('reviewed-inert-items.json', audit), 'utf8')) as { groups: InertGroup[] };
  return buildActionBaseline({
    items: bootstrapContentDefinitions().filter((definition): definition is ItemContentDefinition => definition.kind === 'item'),
    handlers: metadata.handlers, owners, inertGroups: inert.groups,
  });
}

export function renderActionBaseline(rows: readonly ActionBaselineRow[]): string {
  const counts = new Map<string, number>();
  for (const row of rows) {
    const owner = row.owner.startsWith('inert:') ? 'inert' : row.owner;
    counts.set(owner, (counts.get(owner) ?? 0) + 1);
  }
  const summary = [...counts].sort(([a], [b]) => a.localeCompare(b, 'en')).map(([owner, count]) => `${owner}: ${count}`).join('; ');
  return [
    '# Current item action baseline', '',
    'Generated by `npm run actions:baseline -- --write`. Review changes; do not regenerate merely to silence drift.', '',
    `Live item variants: ${rows.length} (${summary}).`, '',
    'This records bootstrap content, not the published database head. Numeric paths include non-action fields',
    '(economy, schema, presentation); inclusion does not make a value buffable. See the migration notes on the wiki page [Roadmap/Unified Actions & Repair UI](https://wiki.orchard.dastari.net/Roadmap/Unified%20Actions%20%26%20Repair%20UI).', '',
    '| Item | Current owner | Lifecycle triggers | Numeric authored values |',
    '| --- | --- | --- | --- |',
    ...rows.map(row => `| ${row.id} | ${row.owner} | ${row.triggers.join(', ') || '—'} | ${Object.entries(row.values).map(([key, value]) => `${key}=${value}`).join('; ')} |`), '',
  ].join('\n');
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const output = renderActionBaseline(loadActionBaseline());
  const destination = new URL('../../../docs/action-baseline.md', import.meta.url);
  const args = process.argv.slice(2);
  if (args.length !== 1 || !['--write', '--check'].includes(args[0]!)) {
    throw new Error('Usage: npm run actions:baseline -- --check|--write');
  }
  if (args[0] === '--write') writeFileSync(destination, output);
  else if (readFileSync(destination, 'utf8') !== output) {
    throw new Error('Action baseline drift: inspect content/ownership changes, then run npm run actions:baseline -- --write');
  }
}
