import { readFile, readdir, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import ts from 'typescript';
const directory = new URL('../../ui/src/kit/lab/specimens/', import.meta.url);
/** Source cards are exact authored build bodies, never hand-maintained examples. */
export async function kitLabCodeCards(): Promise<Record<string, string>> {
  const result: Record<string, string> = {};
  for (const filename of (await readdir(directory)).filter(name => name.endsWith('.ts')).sort()) {
    const text = await readFile(new URL(filename, directory), 'utf8');
    const source = ts.createSourceFile(filename, text, ts.ScriptTarget.Latest, true);
    const visit = (node: ts.Node): void => {
      if (ts.isObjectLiteralExpression(node)) {
        const id = node.properties.find(property => ts.isPropertyAssignment(property) && property.name.getText(source) === 'id');
        const build = node.properties.find(property => ts.isMethodDeclaration(property) && property.name.getText(source) === 'build');
        if (id && ts.isPropertyAssignment(id) && ts.isStringLiteral(id.initializer) && build && ts.isMethodDeclaration(build) && build.body) {
          result[id.initializer.text] = build.body.getText(source).slice(1, -1).replace(/^\n|\n\s*$/gu, '');
        }
      }
      ts.forEachChild(node, visit);
    };
    visit(source);
  }
  return result;
}
if (process.argv[1] === fileURLToPath(import.meta.url)) {
  await writeFile(new URL('../../ui/src/kit/lab/source-cards.generated.ts', import.meta.url),
    `/** Generated by kit-lab-code-cards.ts from specimen build bodies. */\nexport const UI_LAB_SOURCE_CARDS: Readonly<Record<string, string>> = ${JSON.stringify(await kitLabCodeCards(), null, 2)};\n`);
}
