/** Reproducible local quote audit, not measured player-income acceptance. */
import {mkdir,readFile,writeFile} from 'node:fs/promises';
import {dirname,resolve} from 'node:path';
import {createHash} from 'node:crypto';
import {bootstrapContentRegistry,villageOrders,villageOrderQuote} from '@orchard/sim';
const root=resolve(import.meta.dirname,'../../..'),registry=bootstrapContentRegistry();
const output=resolve(root,process.argv[2]??'output/doc60/village-order-economy.md');
const costs=[1580n,3200n,4200n];
const counts=(income:bigint)=>costs.map(cost=>((cost+income-1n)/income).toString()).join(' / ');
const rows=villageOrders(registry).flatMap(order=>(registry.items.get(order.item)?.economy.salePremium==='estate_vintage'?[0,1,2,3]:[0]).map(rank=>{
  const quote=villageOrderQuote(registry,order.id,rank);if(!quote)throw new Error('order_unavailable:'+order.id);
  return `| ${order.id}${rank>0?` (vintage ${rank})`:''} | ${quote.quantity} ${quote.itemKind} | ${quote.saleValueBronze} | ${quote.bonusBronze} | ${quote.totalBronze} | ${counts(quote.totalBronze)} | ${counts(quote.bonusBronze)} |`;
}));
const paths=['packages/assets/content/items.json','packages/assets/content/processes.json','packages/assets/content/recipes.json','packages/assets/content/shops.json','packages/sim/src/village-orders.ts','packages/sim/src/homestead-upgrades.ts'];
const hashes=await Promise.all(paths.map(async path=>`- ${path}: ${createHash('sha256').update(await readFile(resolve(root,path))).digest('hex')}`));
const report=`# Village order quote audit\n\nLocal proposed orders; no authority delivery or UI release is implied. Values use the current content registry and existing estate-vintage multipliers.\n\nHousing comparisons use the current 1,580-bronze sample room and 3,200/4,200-bronze expansions, in that order. Gross counts spend the whole delivery payment; bonus-only counts subtract the ordinary sale opportunity cost. Neither is measured elapsed farming income.\n\n| Order | Delivery | Normal sale | Order bonus | Total payment | Gross deliveries: room/east/south | Bonus-only deliveries: room/east/south |\n|---|---|---:|---:|---:|---|---|\n${rows.join('\n')}\n\nThe 350-bronze bonus matches the proposed five/ten/twelve *bonus-only* counts. Actual gross farming payments often fund rooms and expansions faster. One bottle already sells for at least 5,000 bronze without an order, exceeding either single expansion price; vintage rank 3 sells for 40,000. The order bonus does not create that existing mismatch. This does not establish doc60's requested whole-economy pacing. Final housing and bottle-income acceptance remains open.\n\nNone of the seven delivery goods is directly buyable in current content. Quote generation rejects future direct purchase prices. This is only a direct-purchase guard, not a transitive crafting/conversion proof. Purchased apples can already be pressed into must and fermented into bottles using timed processors (6,000 ticks per apple;36,000 ticks per three-must fermentation before vintage scaling). Production time, station investment, crop yields/seasons, merchant stock and player-paced throughput still need measurement before release.\n\nDelivery planning consumes hotbar/active backpack goods on copies, preserves normal sale/vintage value, rejects stale receipt revision/content/quoted total, and checks wallet capacity before exposing a commit plan. Authority admission, a private per-player receipt, sender-derived quotes and the transaction reducer are now wired locally with fake-database tests. The native NPC order list and explicit review/deliver UI are wired locally and covered by flow/input tests. Live rollback/isolation/reconnect, touch journeys and whole-economy acceptance remain unfinished.\n\n## Source hashes\n\n${hashes.join('\n')}\n`;
await mkdir(dirname(output),{recursive:true});await writeFile(output,report);console.log(output);
