import { createHash } from 'node:crypto';
import { constants } from 'node:fs';
import { cp, copyFile, lstat, mkdir, open, readdir, readFile, readlink, realpath, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { keccak_256 } from '@noble/hashes/sha3.js';
import { pathToFileURL } from 'node:url';
import { parseStoredRejoinCredentials } from './world-rejoin-credentials.js';
import { parseContentHeadCandidate, type ContentHeadCandidate } from './content-head-release.js';
import { parseWorldRejoinSnapshot, type WorldRejoinSnapshot } from './world-rejoin-snapshot.js';

const HOST = 'http://127.0.0.1:3000';
const DATABASE = 'orchard-cellar-world';
const DATABASE_IDENTITY = 'c200af6ca3e4663bde9be65c18114d5d296f4b811bf0fa35d3771f8fdba89c21';
const MAX_RESPONSE = 40 * 1024 * 1024;

/** SQL U256 is numeric big endian; SpacetimeDB Hash stores Keccak bytes little endian. */
export function programHashFromSql(value: unknown): string {
  if (typeof value !== 'string' || !/^0x[0-9a-f]{1,64}$/u.test(value)) {
    throw new Error('routine_program_hash_invalid');
  }
  return Buffer.from(value.slice(2).padStart(64, '0'), 'hex').reverse().toString('hex');
}

export function keccak256(bytes: Uint8Array): string {
  return Buffer.from(keccak_256(bytes)).toString('hex');
}

export async function treeManifest(directory: string, excludeBuilds = false): Promise<string> {
  const lines: string[] = [];
  async function visit(relative: string): Promise<void> {
    const path = join(directory, relative);
    const stat = await lstat(path);
    if (stat.isSymbolicLink()) {
      // Existing public asset aliases point within packages; the target files
      // are independently pinned by this same complete source-tree traversal.
      const target = await realpath(path);
      if (!excludeBuilds || !target.startsWith(`${resolve(directory)}/`)
        || target.split('/').some((part) => ['node_modules', 'dist', '.vite', 'coverage', '.git'].includes(part))) {
        throw new Error(`routine_symbolic_link:${relative}`);
      }
      lines.push(`${createHash('sha256').update(`symlink:${await readlink(path)}`).digest('hex')}  ${relative}`);
      return;
    }
    if (stat.isDirectory()) {
      for (const name of (await readdir(path)).sort()) {
        if (excludeBuilds && ['node_modules', 'dist', '.vite', 'coverage', '.git'].includes(name)) continue;
        await visit(relative === '' ? name : `${relative}/${name}`);
      }
    } else if (stat.isFile()) {
      if (/[\n\r\\]/u.test(relative)) throw new Error('routine_unsafe_filename');
      lines.push(`${createHash('sha256').update(await readFile(path)).digest('hex')}  ${relative}`);
    } else throw new Error(`routine_special_file:${relative}`);
  }
  await visit('');
  if (lines.length === 0) throw new Error('routine_empty_artifact');
  return `${lines.join('\n')}\n`;
}

export async function retainStaticAssets(original: string, staged: string): Promise<void> {
  await treeManifest(original);
  await treeManifest(staged);
  async function retain(relative: string): Promise<void> {
    const source = join(original, relative);
    if ((await lstat(source)).isDirectory()) {
      await mkdir(join(staged, relative), { recursive: true });
      for (const name of await readdir(source)) await retain(`${relative}/${name}`);
      return;
    }
    try { await copyFile(source, join(staged, relative), constants.COPYFILE_EXCL); }
    catch (error) {
      if ((error as NodeJS.ErrnoException).code !== 'EEXIST') throw error;
      if (!(await readFile(source)).equals(await readFile(join(staged, relative)))) {
        throw new Error(`routine_immutable_asset_collision:${relative}`, { cause: error });
      }
    }
  }
  await retain('assets');
}

/** Preserve the already reviewed Studio release, pinned before any world build. */
export async function preserveStudioArtifact(original: string, staged: string, manifestFile: string): Promise<void> {
  const expected = await readFile(manifestFile, 'utf8');
  await verifyStatic(original);
  if (await treeManifest(original) !== expected) throw new Error('routine_studio_artifact_changed');
  // Refuse an existing destination, including a dangling symlink.
  await mkdir(staged);
  for (const name of await readdir(original)) {
    await cp(join(original, name), join(staged, name), { recursive: true, force: false, errorOnExist: true });
  }
  if (await treeManifest(staged) !== expected || await treeManifest(original) !== expected) {
    throw new Error('routine_studio_artifact_changed');
  }
  await verifyStatic(staged);
}

export async function assertSameSchema(deployed: string, candidate: string): Promise<void> {
  const before = await treeManifest(deployed);
  const after = await treeManifest(candidate);
  if (!(await readFile(join(deployed, 'index.ts'), 'utf8')).includes('AUTOMATICALLY GENERATED BY SPACETIMEDB')) {
    throw new Error('routine_not_generated_schema');
  }
  // Compare every generated byte, including private tables, indexes, reducers,
  // views and serialization types. There is no "compatible enough" allowance.
  if (before !== after) throw new Error('routine_schema_changed_use_full_migration_release');
}

export async function verifyStatic(directory: string, origin?: string): Promise<void> {
  await treeManifest(directory);
  const html = await readFile(join(directory, 'index.html'), 'utf8');
  if (/\/@vite\/client|\/@fs\/|["']\/src\//u.test(html)) throw new Error('routine_static_contains_dev_entry');
  const entries = [...html.matchAll(/["'](\/assets\/[^"'\s]+\.(?:js|css))["']/gu)].map((match) => match[1]!);
  if (!entries.some((entry) => entry.endsWith('.js'))) throw new Error('routine_static_entry_missing');
  const seen = new Set<string>();
  async function visit(path: string): Promise<void> {
    if (seen.has(path)) return;
    seen.add(path);
    if (!path.startsWith(`${resolve(directory)}/`)) throw new Error('routine_static_path_escape');
    const bytes = await readFile(path);
    if (origin !== undefined) {
      const url = `${origin}/${path.slice(resolve(directory).length + 1)}`;
      const response = await fetch(url, { signal: AbortSignal.timeout(20_000) });
      if (!response.ok || !Buffer.from(await response.arrayBuffer()).equals(bytes)) {
        throw new Error('routine_served_chunk_mismatch');
      }
    }
    if (!path.endsWith('.js')) return;
    // Vite's static imports, dynamic import URLs and preload dependency arrays
    // all use quoted relative asset paths. Verify the complete reachable graph.
    for (const match of bytes.toString('utf8').matchAll(/["']((?:\.\.?\/|\/?assets\/)[^"'\s]+\.(?:js|css))["']/gu)) {
      const target = match[1]!;
      await visit(target.startsWith('/') ? resolve(directory, `.${target}`)
        : target.startsWith('assets/') ? resolve(directory, target) : resolve(dirname(path), target));
    }
  }
  for (const entry of entries) await visit(resolve(directory, `.${entry}`));
}

export function expectedContentSnapshot(
  snapshot: WorldRejoinSnapshot, candidate: ContentHeadCandidate, ownerLabel: string,
): WorldRejoinSnapshot {
  if (snapshot.database !== candidate.database || candidate.deletes.length !== 0) {
    throw new Error('routine_snapshot_candidate_mismatch');
  }
  const owner = snapshot.identities.find((entry) => entry.label === ownerLabel);
  if (owner === undefined) throw new Error('routine_snapshot_owner_missing');
  return {
    ...snapshot,
    identities: snapshot.identities.map((entry) => {
      const rows = entry.tables['contentHead'];
      if (rows?.length !== 1) throw new Error('routine_snapshot_head_missing');
      const head = rows[0] as Record<string, unknown>;
      const expected = candidate.expectedHead;
      for (const key of ['packId', 'contentHash', 'definitionCount', 'engineVersion', 'clientMutationId'] as const) {
        if (head[key] !== expected[key]) throw new Error(`routine_snapshot_head_changed:${key}`);
      }
      if (JSON.stringify(head['revision']) !== JSON.stringify({ $bigint: expected.revision })) {
        throw new Error('routine_snapshot_head_changed:revision');
      }
      if (candidate.upserts.length === 0) return entry;
      // Quotes project the current registry hash; their prices, quantities and
      // receipt revisions still have to match exactly across publication.
      const orders = entry.tables['ownVillageOrders']?.map((row) => {
        if (typeof row !== 'object' || row === null || Array.isArray(row)
          || !('contentHash' in row) || row.contentHash !== expected.contentHash) {
          throw new Error('routine_snapshot_order_hash_changed');
        }
        return { ...row, contentHash: candidate.resultingHead.contentHash };
      });
      return {
        ...entry,
        tables: {
          ...entry.tables,
          ...(orders === undefined ? {} : { ownVillageOrders: orders }),
          contentHead: [{
            ...head,
            ...candidate.resultingHead,
            revision: { $bigint: candidate.resultingHead.revision },
            clientMutationId: candidate.clientMutationId,
            updatedBy: { $identity: owner.identity },
          }],
        },
      };
    }),
  };
}

async function boundedJson(response: Response): Promise<unknown> {
  if (!response.ok || response.body === null) throw new Error(`routine_http_failed:${response.status}`);
  const chunks: Uint8Array[] = [];
  let length = 0;
  for await (const chunk of response.body) {
    length += chunk.length;
    if (length > MAX_RESPONSE) throw new Error('routine_response_too_large');
    chunks.push(chunk);
  }
  return JSON.parse(Buffer.concat(chunks).toString('utf8')) as unknown;
}

async function liveProgram(output?: string): Promise<{ identity: string; programHash: string }> {
  const tokenPath = process.env['WORLD_REJOIN_TOKENS_FILE'];
  const label = process.env['WORLD_RELEASE_CONTENT_OWNER_LABEL'];
  if (tokenPath === undefined || !tokenPath.startsWith('/')) throw new Error('routine_credentials_required');
  const handle = await open(tokenPath, constants.O_RDONLY | constants.O_NOFOLLOW);
  let token: string | undefined;
  try {
    const stat = await handle.stat();
    if (!stat.isFile() || (stat.mode & 0o777) !== 0o600) throw new Error('routine_credential_permissions');
    token = parseStoredRejoinCredentials(JSON.parse(await handle.readFile('utf8')) as unknown)
      .find((entry) => entry.label === label)?.token;
  } finally { await handle.close(); }
  if (token === undefined) throw new Error('routine_owner_credential_missing');
  const metadata = await boundedJson(await fetch(`${HOST}/v1/database/${DATABASE}`, {
    signal: AbortSignal.timeout(30_000),
  })) as { database_identity?: { __identity__?: string }; host_type?: { Js?: unknown } };
  const identity = metadata.database_identity?.__identity__?.replace(/^0x/u, '');
  if (identity !== DATABASE_IDENTITY || metadata.host_type?.Js === undefined) {
    throw new Error('routine_existing_javascript_database_required');
  }
  // initial_program in database metadata is the creation program, not the live
  // program. Read the current hash and bytes in one read-only system-table row.
  const result = await boundedJson(await fetch(`${HOST}/v1/database/${DATABASE}/sql`, {
    method: 'POST', headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'text/plain' },
    body: output === undefined ? 'SELECT program_hash FROM st_module' : 'SELECT program_hash, program_bytes FROM st_module',
    signal: AbortSignal.timeout(30_000),
  })) as { rows?: unknown[][] }[];
  if (!Array.isArray(result) || result.length !== 1 || result[0]?.rows?.length !== 1) {
    throw new Error('routine_live_module_row_required');
  }
  const row = result[0].rows[0]!;
  const programHash = programHashFromSql(row[0]);
  if (output !== undefined) {
    const encoded = row[1];
    if (typeof encoded !== 'string' || encoded.length === 0 || encoded.length % 2 !== 0 || /[^0-9a-f]/u.test(encoded)) {
      throw new Error('routine_live_program_bytes_invalid');
    }
    const bytes = Buffer.from(encoded, 'hex');
    if (keccak256(bytes) !== programHash) throw new Error('routine_live_program_hash_mismatch');
    await writeFile(output, bytes, { flag: 'wx', mode: 0o600 });
  }
  return { identity, programHash };
}

async function main(): Promise<void> {
  const [mode, first, second, third] = process.argv.slice(2);
  if (mode === 'live-program') {
    process.stdout.write(`${JSON.stringify(await liveProgram(first))}\n`);
  } else if (mode === 'same-schema' && first !== undefined && second !== undefined) {
    await assertSameSchema(first, second);
  } else if (mode === 'manifest' && first !== undefined) {
    process.stdout.write(await treeManifest(first, second === 'source'));
  } else if (mode === 'keccak' && first !== undefined) {
    process.stdout.write(`${keccak256(await readFile(first))}\n`);
  } else if (mode === 'static' && first !== undefined) {
    await verifyStatic(first, second);
  } else if (mode === 'retain-assets' && first !== undefined && second !== undefined) {
    await retainStaticAssets(first, second);
  } else if (mode === 'preserve-studio' && first !== undefined && second !== undefined && third !== undefined) {
    await preserveStudioArtifact(first, second, third);
  } else if (mode === 'expected-snapshot' && first !== undefined && second !== undefined && third !== undefined) {
    const snapshot = parseWorldRejoinSnapshot(JSON.parse(await readFile(first, 'utf8')) as unknown);
    const candidate = parseContentHeadCandidate(JSON.parse(await readFile(second, 'utf8')) as unknown);
    const expected = expectedContentSnapshot(snapshot, candidate, process.env['WORLD_RELEASE_CONTENT_OWNER_LABEL'] ?? '');
    await writeFile(third, `${JSON.stringify(expected, null, 2)}\n`, { flag: 'wx', mode: 0o600 });
  } else throw new Error('routine_helper_usage');
}

if (process.argv[1] !== undefined && import.meta.url === pathToFileURL(resolve(process.argv[1])).href) await main();
