import { mkdtemp, mkdir, readFile, rm, symlink, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { spawnSync } from 'node:child_process';
import { afterEach, describe, expect, it } from 'vitest';
import { assertSameSchema, expectedContentSnapshot, keccak256, programHashFromSql, retainStaticAssets, treeManifest, verifyStatic } from './world-release-routine.js';
import type { ContentHeadCandidate } from './content-head-release.js';
import { WORLD_REJOIN_EXCLUSIONS, type WorldRejoinSnapshot } from './world-rejoin-snapshot.js';

const directories: string[] = [];
async function temporary(): Promise<string> {
  const directory = await mkdtemp(join(tmpdir(), 'orchard-routine-test-'));
  directories.push(directory); return directory;
}
afterEach(async () => { await Promise.all(directories.splice(0).map((path) => rm(path, { recursive: true, force: true }))); });

describe('routine same-schema release', () => {
  it('interprets the SQL U256 hash as little endian Keccak bytes and rejects malformed hashes', () => {
    expect(programHashFromSql('0x01')).toBe(`01${'00'.repeat(31)}`);
    expect(programHashFromSql('0x232870958a14e161dc86e59007f7f9f942c85ad19fe8205bc970193c1d82dbd1'))
      .toBe('d1db821d3c1970c95b20e89fd15ac842f9f9f70790e586dc61e1148a95702823');
    expect(() => programHashFromSql('../program')).toThrow('routine_program_hash_invalid');
    expect(keccak256(Buffer.alloc(0))).toBe('c5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470');
  });

  it('rejects private schema, index, visibility and reducer changes without ignoring generated files', async () => {
    const root = await temporary(); const before = join(root, 'before'); const after = join(root, 'after');
    await mkdir(before); await mkdir(after);
    const generated = '// AUTOMATICALLY GENERATED BY SPACETIMEDB\n';
    for (const dir of [before, after]) {
      await writeFile(join(dir, 'index.ts'), generated);
      await writeFile(join(dir, 'private_escrow_table.ts'), 'private owner:index identity; quantity:u32;');
    }
    await expect(assertSameSchema(before, after)).resolves.toBeUndefined();
    for (const changed of ['public owner:index identity; quantity:u32;', 'private owner:identity; quantity:u32;', 'private owner:index identity; quantity:u16;']) {
      await writeFile(join(after, 'private_escrow_table.ts'), changed);
      await expect(assertSameSchema(before, after)).rejects.toThrow('routine_schema_changed');
    }
    await writeFile(join(after, 'private_escrow_table.ts'), 'private owner:index identity; quantity:u32;');
    await writeFile(join(after, 'new_reducer.ts'), 'quantity:u16');
    await expect(assertSameSchema(before, after)).rejects.toThrow('routine_schema_changed');
  });

  it('refuses symlinks and detects missing lazy chunks before static installation', async () => {
    const root = await temporary(); await mkdir(join(root, 'assets'));
    await writeFile(join(root, 'index.html'), '<script type="module" src="/assets/main-123.js"></script>');
    await writeFile(join(root, 'assets/main-123.js'), 'import("./lazy-123.js")');
    await expect(verifyStatic(root)).rejects.toThrow();
    await writeFile(join(root, 'assets/lazy-123.js'), 'export const ready=true;');
    await expect(verifyStatic(root)).resolves.toBeUndefined();
    await writeFile(join(root, 'index.html'), '<script src="/assets/main-123.js"></script><link href="/assets/style-123.css">');
    await expect(verifyStatic(root)).rejects.toThrow();
    await writeFile(join(root, 'assets/style-123.css'), 'body{color:red}');
    await writeFile(join(root, 'assets/main-123.js'), 'const preload=["assets/preload-123.css"];');
    await expect(verifyStatic(root)).rejects.toThrow();
    await writeFile(join(root, 'assets/preload-123.css'), 'body{color:blue}');
    await expect(verifyStatic(root)).resolves.toBeUndefined();
    await symlink(join(root, 'index.html'), join(root, 'linked'));
    await expect(treeManifest(root)).rejects.toThrow('routine_symbolic_link');
  });

  it('changes only the reviewed content head in expected parity, never player or pending cooking rows', () => {
    const head = { packId: 'live', revision: '2', contentHash: 'old', definitionCount: 484, engineVersion: 1, clientMutationId: 'prior' } as const;
    const candidate = { database: 'orchard-cellar-world', expectedHead: head, resultingHead: { revision: '3', contentHash: 'new', definitionCount: 484, engineVersion: 1 }, clientMutationId: 'approved', upserts: [{ id: 'object:workbench' }], deletes: [] } as unknown as ContentHeadCandidate;
    const snapshot: WorldRejoinSnapshot = {
      formatVersion: 2, database: candidate.database, capturedAt: '2026-09-05T00:00:00Z', exclusions: WORLD_REJOIN_EXCLUSIONS,
      identities: [{ label: 'owner', identity: 'owner-id', tables: {
        contentHead: [{ ...head, revision: { $bigint: '2' }, updatedBy: { $identity: 'prior-owner' } }],
        ownCookingJob: [{ quantity: 12, readyTick: { $bigint: '999' } }], ownInventorySlot: [{ quantity: 500 }],
      } }],
    };
    const after = expectedContentSnapshot(snapshot, candidate, 'owner');
    expect(after.identities[0]!.tables['ownCookingJob']).toBe(snapshot.identities[0]!.tables['ownCookingJob']);
    expect(after.identities[0]!.tables['ownInventorySlot']).toBe(snapshot.identities[0]!.tables['ownInventorySlot']);
    expect(after.identities[0]!.tables['contentHead']).toEqual([{ ...head, ...candidate.resultingHead, revision: { $bigint: '3' }, clientMutationId: 'approved', updatedBy: { $identity: 'owner-id' } }]);
    expect(snapshot.identities[0]!.tables['contentHead']![0]).toMatchObject({ contentHash: 'old' });
    expect(() => expectedContentSnapshot(snapshot, { ...candidate, expectedHead: { ...head, contentHash: 'drift' } }, 'owner')).toThrow('routine_snapshot_head_changed');
  });

  it('retains cached immutable chunks but refuses different bytes under the same URL', async () => {
    const root = await temporary(); const old = join(root, 'old'); const staged = join(root, 'staged');
    await mkdir(join(old, 'assets'), { recursive: true }); await mkdir(join(staged, 'assets'), { recursive: true });
    await writeFile(join(old, 'assets/old-hash.js'), 'old chunk');
    await writeFile(join(staged, 'assets/new-hash.js'), 'new chunk');
    await retainStaticAssets(old, staged);
    expect(await readFile(join(staged, 'assets/old-hash.js'), 'utf8')).toBe('old chunk');
    await writeFile(join(staged, 'assets/old-hash.js'), 'different bytes');
    await expect(retainStaticAssets(old, staged)).rejects.toThrow('routine_immutable_asset_collision');
  });

  it('orders schema, source, live identity/CAS, rollback and parity gates around a single no-delete publish', async () => {
    const source = await readFile(new URL('./world-release-routine.sh', import.meta.url), 'utf8');
    expect(spawnSync('bash', ['-n', 'scripts/world-release-routine.sh']).status).toBe(0);
    expect(source).toContain('npx vitest run');
    expect(source).not.toMatch(/npm test|--coverage|backup-world\.sh|world:chest-migrate|restore-world-rehearsal\.sh/u);
    const schema = source.indexOf('same-schema "$evidence/schema-before"');
    const stop = source.indexOf('traffic_stopped=true');
    const publish = source.indexOf('spacetime publish "$database"');
    const apply = source.indexOf('world:content-head -- apply');
    const parity = source.indexOf('world:rejoin-smoke -- verify');
    const swap = source.indexOf('mv "$evidence/staged/packages/$app/dist"');
    expect(schema).toBeGreaterThan(0); expect(schema).toBeLessThan(stop);
    expect(source.indexOf('--outDir "$evidence/staged/packages/studio/dist"')).toBeLessThan(stop);
    expect(stop).toBeLessThan(publish); expect(publish).toBeLessThan(apply);
    expect(apply).toBeLessThan(parity); expect(parity).toBeLessThan(swap);
    expect(source).toContain('--delete-data=never --yes=remote,migrate --no-config');
    expect(source).toContain('cmp "$evidence/live-program-before.json" "$evidence/live-program-final-cas.json"');
    expect(source).toContain('published=true\nspacetime publish');
    expect(source).toContain('publication-started-review-required');
  });
});
