/**
 * Node side of the chunk asset dependencies. The resolver is browser-safe and lives with Studio
 * (packages/studio/src/world-chunks/assets.ts, static world S7b) over a generated inventory; this
 * module scans the art loader source for that inventory and writes it (`--write`).
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import ts from 'typescript';
import type { ChunkAssetInventory } from '../packages/studio/src/world-chunks/assets.js';

export { CHUNK_ASSET_INVENTORY, chunkDecorationAssetIds, chunkResourceAssetIds, chunkTerrainAssetIds, type ChunkAssetInventory } from '../packages/studio/src/world-chunks/assets.js';

export const CHUNK_ASSET_INVENTORY_PATH = new URL('../packages/studio/src/world-chunks/asset-inventory.ts', import.meta.url);

/** The inventory as the art loader source defines it today. Fails closed when its shape changes. */
export function scanChunkAssetInventory(sourceText = readFileSync(new URL('../packages/engine/src/overworld-art.ts', import.meta.url), 'utf8')): ChunkAssetInventory {
  const artSource = ts.createSourceFile('overworld-art.ts', sourceText, ts.ScriptTarget.Latest, true);
  const terrain = new Set<string>();
  const visitTerrain = (node: ts.Node): void => {
    if (ts.isStringLiteral(node) && node.text.startsWith('tile_cf_')) terrain.add(node.text);
    ts.forEachChild(node, visitTerrain);
  };
  visitTerrain(artSource);
  const banks = artSource.statements.find(node => ts.isVariableStatement(node)
    && node.declarationList.declarations.some(declaration => ts.isIdentifier(declaration.name) && declaration.name.text === 'NATURE_DECORATION_BANKS'));
  if (!banks) throw new Error('Nature asset banks changed; review chunk dependencies');
  const natureFamilies: Record<string, readonly [string, number]> = {};
  const visitBanks = (node: ts.Node): void => {
    if (ts.isArrayLiteralExpression(node) && node.elements.length === 3) {
      const [kind, name, count] = node.elements;
      if (kind && name && count && ts.isStringLiteral(kind) && ts.isStringLiteral(name) && ts.isNumericLiteral(count)) natureFamilies[kind.text] = [name.text, Number(count.text)];
    }
    ts.forEachChild(node, visitBanks);
  };
  visitBanks(banks);
  if (Object.keys(natureFamilies).length === 0) throw new Error('Nature asset families unavailable');
  const names = new Map<string, string>();
  const visitNames = (node: ts.Node): void => {
    if (ts.isPropertyAssignment(node) && ts.isIdentifier(node.name) && ts.isStringLiteral(node.initializer)) names.set(node.name.text, node.initializer.text);
    ts.forEachChild(node, visitNames);
  };
  const named = artSource.statements.find(node => ts.isVariableStatement(node) && node.declarationList.declarations.some(declaration => declaration.name.getText(artSource) === 'MAP_EDITOR_ASSET_NAMES'));
  if (!named) throw new Error('Map art asset inventory changed');
  visitNames(named);
  const fn = artSource.statements.find(node => ts.isFunctionDeclaration(node) && node.name?.text === 'authoredResourceAsset');
  if (!fn) throw new Error('Resource asset resolver changed');
  const resourceAliases: Record<string, string> = {};
  const cases = (node: ts.Node): void => {
    if (ts.isCaseClause(node) && ts.isStringLiteral(node.expression)) {
      const ret = node.statements.find(ts.isReturnStatement);
      if (ret?.expression && ts.isPropertyAccessExpression(ret.expression)) {
        const asset = names.get(ret.expression.name.text);
        if (asset) resourceAliases[node.expression.text] = asset;
      }
    }
    ts.forEachChild(node, cases);
  };
  cases(fn);
  return { terrain: [...terrain].sort(), natureFamilies, resourceAliases };
}

/** The generated module text (`asset-inventory.ts`). */
export function chunkAssetInventorySource(inventory: ChunkAssetInventory = scanChunkAssetInventory()): string {
  return `// Generated by \`npm run world:chunks:asset-inventory\` from packages/engine/src/overworld-art.ts. Do not edit.
import type { ChunkAssetInventory } from './assets.js';

export const CHUNK_ASSET_INVENTORY_DATA: ChunkAssetInventory = ${JSON.stringify(inventory, null, 2)};
`;
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url) && process.argv.includes('--write')) {
  writeFileSync(CHUNK_ASSET_INVENTORY_PATH, chunkAssetInventorySource());
  console.info(`Wrote ${fileURLToPath(CHUNK_ASSET_INVENTORY_PATH)}`);
}
