// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all procedure arg schemas
import * as AdminAuditPageProcedure from "../admin_audit_page_procedure";
import * as AdminChestMigrationStatusProcedure from "../admin_chest_migration_status_procedure";
import * as AdminClientErrorsProcedure from "../admin_client_errors_procedure";
import * as AdminConnectionsPageProcedure from "../admin_connections_page_procedure";
import * as AdminContainerContentsProcedure from "../admin_container_contents_procedure";
import * as AdminEntitiesInAreaProcedure from "../admin_entities_in_area_procedure";
import * as AdminEntitiesInAreaPageProcedure from "../admin_entities_in_area_page_procedure";
import * as AdminFindPlayersProcedure from "../admin_find_players_procedure";
import * as AdminHomesteadProcedure from "../admin_homestead_procedure";
import * as AdminLegacyFarmRetirementStatusProcedure from "../admin_legacy_farm_retirement_status_procedure";
import * as AdminMissingContainerRecoveryProcedure from "../admin_missing_container_recovery_procedure";
import * as AdminPlayerInventoryProcedure from "../admin_player_inventory_procedure";
import * as AdminPlayerMutationResultProcedure from "../admin_player_mutation_result_procedure";
import * as AdminPlayerSnapshotProcedure from "../admin_player_snapshot_procedure";
import * as AdminSpaceRegistryProcedure from "../admin_space_registry_procedure";
import * as AdminStudioMembersProcedure from "../admin_studio_members_procedure";
import * as AdminStudioScopesProcedure from "../admin_studio_scopes_procedure";
import * as AdminTelemetryProcedure from "../admin_telemetry_procedure";
import * as AdminValidateWorldProcedure from "../admin_validate_world_procedure";
import * as PreviewStudioScopeProcedure from "../preview_studio_scope_procedure";
import * as StudioScopeReceiptProcedure from "../studio_scope_receipt_procedure";
import * as StudioScriptReviewProcedure from "../studio_script_review_procedure";

export type AdminAuditPageArgs = __Infer<typeof AdminAuditPageProcedure.params>;
export type AdminAuditPageResult = __Infer<typeof AdminAuditPageProcedure.returnType>;
export type AdminChestMigrationStatusArgs = __Infer<typeof AdminChestMigrationStatusProcedure.params>;
export type AdminChestMigrationStatusResult = __Infer<typeof AdminChestMigrationStatusProcedure.returnType>;
export type AdminClientErrorsArgs = __Infer<typeof AdminClientErrorsProcedure.params>;
export type AdminClientErrorsResult = __Infer<typeof AdminClientErrorsProcedure.returnType>;
export type AdminConnectionsPageArgs = __Infer<typeof AdminConnectionsPageProcedure.params>;
export type AdminConnectionsPageResult = __Infer<typeof AdminConnectionsPageProcedure.returnType>;
export type AdminContainerContentsArgs = __Infer<typeof AdminContainerContentsProcedure.params>;
export type AdminContainerContentsResult = __Infer<typeof AdminContainerContentsProcedure.returnType>;
export type AdminEntitiesInAreaArgs = __Infer<typeof AdminEntitiesInAreaProcedure.params>;
export type AdminEntitiesInAreaResult = __Infer<typeof AdminEntitiesInAreaProcedure.returnType>;
export type AdminEntitiesInAreaPageArgs = __Infer<typeof AdminEntitiesInAreaPageProcedure.params>;
export type AdminEntitiesInAreaPageResult = __Infer<typeof AdminEntitiesInAreaPageProcedure.returnType>;
export type AdminFindPlayersArgs = __Infer<typeof AdminFindPlayersProcedure.params>;
export type AdminFindPlayersResult = __Infer<typeof AdminFindPlayersProcedure.returnType>;
export type AdminHomesteadArgs = __Infer<typeof AdminHomesteadProcedure.params>;
export type AdminHomesteadResult = __Infer<typeof AdminHomesteadProcedure.returnType>;
export type AdminLegacyFarmRetirementStatusArgs = __Infer<typeof AdminLegacyFarmRetirementStatusProcedure.params>;
export type AdminLegacyFarmRetirementStatusResult = __Infer<typeof AdminLegacyFarmRetirementStatusProcedure.returnType>;
export type AdminMissingContainerRecoveryArgs = __Infer<typeof AdminMissingContainerRecoveryProcedure.params>;
export type AdminMissingContainerRecoveryResult = __Infer<typeof AdminMissingContainerRecoveryProcedure.returnType>;
export type AdminPlayerInventoryArgs = __Infer<typeof AdminPlayerInventoryProcedure.params>;
export type AdminPlayerInventoryResult = __Infer<typeof AdminPlayerInventoryProcedure.returnType>;
export type AdminPlayerMutationResultArgs = __Infer<typeof AdminPlayerMutationResultProcedure.params>;
export type AdminPlayerMutationResultResult = __Infer<typeof AdminPlayerMutationResultProcedure.returnType>;
export type AdminPlayerSnapshotArgs = __Infer<typeof AdminPlayerSnapshotProcedure.params>;
export type AdminPlayerSnapshotResult = __Infer<typeof AdminPlayerSnapshotProcedure.returnType>;
export type AdminSpaceRegistryArgs = __Infer<typeof AdminSpaceRegistryProcedure.params>;
export type AdminSpaceRegistryResult = __Infer<typeof AdminSpaceRegistryProcedure.returnType>;
export type AdminStudioMembersArgs = __Infer<typeof AdminStudioMembersProcedure.params>;
export type AdminStudioMembersResult = __Infer<typeof AdminStudioMembersProcedure.returnType>;
export type AdminStudioScopesArgs = __Infer<typeof AdminStudioScopesProcedure.params>;
export type AdminStudioScopesResult = __Infer<typeof AdminStudioScopesProcedure.returnType>;
export type AdminTelemetryArgs = __Infer<typeof AdminTelemetryProcedure.params>;
export type AdminTelemetryResult = __Infer<typeof AdminTelemetryProcedure.returnType>;
export type AdminValidateWorldArgs = __Infer<typeof AdminValidateWorldProcedure.params>;
export type AdminValidateWorldResult = __Infer<typeof AdminValidateWorldProcedure.returnType>;
export type PreviewStudioScopeArgs = __Infer<typeof PreviewStudioScopeProcedure.params>;
export type PreviewStudioScopeResult = __Infer<typeof PreviewStudioScopeProcedure.returnType>;
export type StudioScopeReceiptArgs = __Infer<typeof StudioScopeReceiptProcedure.params>;
export type StudioScopeReceiptResult = __Infer<typeof StudioScopeReceiptProcedure.returnType>;
export type StudioScriptReviewArgs = __Infer<typeof StudioScriptReviewProcedure.params>;
export type StudioScriptReviewResult = __Infer<typeof StudioScriptReviewProcedure.returnType>;

