import {
  BASE_TYPES, LEGENDARIES, LINEAGES, MATERIALS_BY_LINE, PREFIXES, RARITIES, STATS, SUFFIXES, TIER_LEVEL,
  affixValue, baseType, rarity, type Affix, type BaseType,
} from './catalogue.js';
import type { IconLibrary } from './icons.js';
import type { Item } from './items.js';

const table = (header: readonly string[], rows: readonly (readonly (string | number)[])[]): string => [
  `| ${header.join(' | ')} |`,
  `| ${header.map(() => '---').join(' | ')} |`,
  ...rows.map((row) => `| ${row.join(' | ')} |`),
].join('\n');

const suits = (affix: Affix, base: BaseType): boolean => affix.suits.length === 0 || affix.suits.includes(base.group);

function visualLabel(base: BaseType): string {
  const visual = base.visual;
  switch (visual.kind) {
    case 'head': return `helmet: ${[...new Set([visual.fallback, ...Object.values(visual.families)])].join(' → ')}`;
    case 'garment': return `${visual.family} layer${visual.pauldronsFrom ? ` + pauldrons from ${visual.pauldronsFrom}` : ''}`;
    case 'gauntlets': return 'hands layer recoloured';
    case 'feet': return visual.style === 'shoes' ? 'shoe pixels recoloured' : `shoe pixels + ankle recoloured (${visual.style})`;
    case 'cape': return 'cape layer (behind / over the back by facing)';
    case 'held': return `held ${visual.held}`;
    case 'none': return `_${visual.reason}_`;
  }
}

function combinations(base: BaseType): number {
  const materials = MATERIALS_BY_LINE.filter((entry) => base.lines.includes(entry.line)).length;
  const prefixes = PREFIXES.filter((affix) => suits(affix, base)).length;
  const suffixes = SUFFIXES.filter((affix) => suits(affix, base)).length;
  const uncommon = PREFIXES.filter((affix) => suits(affix, base) && affix.from === 'uncommon').length
    + SUFFIXES.filter((affix) => suits(affix, base) && affix.from === 'uncommon').length;
  // poor + common + uncommon single affixes + rare prefix×suffix pairs, per material; plus epic lineages.
  return materials * (2 + uncommon + prefixes * suffixes) + LINEAGES.length;
}

export function catalogueMarkdown(library: IconLibrary, examples: readonly Item[]): string {
  const out: string[] = [];
  out.push('# Gear catalogue (design draft)', '');
  out.push('Generated by `npm run render:gear-catalogue -w @orchard/tools` from `packages/tools/src/gear-rig/catalogue.ts`. The same data drives names, tooltips, icons, paper-doll visuals and sell values.', '');

  out.push('## Naming grammar', '');
  out.push(table(['Rarity', 'Name pattern', 'Example'], [
    ['Poor', '{Damage} {Material} {Base}', 'Rusted Iron Arming Sword'],
    ['Common', '{Material} {Base}', 'Bronze Arming Sword'],
    ['Uncommon', '{Prefix} {Material} {Base} or {Material} {Base} {Suffix}', 'Steel Longsword of Fortitude'],
    ['Rare', '{Prefix} {Base} {Suffix} (material shown in the tooltip)', 'Radiant Bulwark of the Ages'],
    ['Epic', '{Lineage} {Base}', 'Dawnsworn Greathelm'],
    ['Legendary', 'unique name', 'The Bonecrippler'],
  ]), '');
  out.push('Prefixes grant a primary attribute or headline power (white lines). Suffixes grant a secondary stat, regeneration or a skill rank (green `Equip:` lines). Several items may share one icon or worn family; material, trim and rarity ornaments make them distinct.', '');

  out.push('## Rarities', '');
  out.push(table(['Rarity', 'Colour', 'Affixes', 'Affix power', 'Sell ×', 'Look'], RARITIES.map((entry) => [
    entry.name, `\`${entry.color}\``, entry.affixes, entry.power, entry.price, entry.look,
  ])), '');

  out.push('## Material ladders', '');
  out.push(table(['Material', 'Line', 'Tier', 'Requires level', 'Palette', 'Note'], MATERIALS_BY_LINE.map((entry) => [
    entry.name, entry.line, entry.tier, TIER_LEVEL[entry.tier] ?? 1, entry.palette + (entry.cloth ? ` / ${entry.cloth} cloth` : ''), entry.note ?? '',
  ])), '');

  out.push('## Base types', '');
  const groups = [...new Set(BASE_TYPES.map((base) => `${base.slot}|${base.group}`))];
  const rows: (string | number)[][] = [];
  for (const key of groups) {
    for (const base of BASE_TYPES.filter((entry) => `${entry.slot}|${entry.group}` === key)) {
      const iconRows = base.icon.rows.length
        ? `${base.icon.sheet} ${base.icon.rows.length} rows (${Math.min(...base.icon.rows)}–${Math.max(...base.icon.rows)})${base.icon.staff ? ', gem head' : ''}`
        : 'painted from worn design';
      rows.push([base.name, base.slot.replace('_', ' '), base.group, base.armourClass ?? '—', base.lines.join(', '), iconRows, visualLabel(base), combinations(base)]);
    }
  }
  out.push(table(['Base', 'Slot', 'Group', 'Class', 'Materials', 'Icon family', 'Paper doll', 'Distinct items'], rows), '');
  const total = BASE_TYPES.reduce((sum, base) => sum + combinations(base), 0) + LEGENDARIES.length;
  out.push(`**${BASE_TYPES.length} base types → ${total.toLocaleString('en-GB')} distinct generated items** (poor, common, every allowed single affix, every allowed prefix × suffix pair, per material, plus one epic per lineage and base, plus ${LEGENDARIES.length} legendaries). Content can publish any subset.`, '');

  const statCell = (statId: string): string => {
    const stat = STATS[statId]!;
    return `${stat.label}${stat.needsBudget ? ' \\*' : ''}`;
  };
  const magnitude = (statId: string): string => {
    const stat = STATS[statId]!;
    if (stat.unit === 'rank') return '+1 rank';
    const suffix = stat.unit === 'percent' ? '%' : stat.unit === 'perSecond' ? '/s' : '';
    return [1, 4, 7].map((tier) => `${affixValue(stat, tier, rarity('rare').power)}${suffix}`).join(' / ');
  };
  out.push('## Prefixes', '');
  out.push(table(['Prefix', 'Grants', 'Rare at tier 1 / 4 / 7', 'From', 'Suits'], PREFIXES.map((affix) => [
    affix.name, statCell(affix.stat), magnitude(affix.stat), affix.from, affix.suits.join(', ') || 'any',
  ])), '');
  out.push('## Suffixes', '');
  out.push(table(['Suffix', 'Grants', 'Rare at tier 1 / 4 / 7', 'From', 'Suits'], SUFFIXES.map((affix) => [
    affix.name, statCell(affix.stat), magnitude(affix.stat), affix.from, affix.suits.join(', ') || 'any',
  ])), '');
  out.push('\\* Needs `EQUIPMENT_STAT_BUDGETS` extended (attributes, mana and regeneration are not equipment-budgeted today). Skill ranks follow the existing rare-or-better, four-rank loadout rule.', '');

  out.push('## Epic lineages', '');
  out.push(table(['Lineage', 'Theme', 'Attributes', 'Equip', 'Palette / trim / ornament', 'Helm'], LINEAGES.map((entry) => [
    entry.name, entry.theme, entry.stats.map((stat) => STATS[stat]!.label).join(', '), STATS[entry.equip]!.label,
    `${entry.palette} / ${entry.accent} / ${entry.detail}`, entry.head,
  ])), '');

  out.push('## Legendary uniques', '');
  out.push(table(['Name', 'Base', 'Stats', 'Signature', 'Flavour'], LEGENDARIES.map((entry) => [
    `**${entry.name}**`, baseType(entry.base).name, entry.stats.map(([stat, value]) => `+${value} ${STATS[stat]!.label}`).join(', '),
    entry.signature, `_"${entry.flavour}"_`,
  ])), '');

  out.push('## Sample items in the renders', '');
  out.push(table(['Name', 'Rarity', 'Base', 'Material', 'Sell (bronze)'], examples.map((item) => [
    item.name, item.rarity, item.base.name, item.material.name, item.sellBronze,
  ])), '');

  out.push('## Open decisions', '');
  out.push('- **Authored combinations or rolled affixes?** Item stacks carry no per-copy data today. Either publish chosen combinations as distinct item ids (fits the current schema and trading), or add per-item affix storage for random rolls.');
  out.push('- **Attributes on gear.** Extend `EQUIPMENT_STAT_BUDGETS` to the six attributes, mana and regeneration, and show attributes to players.');
  out.push('- **Two-hand vs shield.** Staffs, polearms, warhammers and bows are listed as two-handed; decide whether the off-hand stays empty.');
  out.push('- **Missing worn art.** Caps and kettle hats need worn head designs; their icons already exist.');
  out.push(`- **Icon choice.** Each base ranks its icon rows by measured ornateness (accent pixels × 3 + area ÷ 4); rarer items take the more ornate rows. ${library.rows('weapons')} weapon rows and ${library.rows('armor')} armour rows are available.`);
  return `${out.join('\n')}\n`;
}
